split data folder into separate repo
calliope-project/euro-calliope pull request #112
Opened 2021-05-05 13:09 UTC by silas-schweizer

Simple split, doesn't support multiple repos and subfolder selection

2021-05-05 13:15 UTC, silas-schweizer commented
@brynpickering and @sjpfenninger  can you please review this?

2021-05-05 13:19 UTC, suvayu commented
This fixes #104. Can someone link the issues? I do not have permission.

2021-05-05 14:05 UTC, sjpfenninger commented
@suvayu @silas-schweizer  Did you test this locally?

2021-05-05 14:15 UTC, FLomb requested changes
Reviewed the pull request with @sjpfenninger. We fixed some minor issues with the rule definition (see commits), but still it looks like the rule isn't applied. We weren't able to test the rule, it doesn't seem to be recognised by snakemake

2021-05-05 14:41 UTC, suvayu commented
> @suvayu @silas-schweizer Did you test this locally?

No, clearly this wasn't trivial. I'm not sure I understand the dependency resolution used by snakemake. I'll scour the docs.

2021-05-05 16:49 UTC, brynpickering reviewed
Possible alternative given, which downloads individual files on the fly (also reducing the number of files that need to be downloaded, if a user chooses to only run part of the workflow).

This might need updating so it doesn't clash with the search for data in `data/automatic`.

2021-05-05 16:49 UTC, brynpickering commented on Snakefile
> +rule import_data_submodule:
Since you can curl any file you like from github, you could turn this into a wildcarded rule:

```suggestion
rule import_data_submodule:
    params: url = lambda wildcards: config["data-sources"]["data-repository"].format(dataset=wildcards.dataset)
    output: "data/{dataset}"
    shell: "curl -sLo {output} {params.url}"
```
Here, the config url would be `https://raw.githubusercontent.com/calliope-project/euro-calliope-datasets/main/{dataset}`.

Then if snakemake can't find the data (i.e. a user hasn't chosen to put in their own version of it), it will extract it from the repository on the fly, when looking for this dataset (e.g., [here](https://github.com/calliope-project/euro-calliope/blob/4de2d8af279990251ccfa7e7b05b18ce8c0c63cd/rules/hydro.smk#L115))

2021-05-05 17:15 UTC, brynpickering commented on Snakefile
> +rule import_data_submodule:
Committed this alternative as it seems to work well

2021-05-06 05:38 UTC, sjpfenninger reviewed
Ideally, the data repository would be a modified copy of the main repository with everything but `data` removed, so that the history of edits to `data` is preserved.

2021-05-06 05:38 UTC, sjpfenninger commented on config/default.yaml
> +    data-repository: https://raw.githubusercontent.com/calliope-project/euro-calliope-datasets/main/{dataset}
Seems like an elegant solution that also allows versioning, i.e. the v.1.1 version of the euro-calliope repo can set data-repository to a v1.1 tagged version of the data

2021-05-06 09:53 UTC, suvayu commented
> Ideally, the data repository would be a modified copy of the main repository with everything but `data` removed, so that the history of edits to `data` is preserved.

IIUC, the datasets are final results from papers, or post-processed data releases, so what do you mean by history here?  I would think it's just addition of whole datasets.  I'm not sure if there's any useful information there.  If retaining the history is important, I can of course do some surgery and retain only the history of the `data` folder and push that to the data repository.

2021-05-06 20:02 UTC, suvayu commented
There's only one notebook in the repo (in `notebooks/`), maybe you mean the scripts in `scripts/`?  Also, keeping preprocessing steps in a notebook isn't a good idea.  If a notebook is necessary because of accompanying visualisations, I would either split that out, or use something like [`jupytext`](https://jupytext.readthedocs.io/en/latest/install.html) to convert to a script and keep them in sync.  But that can be done after the repo split.

2021-05-07 15:28 UTC, brynpickering commented
> There's only one notebook in the repo (in `notebooks/`), maybe you mean the scripts in `scripts/`? Also, keeping preprocessing steps in a notebook isn't a good idea. If a notebook is necessary because of accompanying visualisations, I would either split that out, or use something like [`jupytext`](https://jupytext.readthedocs.io/en/latest/install.html) to convert to a script and keep them in sync. But that can be done after the repo split.

No, it's the notebook (I hadn't notceid that there was only one). @timtroendle how do you want to proceed on data pre-processing scripts that are outside the scope of the workflow?

2021-05-07 15:36 UTC, timtroendle commented
I agree with @brynpickering that 
* the notebook should move as well,
* data should be deleted here.

In addition, data and notebook folders can be deleted (when you do, please also update the documented repo structure -- the documentation exists twice now: once in README.md and once in the new documentation folder).

When it comes to the question of notebook format or not, I have no strong feelings. Just keep in mind that this script must be execute only once per update of the data. Since the raw data is always in a slightly different format, I found a notebook easier to handle that than a script. But really, it does not matter much in my opinion.

2021-05-13 15:59 UTC, brynpickering commented
@suvayu @silas-schweizer I think this now only needs a changelog update and the notebook to be added to the `euro-calliope-datasets` repository....

2021-05-14 10:47 UTC, suvayu commented
@calliope-project/euro-calliope-devs can you have look at https://github.com/calliope-project/euro-calliope-datasets, and check if it meets expectations?

2021-05-14 11:36 UTC, suvayu commented
The commit I wanted to push is [attached](https://github.com/calliope-project/euro-calliope/files/6478475/0001-data-sources-update-data-repository-url.txt).  To apply: `git am path/to/patch`.

2021-05-14 11:39 UTC, sjpfenninger commented
Looks good to me. From a documentation and understandability perspective, would it make sense to have each dataset be in a top-level dir (either with a README inside, or along with a central list of all datasets = top-level dirs). That would mean having files with different spatial resolution inside the top-level dir, rather than top-level dirs for each spatial resolution with multiple datasets inside.

2021-05-14 12:02 UTC, timtroendle commented
https://github.com/calliope-project/euro-calliope-datasets looks good to me. Nice conservation of the Git history there! 👍

Some datasets are not needed anymore as they are automatically downloaded from Zenodo now. Those are the two datasets "farmland.csv" and "land-cover.csv" for all three resolutions. That means all three top-level folders `continental`, `national`, `regional` can go entirely. This resolves your comment, @sjpfenninger.

2021-07-15 14:39 UTC, brynpickering commented
@timtroendle Is there any reason this can't be merged in?

2021-07-15 14:49 UTC, timtroendle commented
Hm, I am not a reviewer here. But none of the three reviewers has accepted the change. 

I have on comment, though: As I mentioned above, some datasets aren't needed anymore and I suggest to remove them before merging this.

2021-07-15 15:05 UTC, brynpickering approved these changes

2021-07-16 18:48 UTC, timtroendle requested changes
The use of data folders is inconsistent now and I think we should fix it before merging this change.

2021-07-16 18:48 UTC, timtroendle commented on README.md
> +* `data`: Contains data automatically downloaded within the model build process (does not exist initially).
This change is incorrect. `data/automatic` still exists and will be used for all data automatically downloaded from other sources than euro-calliope-datasets.

I don't think it makes sense to load euro-calliope-datasets into `data` and load all other datasets into `data/automatic`. We should either load everything into `data` or everything into `data/automatic` because to the user, it really makes no difference where the data are downloaded.

I prefer the latter. One may use manually downloaded data (I do that often) and one would want to differentiate it from automatically downloaded data. Therefore, I'd go for downloading everything into `data/automatic`.

2021-07-19 08:55 UTC, timtroendle commented on Snakefile
> +rule import_data_submodule:
Can we rename this rule to `download_xxx`, e.g. `download_eurocalliope_dataset`?

It's really useful to be able to tell by the name that this is a rule downloading data.

2021-07-19 10:49 UTC, brynpickering commented on README.md
> +* `data`: Contains data automatically downloaded within the model build process (does not exist initially).
Ideally it would be differentiated from the rest of the data in `data/automatic` so that we can have a wildcard constraint that ignores this rule unless downloading from the eurocalliope-dataset repo (as is currently the case). It could go into something like a `data/eurocalliope-dataset` directory?

2021-07-19 10:55 UTC, brynpickering commented on README.md
> +* `data`: Contains data automatically downloaded within the model build process (does not exist initially).
This would also enable a user to delete all the data from the dataset in one go (e.g. if they update the GH repo pointed to in the config) without having to work out which subdirs in `automatic` or elsewhere are coming from there.

2021-07-19 11:37 UTC, brynpickering requested changes
Need to sort out mistake with EEZ filepath change and update curl to return error on 404, not to save a file with the error in it.

2021-07-19 12:59 UTC, brynpickering approved these changes

2021-07-19 12:59 UTC, brynpickering commented
Minimal workflow completes successfully with latest commit.

2021-07-20 13:18 UTC, timtroendle approved these changes

2021-07-20 13:59 UTC, merged

2021-07-20 14:08 UTC, timtroendle commented
Thanks @silas-schweizer @suvayu @sjpfenninger @FLomb @brynpickering for your work on this!