Move across annual energy balance from 2.0 repository
calliope-project/euro-calliope pull request #113
Opened 2021-05-05 13:39 UTC by sjpfenninger

Fixes #100

2021-05-05 13:40 UTC, sjpfenninger commented
Needs contributor info added in when merging

2021-05-05 14:00 UTC, sjpfenninger commented
@brynpickering Also this is missing the two files that need to be moved across to the `data` directory -- pending that being possibly removed from the repository

2021-05-05 14:49 UTC, FebinKa reviewed
Only minor comments, took me a while to get oriented but as far as I understood the code, it seems to make sense.

2021-05-05 14:49 UTC, FebinKa commented on config/schema.yaml
> +                        description: Base UR for Eurostat data
*URL

2021-05-05 14:49 UTC, FebinKa commented on scripts/annual_energy_balance.py
> +    """
Why does only this function have a description? Would probably be helpful to have one for the others as well

2021-05-05 15:00 UTC, brynpickering requested changes
The first 2.0 update - woohoo!

A bunch of changes to make to try and simplify things (my initial implementation was perhaps too verbose ;) )

Functions added to eurocalliopelib should be tested, and the final `annual-energy-balance.csv` file should be tested, to ensure it has at least the expected countries and multi-index levels.

Final point: this feature should be added to the `feature-sector-coupling`, so the PR needs updating (or re-submitting?) to point to a merge on that branch.

2021-05-05 15:00 UTC, brynpickering commented on lib/eurocalliopelib/utils.py
> +def get_alpha2(country, eurostat=True):
This should possibly have the same structure as `eu_country_code_to_iso3`, or merge them with the option to spit out ISO2 or ISO3, or make it a class which subclasses pycountry?

2021-05-05 15:00 UTC, brynpickering commented on rules/data-processing.smk
> +rule eurostat_data_tsv:
Agreed with your PR comment that this would be better generalised. A possible solution would be: 
```suggestion
rule eurostat_data_tsv:
message: "Get {wildcard.dataset} from Eurostat"
params: 
    base_url = config["data-sources"]["eurostat"]["base-url"],
    file_url = lambda wildcards: config["data-sources"]["eurostat"]["{wildcards.dataset}"]
output: protected("data/automatic/{dataset}.tsv.gz")
shell: "curl -sLo {output} {params.base_url}{params.file_url}.tsv.gz"
```

Then when using this data as input you need to refer to the filename rather than the rule (`rules.eurostat_data_tsv.output.energy_balance` -> `"data/automatic/energy-balance.tsv.gz"`)

2021-05-05 15:00 UTC, brynpickering commented on rules/data-processing.smk
> +rule ch_data_xlsx:
See suggestion above, could be reproduced here, just with `protected("data/automatic/ch_{dataset}.tsv.gz")`

2021-05-05 15:00 UTC, brynpickering commented on rules/data-processing.smk
> +rule eurostat_data_tsv:
To differentiate from the ch one, output should probably be `protected("data/automatic/eurostat_{dataset}.tsv.gz")`

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +        ["cat_code", "carrier_code", "unit", "country"]
maybe this list could be in config?

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +    ch_energy_carriers = {
Maybe have these at the top of the script as a constant?

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +    ch_energy_carriers = {
In fact, maybe this could be in a new lib util file related to opening files?

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +    df = df.groupby(axis=1, level=0).sum().groupby(level=[0, 1]).sum()
use explicit level names rather than numbers? Would make the script more explicit.

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +        #    'FERNWÄRME KUMULIERT': 'heat',  # total
Maybe the source of 'heat' could be configurable - choosing between "FERNWÄRME KUMULIERT", "FERNWÄRME BEZUG", "FERNWÄRME ABGABE"

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +        _df.groupby(axis=1, level=0)
explicit level name

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +    remove_digits = str.maketrans("", "", digits)
could be a util function, then we can test it!

2021-05-05 15:00 UTC, brynpickering commented on scripts/annual_energy_balance.py
> +        .assign(cat_code=cat_code)
I frequently added multiindex levels using this 'assign->set_index' functionality. This could be moved to a lib util function.

2021-05-14 07:56 UTC, sjpfenninger commented on scripts/annual_energy_balance.py
> +    """
@brynpickering could you supply minimal docstrings for all these functions?

2021-05-14 15:51 UTC, brynpickering approved these changes

2021-05-14 15:51 UTC, merged