Add basic docs
calliope-project/euro-calliope pull request #114
Opened 2021-05-05 13:57 UTC by FebinKa

Adding README.md as documentation using Sphinx to address issue #106

2021-05-05 14:55 UTC, sjpfenninger requested changes
Looks good. I have only one comment regarding setting the version number, and a question:

Should the dependencies be in the environment.yml file (I added them in there for now) or a separate docs file? If we later build DAG graphics for the docs I guess we need all requirements in one place to build the docs e.g. on RTD.

I also made two minor changes:

* increased header level in markdown file as prep for splitting across top-level headings
* changed to RTD sphinx theme (cleaner than alabaster I think but happy to revert if you disagree)

2021-05-05 14:55 UTC, sjpfenninger commented on docs/source/conf.py
> +release = "1.1"
Should the version be pulled from somewhere else, e.g. at the top level of the repo?

2021-05-05 16:01 UTC, sjpfenninger approved these changes

2021-05-05 16:06 UTC, merged

2021-05-06 05:08 UTC, timtroendle commented
@FebinKa @sjpfenninger For my understanding: you copied the content from README.md to the new doc. As with any copy, it's only a matter of time until the two will get out of sync. How do you think we should handle that?

2021-05-06 07:58 UTC, FebinKa commented
It's not exactly the same as @sjpfenninger changed the header levels and the file was formatted to include the sources before the license. The goal would be to address #103 through the Sphinx documentation and using the copy allows to paste the new inputs at the appropriate places. However, it would also be possible to [directly link](https://stackoverflow.com/a/17217041/15452089) to the readme instead by creating `readme_link.rst` inside `docs/source` which contains ` include:: ../../README.md` and calling that instead of `overview` in `index.md`.

2021-05-06 08:08 UTC, timtroendle commented
Thanks for the clarification. I am really just worried that we are now maintaining two things, and we should have a strategy moving forward how to handle that.

2021-05-06 18:09 UTC, brynpickering commented
@FebinKa I like the suggestion to point to the README directly to fill in the 'overview' information, instead of the copy-paste job we did. Perhaps you could implement that? In fact, the index could just show that, then we don't have to worry about having moved some but not all things from the readme to the index. The sub-pages can be reserved for more details on the workflow.