Adding Danish Energy Agency cost data and removing default costs
calliope-project/euro-calliope pull request #128
Opened 2021-06-17 09:18 UTC by FebinKa

Fixes #18  .

Forces user to specify a source for cost assumptions using overrides. Currently, [etri](https://publications.jrc.ec.europa.eu/repository/handle/JRC92496) or [dea](https://ens.dk/en/our-services/projections-and-models/technology-data/technology-data-generation-electricity-and) can be chosen for `renewable-cost` and etri and Schröder et al. ([2013](https://www.econstor.eu/bitstream/10419/80348/1/757528015.pdf)) for `hydro-cost` while more sources can be added in `cost-overrides.yaml`.

Two potential issues:

1. When no override is specified, the model assumes that technologies are free to use
2. There are errors in rule test that I can't quite trace

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-06-17 10:41 UTC, timtroendle requested changes
Thanks for this! Can you post the error or failure of the tests?

This looks like a great start, but still requires some work. I've included some comments. My main concern is "default" cost. You are saying that Calliope simply assumes 0 cost, if no other cost is defined, correct? We cannot allow that, as it is too error-prone and will very likely lead to unintended effects. In fact, I think you have such an error in your documented model runs in the README.md. @brynpickering , any ideas how we can **enforce** cost overrides?

I did not double-check all parameter values. I will do as soon as we got everything else right.

2021-06-17 10:41 UTC, timtroendle commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
If I'm not mistaken here, running the model like this will mean that storage is cost free.

No matter whether I am right or wrong here, default cost being 0 is error-prone and will very likely lead to unintended results for some users and some models.

2021-06-17 10:41 UTC, timtroendle commented on templates/cost-overrides.yaml
> +        techs.open_field_pv: #Table 7
There should be a whitespace after the comment sign `#`.

2021-06-17 10:41 UTC, timtroendle commented on templates/cost-overrides.yaml
> +        techs.pumped_hydro.costs.monetary:
Having `pumped_hydro` in the storage cost override is problematic, because we (I at least) usually don't give it cost, see #129, and switching off pumped_hydro cost in another override is impossible in Calliope.

Not sure what to do about that. Maybe pumped hydro should move to hydro-cost?

2021-06-17 10:41 UTC, timtroendle commented on templates/renewable-techs.yaml
>              lifetime: 60
Being consistent, this number must go.

2021-06-17 10:41 UTC, timtroendle commented on templates/renewable-techs.yaml
>              lifetime: 60
Same here.

2021-06-17 10:41 UTC, timtroendle commented on templates/renewable-techs.yaml
> -            lifetime: 25 # [@JRC:2014] Table 7
Changes in this file are good. But: what about `storage-techs-yaml`? Also, for consistency, I think you should move  cost parameters in `link-techs.yaml`, too.

2021-06-17 12:01 UTC, FebinKa commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
This is supposed to be the default configuration. If you want the user to have the responsibility of choosing a source for costs, an actual default would not work and if I understood the previous discussion of issue #18 correctly, scenarios cannot be combined with overrides under Calliope 0.6.5. This approach then allows to add further overrides whereas a scenario `default-cost` would prohibit that.

The storage cost is still defined in `storage-techs.yaml` for now so there is no need to call an override here. In fact, I think the storage costs inside of `cost-overrides.yaml` are off now that I checked them, they are missing scaling factors (0.14 for battery, 1.02 for PHS, 0.33 for hydrogen) since I wasn't sure about the reason for their inclusion. 
I'd suggest to just move the storage cost and lifetime from `storage-cost.yaml` here instead of having it as an override since there is only one source for now and that allows to address your issue with `pumped_hydro` below.

2021-06-17 12:01 UTC, FebinKa commented on templates/cost-overrides.yaml
> +        techs.pumped_hydro.costs.monetary:
That would still cause the same issue as a `hydro-cost` override has to be selected to have operational costs, in which case the same conflict would arise. I'm thinking of having Schmidt as the default cost for storage instead of as an override in which case the override conflicts could be avoided.

2021-06-17 12:01 UTC, FebinKa commented
I agree regarding the default cost, that is why I kept the information for `link-techs.yaml` and `storage-techs.yaml` in the respective files since there are no other sources for now. Alternatively, I can move all of the cost and lifetime information for all technologies to `cost-overrides.yaml` and only define overrides for the renewable technologies so that all such data can still be found within one file (which might then need another name). However, in that case, all three techs-files only initialize technologies and are rather empty otherwise, does that fit with your intention? Also, the issue that the cost of renewable technologies is zero unless an override is chosen still persists under that situation.

The error notitification looks as follows but I can't figure out which rules lead to this error:
```
[Wed Jun 16 16:59:21 2021]
Error in rule test:
    jobid: 4
    output: build/logs/continental/test-report.html
    conda-env: /cluster/scratch/fkachirayil/euro-calliope-cost-override/.snakemake/conda/b51943c8
    cluster_jobid: Job <175635358> is submitted to queue <normal.4h>.

Error executing rule test on cluster (jobid: 4, external: Job <175635358> is submitted to queue <normal.4h>., jobscript: /cluster/scratch/fkachirayil/euro-calliope-cost-override/.snakemake/tmp.5j7t90fh/snakejob.test.4.sh). For error details see the cluster log and the log files of the involved rule(s).
[Wed Jun 16 17:00:01 2021]
Error in rule test:
    jobid: 5
    output: build/logs/national/test-report.html
    conda-env: /cluster/scratch/fkachirayil/euro-calliope-cost-override/.snakemake/conda/b51943c8
    cluster_jobid: Job <175635360> is submitted to queue <normal.4h>.

Error executing rule test on cluster (jobid: 5, external: Job <175635360> is submitted to queue <normal.4h>., jobscript: /cluster/scratch/fkachirayil/euro-calliope-cost-override/.snakemake/tmp.5j7t90fh/snakejob.test.5.sh). For error details see the cluster log and the log files of the involved rule(s).
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /cluster/scratch/fkachirayil/euro-calliope-cost-override/.snakemake/log/2021-06-16T160503.754066.snakemake.log
```

2021-06-17 13:09 UTC, timtroendle commented
Regarding the test failure: you need to check the log files of the rules, as indicated in the error message. Those should be in `build/logs/test.resolution=YOUR_RESOLUTION.log` on the cluster.

2021-06-17 13:12 UTC, timtroendle commented on templates/cost-overrides.yaml
> +        techs.pumped_hydro.costs.monetary:
You are right. We can circumvent that issue by defining operational costs in the `no-hydro-fixed-cost` override, though.

2021-06-17 13:13 UTC, timtroendle commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
Regarding a `default-cost` override: I don't see an issue with that. Users of 0.6.5 don't have to use it if they don't want to. Users of 0.6.7. won't have any issues -- so we are future-proof here.

2021-06-17 13:14 UTC, timtroendle commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
Regarding a `default-cost` override: I don't see an issue with that. Users of 0.6.5 don't have to use it if they don't want to. Users of 0.6.7. won't have any issues -- so we are future-proof here.

2021-06-17 13:17 UTC, timtroendle commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
Regarding storage and link default costs: fair point. This leads to a slightly inconsistent state though: default cost for storage and links are always chosen and defined in their files. Default costs for renewables aren't chosen and defined in the override file.

We should go for either one solution in my opinion: either all default costs are defined in their respective technology files, or they are all defined in the overrides. I had hoped we could go for the latter, but if that's not possible, maybe we should go for the former.

2021-06-17 13:19 UTC, timtroendle commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
We are overthinking this. What do you think of reverting all default costs as they used to be, and only add _new_ cost parameters from DEA in this file? Let's get this done and then decide on possible other changes later.

2021-06-17 13:47 UTC, FebinKa commented on README.md
> +$ calliope run ./build/model/national/example-model.yaml --scenario=etri-renewable-cost,etri-hydro-cost
The updated version should work, if you want to have default costs for renewable technologies in addition to storage and transmission, it suffices to move `etri-renewable-cost` and `etri-hydro-cost` from the overrides to the fixed values in `tech-costs.yaml`.

2021-06-18 11:11 UTC, timtroendle requested changes
Almost there, but it still requires some minor changes.

I still need to do two things: double check all parameter values and run tests. Will do after your updates.

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +tech_groups: # Generation from [@JRC:2014]
Can you remove this comment, make sure that each `tech` or `tech_group` has exactly one root entry (most have, but e.g. `battery` has not) and then add the comment with the source to each root entry?

```yaml
tech_groups:
    pv_on_roof: # taken from [@JRC:2014]
        cosntraints.lifetime: 35
[...]
techs:
    battery: # taken from [@schmidt:2019] Table 4
        costs.monetary:
            [...]
        constraints.lifetime: ...
[...]
```

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +    # Generation from [@JRC:2014]
As above, comment should go to each technology.

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +    # Storage from [@schmidt:2019] Table S4
here too

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +    # Transmission from [@JRC:2014], Table 39
and here

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +    dea-renewable-cost: # from [@DEA:2020]
The source [@DEA:2020] is not in `https://github.com/calliope-project/euro-calliope/blob/develop/docs/source/sources.md`.

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +    ac_transmission.constraints.lifetime: 60
Please align ac_transmission to one root key (as shown above).

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +    hydrogen.constraints:
Please align hydrogen to one root key (as shown above).

2021-06-18 11:11 UTC, timtroendle commented on templates/tech-costs.yaml
> +        # since hydro is constrained to current capacities
This second line is not correct and should simply go.

2021-06-22 12:06 UTC, timtroendle requested changes
This looks very good now. Last request to you from my side: can you update the CHANGELOG with your contribution?

I will

* run the test
* verify parameter values en detail

2021-06-23 10:01 UTC, timtroendle requested changes
The only remaining thing are the parameter values in detail. I added another round of review comments regarding those and I think there's a good chance this will be the final round of comments. Most comments are very simple, only the comments on PV lifetime and biomass tech choice may require some thinking.

You may have seen, I've also added tests of your overrides and they work well! This is going to be extremely useful, and we are 95% there.

2021-06-23 15:29 UTC, FebinKa commented on templates/tech-costs.yaml
> +            constraints.lifetime: 40
The other elements of the system besides the inverter don't need to be replaced during the lifetime of the PV plant and the cost for the inverter replacement is included in O&M costs according to comment P in the data sheet so I think it should be fine. 

They explain their notion of technical lifetime in the associated [report on p.20](https://ens.dk/sites/ens.dk/files/Statistik/technology_data_catalogue_for_el_and_dh_-_0009.pdf) - it is a theoretical value based on experience. Their value matches the technical lifetime from [this IRENA report](https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2016/IRENA_IEAPVPS_End-of-Life_Solar_PV_Panels_2016.pdf). There, they mention that the average lifetime is still closer to 30-35 years but the DEA also uses these values for 2015 and 2020 respectively. I think they just project improvements that allow to increase the average lifetime further until 2050.

2021-06-23 15:29 UTC, FebinKa commented on templates/tech-costs.yaml
> +                energy_cap: {{ 935800 * scaling_factors.specific_costs}} # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MW") }}
I'll wait to update this until we decide on a type of biomass plant to use and then scale the costs using the Annual Average Net Electrical Efficiency if that sounds reasonable to you.

2021-06-23 15:30 UTC, FebinKa commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
Agreed that extraction plants would seem better suited but "large" means ~250MW_el per unit if I read the table correctly (`Generating capacity for one unit (MWe)`) and even more for the pellet-based extraction plant. Since they have no data for medium-sized extraction plants, I chose to use a combined plant with ~25MW_el instead.

2021-06-23 15:30 UTC, FebinKa commented on templates/tech-costs.yaml
> +                om_prod: 0 # Table 34
It's probably lower according to [Figure 7.4](https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2015/IRENA_RE_Power_Costs/IRENA_RE_Power_Costs_2014_report_chapter7.pdf) where IRENA suggests that it is around 30% for Europe. However, they also mention that it's very heterogeneous and depends on the plants that are considered so I think it's fine to work on this assumption unless we have better data.

2021-06-23 15:35 UTC, FebinKa commented on templates/tech-costs.yaml
> +                energy_cap: {{ 560000 * scaling_factors.specific_costs}} # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MW") }}
Does it make sense to add that as a comment (`with DC/AC sizing factor`) as well or is it redundant since the user won't see the use of the factor?

2021-06-23 15:59 UTC, timtroendle commented on templates/tech-costs.yaml
> +                energy_cap: {{ 560000 * scaling_factors.specific_costs}} # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MW") }}
You don't necessary need to apply the factor yourself. You used rows 24 ans 26, but instead you should use data from rows 25 and 27. That data are 5% larger.

2021-06-23 16:00 UTC, timtroendle commented on templates/tech-costs.yaml
> +            constraints.lifetime: 40
Good! Could you provide a very short gist of that in a comment in that line? For example `# inverter lifetime is shorter but included in O&M cost` or so?

2021-06-23 16:01 UTC, timtroendle commented on templates/tech-costs.yaml
> +                energy_cap: {{ 935800 * scaling_factors.specific_costs}} # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MW") }}
Waiting for a decision makes a lot of sense. But as for PV, you don't need to scale the data (you shouldn't even I guess). The values are all in the Table.

2021-06-23 16:13 UTC, timtroendle commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
Good catch! I mixed this up in the PDF.

Argh, this is difficult! I just compared the electricity efficiency of the two and they are 29% for CHP and 39% for extraction. In euro-calliope the default value is 45% (from ETRI) -- that would mean the extraction plant would fit better. Either way, I guess there are reasons to choose either one and I leave it up to you.

But (I know we discussed this before) this means that it may make sense to move biomass to its own override? A user may decide that either one fits better to their concrete model and then they could not use the override for solar and wind as it would prohibit them to use their own biomass override.

2021-06-23 17:33 UTC, FebinKa commented on templates/tech-costs.yaml
> +                energy_cap: {{ 560000 * scaling_factors.specific_costs}} # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MW") }}
True, that works here but not for large PV

2021-06-23 18:38 UTC, FebinKa commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
I wonder how much of that is due to different assumptions in the two datasets. ETRI has efficiency improvements between 5-15% for the different types of biomass while the DEA assumes that efficiencies won't meaningfully improve (while allowing for up to 41% electricity efficiency as the upper boundary for CHP). 

The DEA dataset also has large differences in costs for the two technologies. Extraction plants have O&M costs less than half those of medium CHP plants. Comparing these costs to large CHP plants shows that the cost benefit is mostly due to scale effects, which are unlikely to materialize since plants this large are [less common](https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2015/IRENA-ETSAP_Tech_Brief_E05_Biomass-for-Heat-and-Power.pdf).

Personally, I would have a preference for the CHP plant over the extraction plant since its size is more representative. Even if the model only looks at electricity, CHP plants are nonetheless more likely to be installed than pure extraction plants in reality (which is obviously also an assumption but I would think a reasonable one) so it might also be more accurate to work with those efficiencies than those that can be reached when a plant is optimized for electricity generation. 

I think the difficulty in providing multiple overrides is that a reasonable justification for why we included only the selected technologies and no other alternatives (e.g large wood chips or medium wood pellets) still remains arbitrary, particularly for biomass given its heterogeneity. Maybe Fei might have something to chip in but otherwise I would say that it makes sense to keep only one override for now (more overrides can always be added later) since users still have the opportunity to manually add overrides if this assumption is that critical for their model.

2021-06-24 06:08 UTC, timtroendle commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
Agreed.

Only addition from my side: it probably would be good to mention the inconsistent efficiency value in the documentation of the `dea` override. We cannot change the efficiency value within the override for reasons that exceed the scope of this PR, but users can do that manually in their models. For that, they need to be aware, and a comment in the doc may help to ensure that.

2021-06-24 09:00 UTC, brynpickering commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
Sorry to jump in on this so late! We looked at the most 'useful' CHP techs to consider  for v2.0 and based on discussion with some Belgian colleagues, it was agreed that extraction plants are the most likely to exist moving forward. Nonetheless, it seems that you're missing up your `biofuel` tech here, since I recall it being a black box representing anaerobic digestion to biogas + gas engine/turbine. This makes more sense for a power-system-only model, where you don't want to be paying for a system that is supposed to also be able to meet heat demand. 

Perhaps `06 Gas engines, biogas` could work well? If yes, you would then also need to include a biofuel -> biogas plant, which can be found in various forms in the DEA renewable_fuels datasheet.

2021-06-25 09:35 UTC, FebinKa commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
I am not entirely sure what you mean, do you suggest to use `06 Gas engines, biogas` instead of `09a Wood Chips, medium` (or rather `09a Wood Chips extract. plant` according to your discussion)? Or would the idea be to combine them? The former approach leads to massively lower costs for the `biofuel` tech and the latter risks breaking relative cost consistency between different techs as biofuel would be significantly more expensive using the DEA override unless this cost is also added to the ETRI cost data (e.g. using CCGT?).

If the idea is to combine both of these elements, the lifetimes are fortunately identical for the DEA dataset (but not for the ETRI dataset) and I guess the costs could also straightforwardly be added but I am unsure how to address the differing efficiencies? Should they be multiplied since there are probably still losses when turning biomass into biofuel or does it make sense to simply use the efficiency of the gas engine since the feedstock is then fed into it instead of the CHP (or extraction) plant?

Overall, this seems to be a much more complex issue that is mostly unrelated to the cost data itself. Would it make sense to remove biomass from the `dea` override as Tim proposed above and to address this in a separate issue or would this ideally also be addressed here?

2021-06-25 10:16 UTC, brynpickering commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
I'm proposing updating to represent two technologies in one (as is currently the case): `biomass -> biogas + biogas -> electricity`. From DEA this would be `81 Biogas Plant, Basic conf. + 06 Gas engines, biogas`. The former tech is found in the 'renewable fuels' DEA spreadsheet.

2021-06-25 11:09 UTC, FebinKa commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
Okay, I updated it, does this look like what you had in mind? 

The efficiency of the gas engine is also at 45% and though the lifetime of the biogas plant is given at 20 years, I used the 25 years of the gas engine. I also excluded the O&M cost for heat since you mentioned that you don't want to pay for heat in a power system model but even so, O&M is twice as expensive for DEA than for ETRI.

2021-06-25 11:30 UTC, brynpickering commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
That's the general idea, except that costs for the biogas plant would need to be updated to be in terms of electrical output (1MW_e = 2.22MW_biogas @45% efficiency), so the cost of the biogas plant would become `1.39mio_eur/MW_biogas -> 3.1mio_eur/MW_e`. Similarly for `om_annual`. The efficiency of conversion should also include the conversion efficiency of biomass to biogas (0.75 GJ/ton input)... Basically it's very complicated and difficult to know if it's "correct" :P

2021-07-01 08:38 UTC, FebinKa commented on templates/tech-costs.yaml
> +        techs.biofuel:  # Sheet 09a Wood Chips, Medium (CHP with 80MW feed) (2020)
Okay, I also discussed this with Tim and I think in that case it makes sense to focus on the costs here and address this in a separate issue, I removed biofuel from the override and hope the rest is fine.

2021-07-06 15:19 UTC, timtroendle approved these changes

2021-07-06 15:33 UTC, timtroendle commented
I double-checked: The minimal-config test runs through without issues. This means we can merge this change -- which turned out to be a rather nasty one in the end. Still, I think we found a good solution eventually. Thanks a lot @FebinKa for this work!

2021-07-06 15:37 UTC, merged