Add JRC-IDEES data processing pipeline
calliope-project/euro-calliope pull request #133
Opened 2021-07-16 14:47 UTC by brynpickering

First step to fixing #17 & #102 and blocking #119.

Now that the JRC IDEES database is available via FTP, we can roll the processing of the data into Euro-Calliope. This allows the transport, industry, and tertiary (commercial) sector data to be processed for the components that we need down the line. The processing takes the largely machine-unreadable data from JRC-IDEES and turns into tidy dataframes for use elsewhere.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-07-16 18:23 UTC, timtroendle requested changes
Only very few comments about functionality, but a lot about structuring the code and readability.

I still think readability is important here. These kinds of data processing scripts are in most cases super difficult to read but structure and descriptions can ease the pain to some degree. You may not agree with all my comments and that's fine of course.

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/industry.py
> +            .assign(country_code=df.index.name.split(':')[0], cat_name=df.index.name.split(': ')[1], unit='kt')
as above. consider making this a four-liner

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/industry.py
> +        df.loc[
You are doing four times the same here. Can you shorten this?

This is not super important. But the CARRIER_NAMES mapping in tertiary.py is more or less what's lacking here, and I find it very clear.

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/tertiary.py
> +    data_filepaths = glob.glob(os.path.join(data_dir, "*.xlsx"))
this can also be 

```
import Path from pathlib

Path(data_dir).glob("*.xlsx")
``` 

it doesn't really matter of course, just a fyi in case you didn't know. I personally like pathlib's API much better.

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/tertiary.py
> +    processed_data = get_tertiary_sector_data(data_filepaths)
As above, this could be `pd.concat([get_tertiary_sector_data(file) for file in files])` and you'd get rid of the append-to-list-pattern and you'd replace it by a list comprehension.

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/tertiary.py
> +        df_demand = pd.read_excel(file, sheet_name='SER_hh_tes', index_col=0)
Hmm, what ecaxtly is the difference between consumption and demand?

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +    Subfuels (e.g. biodiesel) are given as 'of which ...', meaning the main fuel consumption
So annoying when they do that. Nice for humans of course, terrible for automation.

2021-07-16 18:23 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +def process_jrc_transport_data(data_dir, dataset, out_path):
A lot of the comments in `industry.py` apply here too.

2021-07-18 17:12 UTC, brynpickering commented on environment.yaml
> +    - snakemake-minimal=6.1.1
To allow a wildcard in a 'script' call. I can't find the exact version where they made this fix in the changelog, but it doesn't work in 5.8.2 and does in 6.1.1... This may be an unnecessary update if I re-write some of the rules as per your suggestions later in this review.

2021-07-18 17:13 UTC, brynpickering commented on lib/eurocalliopelib/utils.py
> +    series = series.astype(str).str.extract("(\\-*\\d+\\.*\\d*)")[0]
It believe it did, I was fixing it due to a futurewarning only. I'll still add a test to be certain.

2021-07-18 17:14 UTC, brynpickering commented on rules/data-processing.smk
> +    message: "Process {wildcards.dataset} {wildcards.sector} data from JRC-IDEES to be used in understanding current and future {wildcards.sector} demand"
I don't need to, but thought it worked quite nicely to keep the number of rules down :) I will split it out to a rule per sector since that will also obviate the need for an update to >=6.0.0.

2021-07-18 17:16 UTC, brynpickering commented on scripts/jrc-idees/industry.py
> +def process_jrc_industry_data(data_dir, dataset, out_path):
I wouldn't say 'not a fan', but rather that when I wrote most of this code in a Jupyter notebook I was not thinking too much about the final structure, so didn't think to parcel everything up into subfunctions as I was going along. A lot of this is just a copy-paste job from the notebook.

I can improve legibility, why not ;)

2021-07-18 17:17 UTC, brynpickering commented on scripts/jrc-idees/industry.py
> +            idx = style_df[col].style.font_color.isin(v).loc[:idx_end]
yup.

2021-07-18 17:18 UTC, brynpickering commented on scripts/jrc-idees/industry.py
> +        df['section'] = df.section.ffill()
you mean with "ffill"?

2021-07-18 17:19 UTC, brynpickering commented on scripts/jrc-idees/tertiary.py
> +    data_filepaths = glob.glob(os.path.join(data_dir, "*.xlsx"))
Agreed, that is nicer! There had been another subdir in this list, which made it more worthwhile to join everything.

2021-07-18 17:21 UTC, brynpickering commented on scripts/jrc-idees/tertiary.py
> +        df_demand = pd.read_excel(file, sheet_name='SER_hh_tes', index_col=0)
The efficiency losses in converting from a commodity (gas, electricity, coal, etc.) to an end-use (steam heat, space heat, machine operation, distance travelled, etc.).

2021-07-19 08:01 UTC, timtroendle commented on scripts/jrc-idees/industry.py
> +        df['section'] = df.section.ffill()
Yes. The reason for this comment is the following: While most other things are just restructuring data, this line is manipulating data. It replaces nan with the last seen value, right? I don't really understand why this is fine, or what this is for. But if it's any important, it would be good to add a comment. If it's unimportant, just ignore my comment.

2021-07-19 10:15 UTC, brynpickering commented on scripts/jrc-idees/industry.py
> +        df['section'] = df.section.ffill()
fair enough, although it still fits with restructuring data. I've left a comment nonetheless.

2021-07-20 14:27 UTC, timtroendle approved these changes
Just a few more minor changes.

2021-07-20 14:27 UTC, timtroendle commented on lib/tests/test_utils.py
> +            "-", numeric_values[0], f"{numeric_values[1]}a", f"{numeric_values[2]}-"
I'd personally make this more explicit rather than computed. Something like

```Python
@pytest.mark.parametrize("raw", "expected (
     (["-", 1, "1a", "2-"], [np.nan, 1, 1, 2]
     (["-", 10, "100a", "1000-"], [np.nan, 10, 100, 1000]
))
def test(self, raw, expected):
     assert np.allclose(raw, expected)
```

I think that way it's much clearer what the intended functionality is.

2021-07-20 14:27 UTC, timtroendle commented on scripts/jrc-idees/industry.py
> +    # All data between section/subsection names correspond to the preceding section/subsection name
Aha! That comment really helped me in understanding this.

2021-07-20 14:27 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +    df['section'] = df.where(df.indent == 1).iloc[:, 0].ffill()
Maybe add that same comment from industry.py here?

2021-07-20 14:27 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +    if sheet_name == 'TrRoad_act':
This if clause is redundant as you are already modelling the relationship between sheet name and dataset in DATSET_PARAMS. Maybe add the function to DATSET_PARAMS as a function object? The disadvantage is that you have to define the functions first and only then you can define DATSET_PARAMS. So nvm, not too important.

```Python
def fun1:
    pass

def fun2:
    pass

DATSET_PARAMS = {
     "road-vehicles": {
          "function": fun1
     }
}
```

2021-07-20 14:27 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +    if sheet_name == 'TrRoad_act':
But maybe DATSET_PARAMS = DATASET_PARAMS

2021-07-20 15:54 UTC, brynpickering commented
Need to fix some bugs found on running the script before it's ready.

2021-07-22 12:12 UTC, merged