Update unit conversion func; add tests
calliope-project/euro-calliope pull request #170
Opened 2021-08-06 13:43 UTC by brynpickering

In adding new features, I've come across the need to convert between units of energy on multiple occasions. Before the 'from' and 'to' units had to be explicitly defined, as well as the 'unit' index level added/updated manually. This rolls it all into a tested function.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-08-06 16:00 UTC, timtroendle requested changes
Generally fine. But I am not a big fan of the unit inference -- see my comments. I would only keep it if absolutely necessary.

I think you need to work on the tests. It was difficult for me to make sense out of them. I see the rationale behind your test design: they are brief, smart, and there are LOADS of them.

But they are also very implicit and that makes them difficult to understand. There should be at least a few tests with explicit input and output -- those are usually the easiest to understand the purpose of a function.

You also don't need so many tests. For example, many tests are testing each unit conversion in UNIT_CONVERSION_MAPPING. That's not necessary. Test them once, and then you know they work, right? I mean if you have tested KTOE -> KWH once, there is no reason to believe it doesn't work in another test.

2021-08-06 16:00 UTC, timtroendle commented on tests/lib/test_utils.py
> +        def _create_idx(multi_or_single):
Looking at your tests, you don't need the complicated factory pattern here. Do this instead:

```Python
@pytest.fixture(parameters=["single", "multi"])
def idx(self, request):
    multi_or_single = request.param
    if multi_or_single == "multi":
        return pd.MultiIndex.from_tuples([("foo", "bar")], names=["baz", "foobar"])
    elif multi_or_single == "single":
        return pd.Index(["foo"], name="baz")
```

All tests asking for `idx` will be run twice automatically. Syntax in my example is likely not 100% correct.

2021-08-06 16:00 UTC, timtroendle commented on tests/lib/test_utils.py
> +    def get_conversions():
This is cheating! You are testing the implementation by comparing it to an important part of the implementation. You are still testing something, but certainly not everything and especially not the important bit: the numbers! I think there should be explicit numbers in this test.

2021-08-06 16:00 UTC, timtroendle commented on tests/lib/test_utils.py
> +    def get_conversions():
In addition, your tests will be much easier to understand. Currently there are all these variables `convert_from` and `convert_to` which are difficult to graps. Another reason why they should be explicit.

2021-08-06 16:00 UTC, timtroendle commented on lib/eurocalliopelib/utils.py
> +        If `unit_in_output_idx` is False, there will be no index level `unit` in `df`.
But it will exist if it existed before?

2021-08-06 16:00 UTC, timtroendle commented on lib/eurocalliopelib/utils.py
> +    input_unit : str, optional, default None
Is this unit inference on a row by row basis? Otherwise I would not do unit inference -- it's just too brittle and complicated for its usefulness.

2021-08-06 16:00 UTC, timtroendle commented on lib/eurocalliopelib/utils.py
> +            assert len(units) == 1, f"Cannot infer unit for data with multiple available units {units}"
Ok so this answers my question from above. Do you think this unit inference is really worth its potential problems?

2021-08-06 16:00 UTC, timtroendle commented on lib/eurocalliopelib/utils.py
> -def ktoe_to_twh(array):
I actually think this was a very clear function. 🙈 I guess you have good reasons to make this more complex.

Here's a compromise solution to consider:

First, I wouldn't do unit inference. It's just so much more brittle and implicit and its added value is close to zero, isn't it? That's why I'd consider getting rid of unit inference. If you do, you could also consider to keep these functions as convenience functions like so:

```Python
def convert_unit(df, output_unit, input_unit, unit_in_output_idx=True):
   # as before but input_unit is mandatory
   return

def gwh_to_tj(df, **kwargs):
     return convert_unit(df, output_unit="twh", input_unit="ktoe", **kwargs)

def ...
```

2021-08-06 16:03 UTC, brynpickering commented on lib/eurocalliopelib/utils.py
> +        If `unit_in_output_idx` is False, there will be no index level `unit` in `df`.
No, not sure the best way to name this to cover both. `keep_unit_index_level`?

2021-08-06 16:04 UTC, brynpickering commented on lib/eurocalliopelib/utils.py
> +            assert len(units) == 1, f"Cannot infer unit for data with multiple available units {units}"
I think yes, if (as I have been doing) there is almost always an index level 'unit' in datasets. It's a lot *less* brittle than variable/column names being appended with the unit name...

2021-08-06 18:36 UTC, brynpickering commented
@timtroendle I can see the concern RE the inference. The reason I chose this approach was because I was finding so many instance of doing e.g. 

```
df = df.xs("TJ", level="unit").apply(tj_to_twh)
df = utils.add_idx_level(df, unit="twh")
```

This is good, as it means the data always has the unit information attached to it. However, I believe it's more error-prone and likely to go wrong with future iterations. 

I can see the issue of the current implementation though and have come to dislike my approach over the last few hours ;) 

I wonder whether an alternative would be to store all this data as xarrays with a "unit" attribute. This would then be a lot easier to track, less error-prone to infer, and just as easy to update data...

2021-08-09 06:40 UTC, timtroendle commented
Regarding adding a unit attribute to processed data: of course, that makes sense. We don't have a consistent way for that right now. 

Generally though, I would suggest to stick to the default unit for all processed data: MW / MWh. If all data are in the same unit, units should probably still be documented, but can in practise be ignored (or assumed) when working with the data.

2023-07-27 12:02 UTC, timtroendle commented
Closing this as it became stale and there is no conclusion.

2023-07-27 12:02 UTC, closed without merging