Feature config in doc
calliope-project/euro-calliope pull request #177
Opened 2021-08-11 15:37 UTC by timtroendle

Fixes #68.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-08-11 15:38 UTC, timtroendle commented
This is blocked by #171. Once merged, need to merge develop into this branch.

2021-08-11 15:39 UTC, timtroendle commented
The result is not pretty, but it's complete and the time invest was justified.

2021-08-11 17:49 UTC, brynpickering requested changes
Agreed that it is worthwhile to have, but this package might be more appropriate for a good result, and possibly less involved implementation? https://github.com/coveooss/json-schema-for-humans

You could output as html or as md. Running both locally on the schema works nicely. It comes down to our preferred aesthetics.

2021-08-11 17:49 UTC, brynpickering commented on config/schema.yaml
> +                        6. select most complete dataset for each country from list of data sources, based on a priority order
Currently renders with the numbering continuing through to the parameters in `load`...

2021-08-12 06:48 UTC, timtroendle commented
Ok, will look into `json-schema-for-humans`.

2021-08-12 07:15 UTC, timtroendle commented
Hm do you have a suggested configuration? I am creating a Markdown and I find the result pretty bloated -- I don't understand everything in that file and I wouldn't say it provides an easy overview. There is loads of stuff that's too bold and just unnecessary. It basically looks like their own documentation, which I find bloated and difficult to navigate, too:

https://github.com/coveooss/json-schema-for-humans/blob/master/docs/examples/examples_md_default/Configuration.md#deprecated_from_description

If we find a configuration generating a better result it could still be a good tool for its ease of use.

2021-08-17 16:01 UTC, brynpickering commented
@timtroendle I've looked into this a bit more and agree with you. Your current implementation seems the best of the options out there. I have fixed the 'data_quality' section locally so that it doesn't need special treatment. Let me know if I can push it to your branch. Two other issues that I see:

1. schema items using 'propertyNames' don't render ('shapes' and 'sea-connections'), which is an issue with the dependency not supporting it.
2. it would be good to include default values in here too. Would this be easy to add to each line in 'lines' after turning it to markdown...?

2021-08-17 16:09 UTC, timtroendle commented
1. Sure, push. I actually did not want to change `schema.yaml` more than necessary for this, but maybe that's only my neurosis calling here.
2. I can give it a try, but wouldn't spend much more time on this. So if there is no quick solution, I suggest to omit default values and instead point the reader to the `default.yaml` file for default values. (Thinking about it: it may be quicker to "fake" default values in the schema by adding them from `default.yaml` and then let the third-party library render it to Markdown. Default values are a feature of schemas, we are just not using it.)

2021-08-17 16:35 UTC, brynpickering commented
1. Don't worry the change is pretty minimal. 
2. OK, maybe update the schema preamble to link directly to the default YAML in this repo?

2021-08-17 16:36 UTC, brynpickering commented
btw, markdown link check fails on https://open-power-system-data.org which it shouldn't....

2021-08-17 16:41 UTC, brynpickering commented on lib/eurocalliopelib/docs/schema.py
>          #del lines[1]
delete this commented line before merging.

2021-08-18 14:27 UTC, timtroendle commented
Nice changes! The failing Markdown link check may simply be a hickup, let's see whether it fails again.

Re default values: I decided to go for the simple solution. While adding default values for simple parameters would be easy, it's complicated for more complicated ones like the arrays.

2021-08-18 14:51 UTC, brynpickering approved these changes
Looks good to me. The only issue is with `shapes` and `sea-connections` schema not rendering, but I think we can aim to deal with that at a later date via #180.

2021-08-18 15:02 UTC, merged