Update model to enable multi-year config
calliope-project/euro-calliope pull request #182
Opened 2021-08-20 12:41 UTC by brynpickering

Fixes #152. 

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-08-20 15:08 UTC, timtroendle requested changes
Nice! A few detail comments below.

Do you need this in 1.1? Otherwise I suggest to release this with 1.2 and allow us more time to test it thoroughly ourselves. If we bring it into 1.2 we can either keep this on hold or merge it into the long-lived feature branch.

2021-08-20 15:08 UTC, timtroendle commented on scripts/hydro/inflow_mwh.py
> +    for year in range(start_year, end_year + 1):
```Python
inflows = [
                      energy_inflow(
                          plants_with_inflow_m3.sel(time=str(year)), 
                          read_generation(path_to_generation, year), 
                          max_capacity_factor)
                      ) for year in range(start_year, end_year + 1)
]
```

2021-08-20 15:08 UTC, timtroendle commented on tests/model/test_model.py
> +    "multi-year": DEFAULT_TECHNOLOGIES,
This doesn't scale. Disclaimer: I am the original author.

2021-08-20 15:08 UTC, timtroendle commented on tests/resources/national/model.yaml
> +    multi-year: ["two-years"]
The same scenario should exist for continental and regional resolutions.

2021-08-20 15:13 UTC, timtroendle commented
Oh and: what about CHANGELOG and documentation?

2022-01-20 07:33 UTC, timtroendle requested changes
Thanks for updating this. Seemed to be quite some effort.

There are a few tiny things to fix -- in particular, I'd expect the default workflow execution to fail.

2022-01-20 07:33 UTC, timtroendle commented on rules/hydro.smk
> +        protected("data/automatic/europe-cutout.nc")
Would be better to include years like this: `"data/automatic/europe-cutout-{first-year}-{final-year}.nc"`

2022-01-20 07:33 UTC, timtroendle commented on config/minimal.yaml
> +        final-year: 2016
Is it a good idea to run this for two years? Will this make the execution much longer?

2022-01-20 07:33 UTC, timtroendle commented on tests/resources/continental/model.yaml
> +        model.subset_time: ['2015-12-31', '2016-01-01']
Wait, this must fail in the normal workflow, because the `default` config includes one year only. Here and in the two other models.

2022-01-20 10:48 UTC, brynpickering commented on rules/hydro.smk
> +        protected("data/automatic/europe-cutout.nc")
Yes, I had been thinking this too. The issue would be that you don't want to have to re-download this data if you rerun with a set of different years that overlaps with a previous run (e.g. you previously ran with 2010-2015 and now you want to run with just 2014-2016), or is a subset of a previous run (e.g. 2011-2012). Perhaps a cutout per year would suffice, running this rule with the year as a wildcard. Then the relevant years can be merged in 'inflow_m3'?

2022-01-20 10:50 UTC, brynpickering commented on config/minimal.yaml
> +        final-year: 2016
I wouldn't say *much* longer. The optimisation part of the workflow run just goes from december 31st 2015 to january 1st 2016. So, it crosses the two years, but only runs for two days.

2022-01-20 10:53 UTC, brynpickering commented on tests/resources/continental/model.yaml
> +        model.subset_time: ['2015-12-31', '2016-01-01']
Yes, I didn't think of the need to have these tests working for both the minimal and default runs (I was considering only the minimal workflow). Since the default workflow tests are only run for each release, it seems reasonable to have it run over more than one year. Is there anything wrong with the pre-built model having more than one year of data, other than size?

2022-01-20 13:31 UTC, timtroendle commented on rules/hydro.smk
> +        protected("data/automatic/europe-cutout.nc")
I personally would not bother with caring for the case of redownloads. I don't see this as an important use-case. A usual use-case may be to use a subset, but that's something you'd do in the Calliope model rather than in the workflow.

2022-01-20 13:34 UTC, timtroendle commented on tests/resources/continental/model.yaml
> +        model.subset_time: ['2015-12-31', '2016-01-01']
Mainly size I'd say. And that it is slightly odd to have two years in a model that by default runs for one year. Don't you think that testing the two-year mechanism in the minimal workflow suffices?

2022-01-21 12:36 UTC, brynpickering commented
@timtroendle: Minimal workflow builds with the latest commit.

2022-01-21 14:58 UTC, timtroendle approved these changes
One last comment.

Regarding runtime of the minimal workflow, that included downloads, right? With data available, it should take a few minutes only.

2022-01-21 14:58 UTC, timtroendle commented on config/euler/cluster-config.yaml
> +download_runoff_data:
This is configured as a localrule which won't be send to a compute node. You mentioned that this is problematic because of the memory footprint.

How did you manage to run this on a compute node? Shouldn't you remote the localrule statement? And, if that's necessary, can you document what to do to be able to reach the internet from a compute node?

2022-01-21 15:56 UTC, brynpickering commented on config/euler/cluster-config.yaml
> +download_runoff_data:
It's no longer a localrule. I don't know if I do anything special to make it work on a compute node. I have no special environment modules loaded....

2022-01-21 15:58 UTC, brynpickering commented
RE runtime, it still takes a while even without downloads. Does it really only take a few minutes for the minimal workflow currently, following `snakemake --cores 1 clean`?

2022-01-21 16:14 UTC, timtroendle commented
Are you running locally or on Euler? I gave it a try locally just now and it ran slightly longer than 9 minutes, using 3 cores and running from develop.

2022-01-24 09:40 UTC, brynpickering commented
Locally, it takes 14 minutes with 3 cores on this branch. It takes longer on the cluster, probably due to the time penalty of sending things off to job nodes. Is that permissible?

2022-01-24 11:05 UTC, timtroendle commented
I'd say it's not great as 14 minutes is quite long for a test that is supposed to run often. But I guess there is not much we can do.

2022-01-24 12:56 UTC, brynpickering commented
Does this mean we need an intermediate testing level, which happens just before PR merging or release? In most cases, running over multiple years shouldn't be broken by features/fixes - it's just looping over the same functions, after all.

2022-01-24 13:16 UTC, timtroendle commented
I think I wouldn't bother at this point -- also to not make the testing infrastructure too complex (it is already rather complex I think). But we need to keep this in mind, as the runtime of the minimal workflow will only become longer with more features.

2022-01-25 09:16 UTC, merged