Update dataset download to prepare for release
calliope-project/euro-calliope pull request #191
Opened 2021-08-31 16:27 UTC by timtroendle

This prepares for the release of 1.1. Before we can release euro-calliope 1.1, we need to release euro-calliope-datasets 1.1. For consistency, we should release on Zenodo. Zenodo does not support folders of files, unfortunately. The only way to retain folders is to upload everything as a zip-archive. So far, the download in euro-calliope expected to be able to download single files. This will not be possible anymore. Therefore, here's a change to prepare for that.

I know that the new `data.smk` is slightly arbitrary. I needed a new file though (so that the download rules are defined before other rules try to access these rules) and I wanted to introduce a minimal change. We really need to rethink the Snakefile structure, but I did not want to do this in this change -- just before release.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-08-31 16:37 UTC, timtroendle commented
Apart from its necessity to be able to move forward, I think this change makes sense. It's consistent with the way we download other data from Zenodo and it removes the pseudo-flexibility we gave with exposing single datasets as config params.

2021-09-02 08:19 UTC, brynpickering requested changes
I'm OK with the idea of moving to better matching the reliance on zipped zenodo repositories. However, could you first release `euro-calliope-datasets` v1.1 on zenodo and then update this PR in line with that? Mainly, I assume this will remove the need to worry about the unknown name in the top-level of the zip so we can skip the `tar` step (or the use of `dirname` in my proposed change). 

I would also go with explicit reference to the filepath in the rules requesting euro-calliope-dataset data. One reason is given in one of my comments, two others are: 1. you shouldn't need a separate Snakefile and 2. the reference to biofuel feedstocks will be moved to the biofuel rule, making the link to this hardcoded list more explicit.

2021-09-02 13:28 UTC, timtroendle commented on rules/data.smk
> +        # This script removes the top-level directory, whose name we do not know.
Correct, but we need a solution that works on both.

2021-12-09 16:22 UTC, timtroendle commented
Closing this PR in favour of another solution: The idea is to publish all datasets on Zenodo only. This reduces complexity and increases flexibility: we can simply point to Zenodo -- indcluding different versions for different datasets if need be.

2021-12-09 16:22 UTC, closed without merging