Update ts weighting to handle NaN values
calliope-project/euro-calliope pull request #192
Opened 2021-10-21 17:18 UTC by brynpickering

Just stumbled on this issue when running the workflow: Italy had an offshore wind capacityfactor of zero. This was caused by a single gridcell in the CF timeseries having only NaN values. 

This commit drops those gridcells with possible non-zero/NaN weight but NaN values. It then scales weights to 1, since there is one gridcell with a non-zero weight that has been removed. 

On testing, the weight of the removed gridcell in offshore wind was ~1e-8, so the weight correction wasn't really necessary...

Another option to fix this would be to "skipna" in the summation over all gridcells. The current implementation doesn't skip them.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [x] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [x] Tests added to cover contribution
- [x] Documentation updated
- [x] Configuration schema updated

2021-12-22 16:14 UTC, timtroendle requested changes
Nice catch! This solves the regression I found in #202.

Can you add a changelog entry?

2021-12-22 16:14 UTC, timtroendle commented on lib/eurocalliopelib/geo/spatiotemporal.py
> +        print(
Instead of a print message, would it make sense to assert a configurable threshold (must be very high, like 0.99 or so) is not exceeded? These printed messages can get overlooked too easily.

2021-12-22 16:15 UTC, timtroendle commented on lib/eurocalliopelib/geo/spatiotemporal.py
> +        print(
I think this could be even as high as 0.999 (99.9%).

2021-12-22 16:22 UTC, brynpickering commented on lib/eurocalliopelib/geo/spatiotemporal.py
> +        print(
Yeah, that would be fine by me. Maybe 0.995?

2021-12-22 16:23 UTC, timtroendle commented on lib/eurocalliopelib/geo/spatiotemporal.py
> +        .dropna(subset=["weight", "value"], dim="xy") # drop all locations with weight == 0 or value == np.nan
Maybe add `how="any"` to the function call? This happens implicitly, but it seems important enough to make it explicit here.

2021-12-23 07:08 UTC, timtroendle requested changes
Looks almost good! I'll try to come up with a test myself.

2021-12-23 07:08 UTC, timtroendle commented on lib/eurocalliopelib/geo/spatiotemporal.py
> +        .dropna(subset=["weight", "value"], dim="xy", how="all")
This must be "any", otherwise it doesn't work.

2021-12-23 07:08 UTC, timtroendle commented on tests/lib/test_spatiotemporal.py
> +DEFAULT_THRESHOLD = 0.999
There should be a test. The "bug" above wasn't captured by this.

2021-12-23 07:23 UTC, timtroendle approved these changes

2021-12-23 07:32 UTC, timtroendle commented
A changelog entry is not necessary as this is a regression introduced after the last release. I ran the minimal workflow with all tests and it works beautifully. Therefore, I am going to merge this PR.

2021-12-23 07:33 UTC, merged