Add automatic download of bioenergy potentials and cost
calliope-project/euro-calliope pull request #196
Opened 2021-12-08 17:57 UTC by timtroendle

* Add automatic download, Fixes #194.
* Update default scenario years to align them, Fixes #195.
* Fix cost of municipal solid waste, Fixes #193.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2021-12-21 12:14 UTC, brynpickering requested changes
Looks fine. Some comments to address and perhaps some new issues to create:

1. PROXIES -> config
2. retain regional distribution of costs
3. verify that your PROXIES for subnational regionalisation are similar to the NUTS2 data given in the Excel

2021-12-21 12:14 UTC, brynpickering commented on scripts/biofuels.py
>  def allocate_potentials(national_potentials, units, population, land_cover):
I suspect all of this would be best done in pandas, rather than xarray:

```
shares = pd.concat([population, land_cover[FOREST].sum(axis=1), land_cover[FARM].sum(axis=1)], axis=1, keys=['population_share', 'forest_share', "farm_share"]).groupby(units.country_code).transform(lambda x: x / x.sum())
regional_potentials = pd.merge(national_potentials.reset_index(), units["country_code"].reset_index(), on="country_code").set_index(["id", "feedstock"]).unstack("feedstock")
regional_potentials_sum = regional_potentials.groupby(PROXIES, axis=1).sum()
regional_potentials_weighted = regional_potentials_sum.mul(shares).sum(axis=1)
```

2021-12-21 12:14 UTC, brynpickering commented on scripts/biofuels.py
> +    weighted_cost = (
If we have costs per region, why not keep them as regional values? They'll be the same for every subnational region, but will be different between countries.

2021-12-21 16:28 UTC, timtroendle commented on scripts/biofuels.py
>  PROXIES = {
Yes!

2021-12-21 16:39 UTC, timtroendle commented on scripts/biofuels.py
> +    national_costs = (
Hm, most tech costs are given in Eur2013, so I'd assume both are equally good.

2021-12-21 16:40 UTC, timtroendle commented on scripts/biofuels/extract_biofuels.py
> +    df.value = pd.to_numeric(df.value, errors='coerce')
Ok but is there a specific reason?

2021-12-21 16:46 UTC, timtroendle commented on scripts/biofuels.py
> +    weighted_cost = (
Thought about the same when implementing. OK, but in a separate issue #200.

2021-12-21 17:33 UTC, timtroendle commented on scripts/biofuels/extract_biofuels.py
> +    # Sets 1 missing value (NOR, high cost 2030) to 0.
ok. I am using another scenario's value as values barely change between scenarios (and are tiny anyways)

2021-12-21 17:34 UTC, timtroendle commented on scripts/biofuels/extract_biofuels.py
> +    # Sets 1 missing value (BIH med potential 2010) to 0.
ok. But both are 0.

2021-12-21 17:50 UTC, timtroendle commented on scripts/biofuels.py
>  def allocate_potentials(national_potentials, units, population, land_cover):
Maybe. I gave this a try, but it didn't work right away. A pure Pandas approach would require more changes, as the inputs are xarray objects.

2021-12-21 18:06 UTC, timtroendle commented
Ok. I implemented most of your recommendations and I moved PROXIES (and actually much more) to the config. The other two points should be handled in other issues in my opinion (I opened #200).

2021-12-21 19:21 UTC, brynpickering requested changes
OK, I made suggestions to have everything remain in pandas the whole way through (rather than the current approach of pandas -> xarray -> pandas). I think it's cleaner and also quicker.

It's my first attempt at using 'suggestions' and I think it ultimately made it more confusing than I had hoped. Sorry. Let me know if you'd prefer that I just push a commit with the necessary updates.

On another note. Should `biofuels.py` be in the biofuels subdir?

2021-12-21 19:21 UTC, brynpickering commented on scripts/biofuels.py
> +    )
```suggestion
    shares = (
        pd.concat(
            [population, land_cover[FOREST].sum(axis=1), land_cover[FARM].sum(axis=1)], 
            axis=1, 
            keys=['population', 'forest', "farmland"]
        )
        .groupby(units.country_code)
        .transform(lambda x: x / x.sum())
    )
```

2021-12-21 19:21 UTC, brynpickering commented on scripts/biofuels.py
> +    return ds.value.sum("feedstock").rename(NAME).to_series()
```suggestion
    regional_potentials_sum = regional_potentials.groupby(proxies, axis=1).sum()
    regional_potentials_weighted = regional_potentials_sum.mul(shares).sum(axis=1)
    return regional_potentials_weighted.rename(NAME)
```

2021-12-21 19:21 UTC, brynpickering commented on scripts/biofuels.py
>      )
```suggestion
    weighted_cost = (
          national_costs
          .mul(national_potentials)
          .div(national_potentials.sum())
          .sum()
    )
```

2021-12-21 19:21 UTC, brynpickering commented on scripts/biofuels.py
> +        national_potentials = national_potentials.sum("country_code").expand_dims({"country_code": ["EUR"]})
```suggestion
        national_potentials = (
            national_potentials
            .rename(lambda x: "EUR", level="country_code")
            .sum(level=["country_code", "feedstock"])
        )
```

2021-12-21 19:21 UTC, brynpickering commented on scripts/biofuels.py
>      )
and move this above `if (len(units.index) == 1) and (units.index[0] == "EUR"):`

2021-12-21 19:21 UTC, brynpickering commented on scripts/biofuels.py
> +        )
```suggestion
```

In preference of bringing 'weighted_costs' up from below, which is a duplication of this if undertaken before changing 'national_potentials'.

2021-12-22 08:20 UTC, timtroendle commented
It's indeed a little complicated. Plus, you couldn't know whether it worked (it didn't), you had no code autocorrect, and you appear as commiter only, not as author. So my conclusion would be: worth the try, but not a terribly good solution. :P

Thanks in any case. This is cleaner now. Will merge once you give your ok.

2021-12-22 08:28 UTC, brynpickering commented
Haha, ok, I won't try making such lengthy suggestions again ;)

> On another note. Should biofuels.py be in the biofuels subdir?

Did you consider this?

2021-12-22 08:45 UTC, timtroendle commented
Yes, I did. Sorry, I was running the minimal workflow first before pushing. Now it's updated.

2021-12-22 08:50 UTC, brynpickering approved these changes

2021-12-22 08:51 UTC, merged