Update script and final model file structure
calliope-project/euro-calliope pull request #212
Opened 2022-01-25 22:54 UTC by brynpickering

Fixes #146.

Large restructure of final model files following discussions with various euro-calliope users and developers. 

The idea is to make things a bit more intuitive for a non-workflow user, while making the addition of model components easier and more modular for workflow users and developers.

This is necessarily the perfect final structure or naming convention, so I would welcome comments on how to improve!

Some other things changed in the process of this restructure:

1. ENTSOE TYNDP transmission links changed to an override (should 'nearest neighbour' links also be an override?)
2. model.yaml file import lists are created automatically from the template file structure
3. a 'scenarios.yaml' file consolidates overrides that have been split between files in the new structure, but were one override previously. This leaves open the option to add all overrides here, as discussed in #209.
4. a dedicated tech cost file (introduced in #132 ?) has been changed back to costs being defined with the rest of the tech definition.
5. 'load-shedding' and 'direction-rooftop-pv' are no longer independent rules. The 'direction-rooftop-pv' override is rolled into the 'wind-and-solar' template.
6. parametrising a template with Jinja2 has moved to eurocalliopelib.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2022-02-02 09:27 UTC, brynpickering commented on Snakefile
> +    output: "build/models/{resolution}/timeseries/demand/electricity-demand.csv"
Could rename this to `demand-electricity.csv` here, or leave for a follow-up PR. If follow-up, I would also update `capacityfactors...` filenames to more closely match the YAML filename counterparts.

2022-02-02 09:28 UTC, brynpickering commented on Snakefile
> +        example_model = "build/models/{resolution}/example-model.yaml",
Removed test-specific model YAMLs as they were repeating most of what was already in the example model YAML. Now, test+resolution-specfic config is defined in the workflow config and brought in here as parameters.

2022-02-02 09:29 UTC, brynpickering commented on config/schema.yaml
> +                        propertyNames: {"$ref": "#/properties/shapes/propertyNames"}
Can only take on a name matching a resolution defined in 'shapes' ('continental', etc.).

2022-02-02 09:31 UTC, brynpickering commented on rules/model-template.smk
> +MISSING_LOCATION_SPECIFIC_FILES = {
Not necessarily ideal implementation, but there didn't seem an easier way to handle this specific YAML file not being generated for non-national resolutions...

2022-02-02 09:31 UTC, brynpickering commented on rules/model-template.smk
> +NON_MODEL_CONFIG_FILES = ["environment.yaml", "README.md"]
could also read this from a `glob` of the `templates` top-level dir.

2022-02-02 09:32 UTC, brynpickering commented on rules/model-template.smk
> +        csv = "build/data/{resolution}/locations.csv"
Moved from `model` to `data`, since it isn't necessary for the model to run, and the `locations.yaml` file is now slim enough to communicate the same info.

2022-02-02 09:33 UTC, brynpickering commented on rules/model-template.smk
> +        template = "demand/demand-electricity.yaml|supply/supply-load-shedding.yaml|storage/storage-electricity.yaml"
could also avoid this wildcard constraint by setting a ruleorder so that this rule comes last. Then all remaining template files would be parametrised with this rule.

2022-02-02 09:35 UTC, brynpickering commented on rules/model-template.smk
> +        biofuel_cost = "build/data/regional/biofuel/{scenario}/costs-eur-per-mwh.csv".format(
If this was in the same file as 'potential-mwh-per-year.csv', then we wouldn't need the `template_bio.py` script. This fix relates to #200.

2022-02-02 09:36 UTC, brynpickering commented on rules/model-template.smk
> +        entsoe_tyndp = "build/data/national/TYNDP-2020-Scenario-Datafile.xlsx"
This has to be explicitly named (not only referencing the rule output) since the rule is in the main Snakefile. TODO in follow-up PR: move all rules from the main Snakefile into sector/tech-specific snakefiles in `rules`.

2022-02-02 09:39 UTC, brynpickering commented on rules/model-template.smk
> +def get_all_config_files(resolution):
[Snakemake best practices](https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html) would suggest that this help function should be in a separate file. Where? Or can this helper be completely avoided?

2022-02-02 09:39 UTC, brynpickering commented on rules/model-template.smk
> +        model_year = config["parameters"]["model-year"]
Since a user can now generate multiple weather years of data, it makes sense to enable them to define a 'default' year within those years.

2022-02-02 09:40 UTC, brynpickering commented on rules/wind-and-solar.smk
> +rule area_to_capacity_limits:
Replaces the sub-function found in the former `locations.py` script.

2022-02-02 09:41 UTC, brynpickering commented on scripts/template_locations.py
> +    locations = locations.assign(id=locations.index.str.replace(".", "-", regex=False)).set_index("id")
I wonder whether `.`->`-` should happen much sooner in the process...

2022-02-02 09:43 UTC, brynpickering commented on scripts/template_model.py
> +    config_files = sorted([
Possible not a good idea to use string replace here; might create errors. Does `pathlib.Path` have an equivalent string replacement that might be more robust?

2022-02-02 09:44 UTC, brynpickering commented on scripts/template_techs_and_locations.py
> +        **params
Just passes on all `params` that are defined in the rule.

2022-02-02 09:44 UTC, brynpickering commented on scripts/transmission/template_transmission.py
> +from eurocalliopelib.parametrise_template import parametrise_template
TODO: add tests for this.

2022-02-02 09:45 UTC, brynpickering commented on templates/model/example-model.yaml
> +    {% for file in config_files %}
list of files is now auto-generated.

2022-02-02 09:46 UTC, brynpickering commented on templates/model/scenarios.yaml
> +scenarios:
The only scenarios I've defined here so far are those which require stitching together newly split overrides back into scenarios with the same name as former 'overrides'.

2022-02-02 09:46 UTC, brynpickering commented on templates/model/techs/storage/storage-electricity.yaml
> +            storage_cap: {{ 723130 * 0.14 * scaling_factors.specific_costs }} # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MWh") }}, 802 $2015
I have moved costs back into where the technologies themselves are defined. This seems more intuitive.

2022-02-02 09:48 UTC, brynpickering commented on templates/model/techs/supply/supply-hydro.yaml
> +overrides:
Overrides are found alongside base tech definitions. This can make the YAML files very long and could ultimately 'hide' these overrides. Hence why I would create a scenario which encapsulates each override and place it in the top-level `scenarios.yaml` file.

2022-02-02 09:49 UTC, brynpickering commented on templates/model/techs/supply/supply-wind-and-solar.yaml
> +    directional-rooftop-pv:
Moved from its own file to an override in `supply-wind-and-solar.csv`, which fits with the approach taken with overrides elsewhere.

2022-02-02 09:50 UTC, brynpickering commented on templates/model/techs/supply/supply-wind-and-solar.yaml
> +tech_groups:
I could imagine this file being split into `wind` and `solar`. The only reason I can't easily do it right now is due to the shared `available_area` of onshore wind and open field PV, which is placed at the location level. Putting this bit in 'locations.yaml' would require that rule to include the wind and PV available area CSV as an input, which seems less clean.

2022-02-02 09:52 UTC, brynpickering commented on templates/model/techs/transmission/transmission-electricity-entsoe.yaml
> +# {{ ntc_limit.title() }} net transfer capacity between countries according to the
This could be in `transmission-electricity.yaml` as an override (it would match the implementation of overrides in other files), however, I don't know how to only stitch this in for the national resolution.

2022-02-02 09:54 UTC, brynpickering commented
@timtroendle this is now ready to review following the OK from others on the structure in #145. I have left comments here and there to provide some clarity and to open discussion where I think it would be useful. Hopefully these act to help (rather than hinder) you in the review process!

2022-02-07 16:28 UTC, timtroendle requested changes
This is great and looks like it will make both the workflow and the models cleaner. 

I left many comments inline and I have two main comments.

1. We should try to get rid of tech-specific template rules as they are making the workflow more complicated than need be (I think). Can’t we have a structure such that we need a `template/models/{class}/{tech}.yaml` and a `data/{class}/{tech}.csv` which will automatically build a `build/models/{class}/{tech}.yaml` ? Then, a workflow dev would only need to create the former two to build in a new tech. Only in special cases would one need to deviate from this. Wouldn’t that be simpler to grasp?
2. There is a lot of copy-paste going on in this PR. We need to heavily test the result of this PR to avoid regression. Maybe we can run a diff on a Calliope/netcdf/xarray object to avoid doing that by hand?

And finally: please try to bring in such a PR in smaller chunks next time. This is a huge PR and while it may seem slower to build it in chunks, I am convinced that eventually it is faster. It certainly will be less brain fuck.

2022-02-07 16:28 UTC, timtroendle commented on rules/model-template.smk
> +NON_MODEL_CONFIG_FILES = ["environment.yaml", "README.md"]
Then again, you have all sorts of hard coded file names in the rules below. As long as we cannot get rid of these, maybe simply inline NON_MODEL_CONFIG_FILES in the rule below? That would be consistent.

2022-02-07 16:28 UTC, timtroendle commented on rules/model-template.smk
> +NON_MODEL_CONFIG_FILES = ["environment.yaml", "README.md"]
Hello, it's me again. Now I understand: you need them at more than one location. What about this: These files can be differentiated by being top-level. So why don't you add a wildcard constraint to the specific rule forbidding a path separator. In the model rule, you could list them explicitly.

2022-02-07 16:28 UTC, timtroendle commented on rules/model-template.smk
> +        model_year = config["parameters"]["model-year"]
Not sure I agree. See my comment in the config.

2022-02-07 16:28 UTC, timtroendle commented on rules/model-template.smk
> +def get_all_config_files(resolution):
My personal opinion is to be explicit here. This is _the_ place where we stitch together the entire models. I think it's fine if we are explicit. It also solves some of the issues you mention above.

We could then consider moving this rule back to the main Snakfile, just because it's so important. There is another model rule over there but isn't one of them superfluous?

2022-02-07 16:28 UTC, timtroendle commented on rules/model-template.smk
> +MISSING_LOCATION_SPECIFIC_FILES = {
If you ditch the `get_config_files` function as I propose below and if you go back to the old being-explicit approach, you do not need this but you can reuse the approach we use in v1.1

2022-02-07 16:28 UTC, timtroendle commented on rules/model-template.smk
> +        template = "demand/demand-electricity.yaml|supply/supply-load-shedding.yaml|storage/storage-electricity.yaml"
I'd go for a ruleorder, especially if there are only a few exceptions (which I think we should aim for, see my main comment).

2022-02-07 16:42 UTC, brynpickering commented on rules/model-template.smk
> +        csv = "build/data/{resolution}/locations.csv"
OK, will move it back. It just seems an odd addition to the model files when it is the only file that isn't used to build the model. It might cause confusion with those using the pre-built model... 

Maybe there needs to be a 'name' option for locations. Something to add to the v0.7.0 to-do list...

2022-02-07 16:44 UTC, brynpickering commented on scripts/template_locations.py
> +    locations = locations.assign(id=locations.index.str.replace(".", "-", regex=False)).set_index("id")
hmm, yes and no. The official naming according to NUTS doesn't include `.`. This is purely a GADM naming convention.

2022-02-07 16:45 UTC, brynpickering commented on templates/model/scenarios.yaml
> +scenarios:
I was trying to keep this PR as small as possible ;) Maybe, given it's a monster already, I should add all overrides in here.

2022-02-07 16:46 UTC, brynpickering commented on templates/model/techs/supply/supply-hydro.yaml
> +overrides:
Except that overrides are sometimes so long that locations are hidden...

2022-02-07 16:48 UTC, brynpickering commented on templates/model/techs/supply/supply-wind-and-solar.yaml
> +    directional-rooftop-pv:
I'm generally against using a change of file imports as a way of setting up different versions of a model. It isn't Calliope best practice. This is why I would always import all files and use scenarios/overrides to shape the model setup.

Nevertheless, I agree with splitting the YAMLs.

2022-02-07 16:51 UTC, brynpickering commented on templates/model/techs/supply/supply-wind-and-solar.yaml
> +    directional-rooftop-pv:
For futureproofing, leaning more towards different file imports might actually be OK. We're intending on changing the file import structure in such a way that would make it more intuitive to change file imports with overrides.

2022-02-07 16:53 UTC, brynpickering commented on Snakefile
> +include: "./rules/model-template.smk"
Yes, agreed. I kept it in one place to make it easier to parse. Moving to technology domain-specific rule rules will mean expanding the file structure, which I was trying to keep to a minimum. Will update to tech 'domain'-specific rule files.

2022-02-07 16:54 UTC, brynpickering commented on docs/model/overview.md
> +└── README.md                                               <- Basic documentation (pre-builts only).
Did I add that sentence? I think it was there already...

2022-02-07 16:56 UTC, brynpickering commented
Thanks for the comments and sorry (not sorry) again for the monster. Splitting up would have taken a lot of redundant work to make each PR buildable, which I was unwilling to do...

2022-02-08 08:39 UTC, timtroendle commented on rules/model-template.smk
> +        csv = "build/data/{resolution}/locations.csv"
Does Calliope forbid to add unknown key value pairs? Otherwise, couldn't we simply add the name without it being a supported feature?

2022-02-14 16:45 UTC, brynpickering commented on rules/model-template.smk
> +        csv = "build/data/{resolution}/locations.csv"
Yes, but we'd get a stream of warnings telling us of an unknown key on loading the model. Best to leave it as this CSV for now.

2022-02-14 17:37 UTC, brynpickering commented on lib/eurocalliopelib/parametrise_template.py
> +        lstrip_blocks=True, trim_blocks=True, keep_trailing_newline=True,
Yep, let's introduce Black, but in a separate PR.

2022-02-14 17:50 UTC, brynpickering commented on scripts/transmission/template_transmission.py
>  """Link all those locations that are neighbours."""
I've implemented a shared template. However, it then relies on if statements. I don't think this is inherently bad, but raises the question of how maintainable it will be if/when other transmission setups are added.

2022-02-15 11:36 UTC, brynpickering commented
So the only thing that is still causing me issues to solve is your first point in your main comment, @timtroendle.

To do this there would need to be a single CSV file providing location-specific information for each resulting YAML file which relies on location-specific information. The current setup of having all solar and wind capacity limits in one CSV wouldn't work any more. Likewise for hydro supply/storage. Would you suggest doing that (i.e. splitting the CSV-generation rules to output tech-specific content)?

2022-02-15 11:46 UTC, brynpickering commented
@FLomb and @sjpfenninger if you have an opinion on point (3) of my comment above, feel free to chip in. This is about the structure within each of the final model YAML files.

2022-02-15 12:25 UTC, FLomb commented
> @FLomb and @sjpfenninger if you have an opinion on point (3) of my comment above, feel free to chip in. This is about the structure within each of the final model YAML files.

I am a bit confused though. At some point it looked like both you and Tim agreed on having overrides in a separate YAML file, which should solve the problem of whether locations or overrides come first in a file, shouldn't it? So, are we now talking of just a few, particular remaining overrides? like directional-rooftop and freeze-hydro-capacities? or am I missing something?

2022-02-15 12:28 UTC, brynpickering commented
The agreement was to have a separate `scenarios.yaml` file which effectively lists all available overrides by name. It wouldn't include the configuration component of the overrides, only their names.

2022-02-15 13:34 UTC, FLomb commented
> The agreement was to have a separate `scenarios.yaml` file which effectively lists all available overrides by name. It wouldn't include the configuration component of the overrides, only their names.

Ok, got it. Then I agree that there probably is no "good" order. If overrides where always short ones, I would agree that they should be on top, otherwise they'd be obscured. But, as you say, sometimes overrides are even longer than locations themselves. 

However, if we do have to choose, perhaps the less error-prone option might be indeed to have overrides on top. In fact, provided that we can make clear that no file is supposed to contain only overrides, people shall always expect something to _follow_ them. And so they shall always check what's at the bottom. While, if we chose to have overrides at the bottom, I guess one could still legitmately expect a file to contain only techs/locs with no overrides at the bottom, because we don't always need them; and sometimes they might just forget to check.

Does this make sense?

2022-02-15 14:40 UTC, brynpickering commented
Sounds very sensible, thanks @FLomb!

2022-04-25 10:05 UTC, brynpickering commented
@timtroendle: this PR is now effectively ready. However, since it is a large change, I'm rerunning `all_tests` on the cluster right now and will check the pre-built model contents with that of v1.1 to see if there are any discrepancies.

2022-04-28 08:28 UTC, brynpickering commented
@timtroendle I have now completed the full set of model tests, as would be required for a version release. I've checked the models against the version 1.1 prebuilds and found no unexpected differences in the default runs (+ in the regional model run with all overrides at once). Those differences that do exist are:

1. No transmission technologies in the example models by default. This is a feature change that aligns with discussions in #149, that we should be forcing the user to think about what transmission technologies they want to include in their model. Removing all techs by default ensures they don't blindly go ahead with the 'link all neighbours' example without realising.

2. PV and wind technologies have no `energy_cap_max: .inf` defined, since the inclusion of this is related to a now closed issue in the Calliope repo.

3. the "wind" and "pv" tech groups have been removed, since we can't accommodate tech groups between files.

4. Regional-level distributions of biofuel tech storage and energy capacities are different due to changes made in #199, i.e. since the release of v1.1. National/continental-level numbers don't change.

All relevant model subsets (e.g. "loc_techs", "loc_tech_carriers", etc.) are consistent between this PR and v1.1 pre-builds.

2022-05-06 10:06 UTC, timtroendle commented
@brynpickering Before I start looking at the implementation, a brief reaction to the four points you mentioned.

2--4: all fine.

1: I tend to disagree to that change. I would like to give new users the ability to run a model _without_ thinking about the model. This change will increase the entry barrier which already is quite high. The model is called `example_model` for a reason: it is just that. I am also happy to make that point clearer.

If we keep this change, we need to document this properly (it isn't right now) and guide new users on what to do exactly.

2022-05-07 11:51 UTC, timtroendle reviewed
It’s not possible for me to judge whether these changes are fine. Certainly not in the time you would need. 

As we are far away from the next release and as you said these changes won’t introduce any model changes, I am fine with you merging this in using your administrator super powers.

2022-05-07 11:51 UTC, timtroendle commented on Snakefile
> +ruleorder: area_to_capacity_limits > hydro_capacities > biofuels > dummy_tech_locations_template
This is unfortunate. Is there no way to avoid?

2022-05-07 11:51 UTC, timtroendle commented on Snakefile
> +rule dummy_tech_locations_template:
What is this for? Can you add an explanation?

2022-05-07 11:51 UTC, timtroendle commented on Snakefile
> +ruleorder: area_to_capacity_limits > hydro_capacities > biofuels > dummy_tech_locations_template
Maybe using wildcard constraints?

2022-05-07 11:51 UTC, timtroendle commented on Snakefile
> +        script = script_dir + "template_techs.py",
Is the indentation correct here? Could by my device.

2022-05-07 11:51 UTC, timtroendle commented on Snakefile
> +            technology=ALL_CF_TIMESERIES
Call this ALL_CF_TECHNOLOGIES

2022-05-07 11:51 UTC, timtroendle commented on Snakefile
> +            energy_carrier=ALL_DEMAND_TIMESERIES
ALL-DEMAND-CARRIERS

2022-05-07 11:51 UTC, timtroendle commented on config/default.yaml
> +test:
I would not put test config into this file.it will be necessary fer all projects downstream which is not appropriate.

2022-05-07 11:51 UTC, timtroendle commented on docs/model/overview.md
> +│   ├── example-model.yaml                                  <- Calliope model definition.
This is an excellent place to emphasize this is an example only.

2022-05-07 11:51 UTC, timtroendle commented on templates/models/example-model.yaml
> +    {% for file in input_files %}
👍

2022-05-10 17:21 UTC, brynpickering commented on Snakefile
> +ruleorder: area_to_capacity_limits > hydro_capacities > biofuels > dummy_tech_locations_template
There is no way of doing this that I can see. If using wildcards, they would apply to the *non*-location-specific technologies, which means adding them to 'dummy_tech_locations_template'. I would prefer to distinguish all those technologies that have location-specific data to use (hence this ruleorder), but could also apply it inside the main `techs_and_locations_template` rule inputs for `locations` as follows:
```
        locations = lambda wildcards: (
            f"build/data/{wildcards.resolution}/{wildcards.tech_group}/{wildcards.tech}.csv"
            if f"{wildcards.tech_group}/{wildcards.tech}" in TECHNOLOGIES_WITH_LOCATIONAL_OVERRIDES
            else rules.locations_template.output.csv
        )
 ```
which would require specifying the locational outputs explicitly in the snakefile: 

```
TECHNOLOGIES_WITH_LOCATIONAL_OVERRIDES = [
    "supply/hydro", "supply/open-field-solar-and-wind-onshore", "supply/rooftop-solar",
    "supply/wind-offshore", "storage/hydro", "supply/biofuel"
]
```

This would replace ruleorder and `dummy_tech_locations_template`. I don't really know which is better (read: more maintainable)

2022-05-10 17:21 UTC, brynpickering commented on Snakefile
> +        script = script_dir + "template_techs.py",
It is correct.

2022-05-10 17:34 UTC, brynpickering commented on config/default.yaml
> +test:
Hmm. How would you separate it? Would you put it in "tests/resources" and have it loaded in as a file from there?

2022-05-11 09:49 UTC, timtroendle commented on config/default.yaml
> +test:
I think that's better, yes. It could be either in `test/resources` or `config/test.yaml`. Not sure which is better.

2022-05-11 09:51 UTC, timtroendle commented on Snakefile
> +ruleorder: area_to_capacity_limits > hydro_capacities > biofuels > dummy_tech_locations_template
I agree that this does not look more maintainable. I guess it's fine the way it is -- we can still improve this later.

2022-05-11 13:22 UTC, brynpickering commented on config/default.yaml
> +test:
Moved it to resources and moved the schema section there too.

2022-05-12 08:17 UTC, merged