Feature update workflow infra
calliope-project/euro-calliope pull request #264
Opened 2023-05-23 17:10 UTC by timtroendle

Fixes #253

Fixes #255 

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2023-06-02 20:16 UTC, brynpickering requested changes
Nice!

I'm just running the minimal workflow locally, to double check it ;)

docs env file needs fixing, see my separate comment on that.

2023-06-05 07:50 UTC, timtroendle commented on envs/docs.yaml
> +        - -e ./lib[docs]
Nice catch. I moved it to the top level.

2023-06-05 13:04 UTC, timtroendle commented
I have no clue why the environment cannot be resolved on readthedocs. It works just fine on my machine.

It maybe a Linux problem, but I cannot test that right now as Euler is down for maintenance. Then again, the missing dependency `toposort>=1.10` is a `noarch` package, so it does not really make sense to me.

2023-06-06 07:54 UTC, brynpickering commented
You can always trust mamba to solve all your issues :)

2023-06-06 16:55 UTC, brynpickering approved these changes

2023-06-07 19:52 UTC, merged