DRAFT: Feature road transport
calliope-project/euro-calliope pull request #269
Opened 2023-09-27 10:17 UTC by SimonS898

Fixes # .

Implements road transport demand and road bau transport demand in euro-calliope develop, by making use of some functionality out of sector-coupled-euro-calliope and euro-calliope(branch: feature-sector-coupling).

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2023-11-06 09:28 UTC, timtroendle requested changes
Thanks @SimonS898 . I think this is a very good start. It still requires quite some refactoring --  I'd guess about one day of work. Let's talk offline.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/aggregate_timeseries.py
> +    for timeseries in timeseries_paths:
Looks are usually not a good idea in Python. Here the code you want to use likely looks something like this:
```
(
     pd
     .concat([pd.read_csv(path,...) for path in paths])
     .sum()
)
```

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/aggregate_timeseries.py
> +def aggregate_continental_timeseries(timeseries_paths, output_path):
Continental does what national does as well, just a bit more. So likely, you should call the national function first, and then do what else you need to do.

Likely, it should look like this:
```
df = (
     aggregate_national_timeseries(...)
     .sum()
     .rename("EUR")
)
```

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +CARRIERS = {
This is redundant and should be injected.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +EFFICIENCY_QUANTILE = 0.25
This should come from config.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +YEAR_RANGE = slice(2000, 2018)
Why this range? Why is it different than in the other file? Should be injected.

2023-11-06 09:28 UTC, timtroendle commented on config/default.yaml
> +fill-missing-values:
Also: indentation is wrong.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +    # assumption: agriculture oil use goes to 'road' transport demand;
Use `ASSUME`, not `assumption`.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +        .loc[idx['FC_OTH_NSP_E', ['O4651', 'O4653', 'O4661XR5230B', 'O4669'], :, :, :]]
Use constants for all these values.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +        .loc[idx[['FC_OTH_AF_E', 'FC_OTH_NSP_E'], 'O4000XBIO', :, :, :]]
Use constants for all these values.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +def get_transport_demand(
Use more functions so that this function has only ~10 lines. It'll be much easier to understand what's going on.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
Use typing for parameters and return values of all functions.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/aggregate_timeseries.py
Use typing for all parameters and return values of all functions.

2023-11-06 09:28 UTC, timtroendle commented on scripts/jrc-idees/transport.py
Use typing for all parameters and return values of all functions.

2023-11-06 09:28 UTC, timtroendle commented on scripts/transport/annual_transport_demand.py
> +    # 2016-2018 from 2015 data; non-JRC countries, based on neighbour data
Why 2016--2018?

2023-11-06 09:28 UTC, timtroendle commented on rules/ch-stats.smk
There are many, very small rule files that only download data: `ch-stats.smk`, `eurostat.smk`, and `jrc-idees.smk`. Instead, I suggest to create a `download.smk` that combines all these.

2023-12-15 10:24 UTC, SimonS898 commented on rules/ch-stats.smk
Good point! Moved all rules into a single smk file called download.smk as suggested. 👍

2023-12-15 10:36 UTC, SimonS898 commented on scripts/transport/aggregate_timeseries.py
👍

2023-12-15 11:02 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +    # assumption: agriculture oil use goes to 'road' transport demand;
👍

2023-12-15 11:09 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +EFFICIENCY_QUANTILE = 0.25
✅

2023-12-15 11:32 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +YEAR_RANGE = slice(2000, 2018)
I think this is the rage for which we have the Eurostat data available, which we use to estimate transport efficiency. This is also the reason why it doesn't correspond to the temporal scope defined in the config file. If I don't get things mixed up, I think we estimate all values from 2000 - 2018 and only later cut down to the values required as specified in the temporal scope. This does not make sense as we could already limit the calculated values in this file to the ones specified in the temporal scope, as we calculate our estimates by looking at the values of the neighboring countries for only that specific year.  Not sure if this reasoning is correct? 😄

2023-12-15 13:42 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
✅

2023-12-15 13:44 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +def get_transport_demand(
Good call! I restructured the file quite a bit to increase readability, by introducing new Constants as suggested and Functions. Let me know what you think! :)

2023-12-15 13:44 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +        .loc[idx[['FC_OTH_AF_E', 'FC_OTH_NSP_E'], 'O4000XBIO', :, :, :]]
✅

2023-12-15 13:44 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +        .loc[idx['FC_OTH_NSP_E', ['O4651', 'O4653', 'O4661XR5230B', 'O4669'], :, :, :]]
✅

2023-12-15 13:46 UTC, SimonS898 commented on scripts/transport/annual_transport_demand.py
> +CARRIERS = {
Was not quite sure what you meant here. I  could not find the corresponding carrier mappings in the config file.

2024-01-22 10:29 UTC, timtroendle commented
@SimonS898 please let me know if you need any input from my side.

2024-01-28 09:30 UTC, SimonS898 commented
> @SimonS898 please let me know if you need any input from my side.
Will do thanks! 👍  I think I will finish all the review and push it so you can look at everything at once. :)

2024-02-15 17:30 UTC, timtroendle commented
Hi @SimonS898, on 11 March we will run a sprint. This requires this branch to be merged until then. Could you please soon push whatever you have, so that I can take care of everything else and merge at 8 March latest?

2024-02-19 20:53 UTC, SimonS898 commented
> Hi @SimonS898, on 11 March we will run a sprint. This requires this branch to be merged until then. Could you please soon push whatever you have, so that I can take care of everything else and merge at 8 March latest?

Hi Tim, 

This is exciting to hear! I will make sure to push the changes I did so far tomorrow evening. Sadly I had issues renewing my gurobi license, as I‘m not currently enrolled at ETH (between bachelor and master). I contacted ETH to see if I could be enrolled during my gap year or are there other ways to get the gurobi license? I can work on it this friday and try to to get the rest of the changes done, if I get the license.

2024-02-20 07:12 UTC, timtroendle commented
Hm I guess you still have access to your ETH accounts, right? In that case you could run on the cluster, but that would take a while to set up properly. There is nothing else that comes to my mind, sorry.

Honestly, it's not crucial that you run the tests involving Gurobi. I can do that.

2024-02-20 21:00 UTC, SimonS898 commented
> Hm I guess you still have access to your ETH accounts, right? In that case you could run on the cluster, but that would take a while to set up properly. There is nothing else that comes to my mind, sorry.
> 
> Honestly, it's not crucial that you run the tests involving Gurobi. I can do that.

I contacted ETH and I am now enrolled in a Leave Semester, so I think I should be able to renew my Gurobi license. I will try on friday.

2024-02-29 14:29 UTC, timtroendle commented
@SimonS898 , any updates on this?

2024-03-02 13:25 UTC, SimonS898 commented
> @SimonS898 , any updates on this?

Sorry I wasn‘t able to renew the license and I‘m currently very busy/stressed at work so I didn‘t really get to it.. I‘m gonna try to get some work done today and tomorrow, but I won‘t be able to test it properly I think without the license..

2024-03-02 14:20 UTC, SimonS898 commented on scripts/jrc-idees/transport.py
> +    # The vehicle subtype is identified here and ffill() is used to match all relevant rows to this subtype.
You are right, the first part of the comment makes sense but the ffill() does not. I removed it. 👍

2024-03-02 14:31 UTC, SimonS898 commented on scripts/jrc-idees/transport.py
Good point, moved the file and renamed it to jrc_idees.py

2024-03-02 14:57 UTC, SimonS898 commented on scripts/eurostat/annual_energy_balance.py
> +        lambda x:
Renamed it to index. 👍

2024-03-02 15:13 UTC, SimonS898 commented on scripts/eurostat/annual_energy_balance.py
> +        for i in [
Good point, renamed it to df. 👍

2024-03-02 15:27 UTC, SimonS898 commented on scripts/eurostat/annual_energy_balance.py
> +        path_to_ch_excel, 'T17a', skipfooter=9, cat_code='FC_OTH_HH_E'
Created an Enum for category codes 👍

2024-03-02 15:45 UTC, SimonS898 commented on scripts/eurostat/annual_energy_balance.py
> +    tdf = tdf.unstack("year").loc[:, YEARS].bfill(axis=1).stack()
bfill is now only applied to ME and BA

2024-03-02 15:50 UTC, SimonS898 commented on scripts/eurostat/annual_energy_balance.py
> +        'cat_code', 'carrier_code', 'unit', 'country'
It is necessary because of to_numeric as I understand it. Not sure what you mean by removing this, can we do this?

2024-03-02 15:55 UTC, SimonS898 commented on rules/jrc-idees.smk
> +        sector = "((industry)|(transport)|(tertiary))"
Yes exactly, left it in as it potentially will get used later on.

2024-03-04 09:17 UTC, timtroendle commented
Hi @SimonS898 , I fully understand that you may not have the time right now and that's fine. I can take over. Please finish as soon as possible and let me know what still needs to be done. This needs to be merged by end of week.

2024-03-04 15:06 UTC, SimonS898 commented
> Hi @SimonS898 , I fully understand that you may not have the time right now and that's fine. I can take over. Please finish as soon as possible and let me know what still needs to be done. This needs to be merged by end of week.

Hi @timtroendle, I pushed all the changes I have already done and marked the regarding comments, with either a comment itself or a reaction. I can also resolve the conversations of the requests I addressed? 
Thanks so much for your understanding and sorry that I couldn't make all the changes.. work has been exhausting. I wish you the best of luck for your upcoming sprint and I am excited to see your progress! 🚀

2024-03-04 15:19 UTC, timtroendle commented
Fantastic, thanks. I will take care of the remainder.

2024-03-06 10:31 UTC, timtroendle commented on Snakefile
> +ruleorder: bio_techs_and_locations_template > techs_and_locations_template > jrc_idees_zipped
Removing this as it is unnecessary.

2024-03-06 10:34 UTC, timtroendle commented on config/default.yaml
> +    eurostat-energy-balance: https://raw.githubusercontent.com/calliope-project/euro-calliope-datasets/feature-sector-coupling/eurostat/nrg_bal_c.tsv.gz
added

2024-03-06 10:43 UTC, timtroendle commented on config/default.yaml
> +road_transport_conversion_factors: # conversion factors out of sector-coupled, from mio km to MW(h)
Added source and moved into parameters/transport

2024-03-06 12:28 UTC, timtroendle commented on config/default.yaml
> +fill-missing-values:
moved

2024-03-06 12:29 UTC, timtroendle commented on config/default.yaml
> +  "NO": ['SE', 'DK']
removed

2024-03-06 12:29 UTC, timtroendle commented on config/default.yaml
> +        future-vehicle-efficiency-percentile: 0.25
added

2024-03-06 12:29 UTC, timtroendle commented on config/minimal.yaml
> +fill-missing-values:
added

2024-03-06 12:33 UTC, timtroendle commented on docs/model/overview.md
No, they are not shown one by one.

2024-03-06 12:36 UTC, timtroendle commented on envs/default.yaml
> +    - netCDF4
done

2024-03-06 14:48 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +    path_to_input, path_to_cat_names, path_to_carrier_names, path_to_ch_excel,
done

2024-03-06 15:50 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +    tdf.to_csv(path_to_result)
done

2024-03-06 16:32 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +    df = df.transform(utils.to_numeric)
done

2024-03-06 16:32 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +        'cat_code', 'carrier_code', 'unit', 'country'
seems entirely unnecessary to me. removed.

2024-03-06 16:55 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +YEARS = range(2000, 2019)
I removed this in favour of a single parameter from the Snakemake rule.

2024-03-06 16:56 UTC, timtroendle commented on config/default.yaml
> +road_transport_conversion_factors: # conversion factors out of sector-coupled, from mio km to MW(h)
moved

2024-03-06 16:56 UTC, timtroendle commented on config/default.yaml
done

2024-03-06 16:57 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +    tdf = tdf.unstack("year").loc[:, YEARS].bfill(axis=1).stack()
There were many more nans that got filled here! For now, I am removing this statement.

2024-03-06 17:27 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +        .iloc[:, [i for i in range(10) if i != 1]]
done

2024-03-06 17:27 UTC, timtroendle commented on scripts/eurostat/annual_energy_balance.py
> +        .apply(utils.to_numeric)
not necessary. removed

2024-03-07 08:44 UTC, timtroendle commented on rules/jrc-idees.smk
> +        unprocessed_data = "build/data/jrc-idees/transport/unprocessed"
done

2024-03-07 08:44 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +    data_filepaths = list(Path(data_dir).glob("*.xlsx"))
fixed

2024-03-07 08:46 UTC, timtroendle commented on scripts/jrc-idees/transport.py
> +    processed_data.stack('year').to_csv(out_path)
fixed

2024-03-07 09:26 UTC, timtroendle commented on scripts/transport/road_transport_timeseries.py
> +    powered_2_wheelers_timeseries_out_path, light_duty_vehicles_bau_timeseries_out_path,
done

2024-03-07 09:56 UTC, timtroendle commented on scripts/transport/road_transport_timeseries.py
> +    for _, row in vehicle_df.iterrows():
done

2024-03-07 11:32 UTC, timtroendle commented on scripts/transport/aggregate_timeseries.py
> +    aggregate_timeseries(
done

2024-03-07 11:55 UTC, timtroendle commented on scripts/transport/aggregate_timeseries.py
> +    for timeseries in timeseries_paths:
done

2024-03-07 11:56 UTC, timtroendle commented on scripts/transport/aggregate_timeseries.py
> +def aggregate_continental_timeseries(timeseries_paths, output_path):
done

2024-03-07 15:00 UTC, timtroendle commented on rules/transport.smk
> +rule create_road_transport_timeseries:
done

2024-03-07 17:14 UTC, timtroendle commented on docs/model/customisation.md
> +        **no_bau_road_transport_demand_electrified**: DRAFT: Allows to remove electrified road BAU transport demand.
done

2024-03-07 19:08 UTC, timtroendle commented
The current version works in the minimal workflow (when commenting regional resolution which is not implemented). There are still several TODOs to handle and the checklist above.

2024-03-08 12:33 UTC, timtroendle approved these changes
After a second review (of partly my own changes) this looks now good to me. There are a few things missing or unclear and they are marked with TODOs and FIXMEs.

2024-03-08 12:36 UTC, merged

2024-03-08 12:38 UTC, timtroendle commented
Awesome, this is now merged. 😮‍💨 Thanks a lot for your work @SimonS898 !

2024-03-08 17:14 UTC, SimonS898 commented
> Awesome, this is now merged. 😮‍💨 Thanks a lot for your work @SimonS898 !

Very exciting 🎉🎉, thank you so much for letting me be part of the project! And best of luck for the upcoming sprint! <3