Update EEZ file ref to our own cache
calliope-project/euro-calliope pull request #332
Opened 2024-04-09 15:22 UTC by brynpickering

Fixes #328 

The issue is a newer version of EEZ is being downloaded, which we can't control for on the `https://geo.vliz.be/geoserver/MarineRegions/wfs` file server. Versioned releases _are_ available [here](https://www.marineregions.org/downloads.php), but require a user to tick a box and fill in some info about themselves. The data license allows us to just upload it elsewhere, which I've done by putting it on the [`euro-calliope-datasets` repo](https://github.com/calliope-project/euro-calliope-datasets/pull/5). Arguably not the best way to handle caching a working version of EEZ (in this case, EEZ V11) but it is possibly the quickest.

Tested on the full workflow and it works to produce offshore wind data. Change from the v1.1 pre-built CSV file (average of hourly new cf / hourly old cf per country):

```
AUT         NaN
BEL    1.000087
BGR    0.999992
HRV    0.999954
CYP    0.999995
CZE         NaN
DNK    0.999905
EST    0.999875
FIN    0.999110
FRA    1.000038
DEU    1.000079
GRC    0.999975
HUN         NaN
IRL    1.000002
ITA    0.999969
LVA    1.000151
LTU    0.999934
LUX         NaN
NLD    1.000147
POL    1.000209
PRT    1.000019
ROU    0.999999
SVK         NaN
SVN    0.998619
ESP    0.999996
SWE    0.999313
GBR    1.000024
ALB    1.000064
BIH    1.000000
MKD         NaN
MNE    0.999882
NOR    0.999733
SRB         NaN
CHE         NaN
```

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-04-10 09:18 UTC, brynpickering commented
I've updated to use zenodo. For now the data is in a [sandbox record](https://sandbox.zenodo.org/records/45135), with the plan to move it to [the main input record](https://zenodo.org/records/5797549) when we release v1.2.

2024-04-11 07:06 UTC, timtroendle requested changes
Looks good. Please add a FIXME because we will easily forget.

2024-04-11 07:06 UTC, timtroendle commented on CHANGELOG.md
> +* **FIX** source of Exclusive Economic Zones (EEZ) to use a cache on [zenodo](https://sandbox.zenodo.org/records/45135) so that we can keep using v11 (#332).
Best add a "FIXME update to actual data store before release of Euro-Calliope"

2024-04-11 07:06 UTC, timtroendle commented on config/default.yaml
> +    eez: https://sandbox.zenodo.org/records/45135/files/eez_v11.gpkg.zip?download=1
Add the FIXME here too.

2024-04-11 07:33 UTC, timtroendle commented
Btw do you know how often Sandbox is wiped?

2024-04-11 07:40 UTC, brynpickering commented
> Btw do you know how often Sandbox is wiped?

I don't. I couldn't find any info on it either. Oldest available record is Feb 3rd, so maybe ~2 months? Gives us a deadline...

2024-04-11 07:42 UTC, brynpickering commented
> In the sandbox environment, you can try out all functions of Zenodo and the submitted data will be deleted from time to time. 

https://www.uzh.ch/blog/hbz/2018/11/14/how-to-submit-in-zenodo/?lang=en

2024-04-11 07:44 UTC, brynpickering commented
Maybe we upload to zenodo as a unique record?

2024-04-11 09:09 UTC, timtroendle commented
As discussed, I'd be fine with using sandbox. We only need to release within 2 months and there won't be any problems, haha.

2024-04-11 10:12 UTC, merged