Feature ehighways resolution unts 318
calliope-project/euro-calliope pull request #336
Opened 2024-04-10 07:39 UTC by jonathan-peel

Fixes #318  .

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-04-12 13:39 UTC, jnnr commented
A a note: ehighways uses NUTS3 2006 (checked by comparing the region names in anderski_2014 with `statistal-to-ehighways-units.csv)

2024-04-13 15:38 UTC, timtroendle requested changes
Awesome! It looks good, but it requires a few changes, like type hints, documentation, and solving some inconsistencies.

The one thing I am not liking stems from the source: There are now two different ways in which resolutions are defined: the previously-existing `shape` config in the config AND the new `statistical-to-custom-units` file. Ideally, there would be only one place.

I don't think this should be handled within this PR or ticket. But I would like to keep this in mind and consider solving in the future. @brynpickering, do you agree?

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
Many functions in this file lack type hints.

2024-04-13 15:38 UTC, timtroendle commented on config/default.yaml
> +        # FYI: E-highways were initially defined using NUTS3 units from 2006, but this mapping was manually created to map NUTS units from any year up to 2016 to E-highways. This is picked up by rule
This comments seams out of context here. I don't know where this should go, but this looks like the wrong place to me.

2024-04-13 15:38 UTC, timtroendle commented on config/default.yaml
> +    # TODO: update this link to Bryn's new one, which includes the potentials for ehighways
Please update the link

2024-04-13 15:38 UTC, timtroendle commented on config/default.yaml
> +        Iceland: nuts0
Iceland is not currently supported by Euro-Calliope, see #15.

2024-04-13 15:38 UTC, timtroendle commented on config/schema.yaml
> +                    (i.e., NUTS and GADM) are combined to form units of a custom
GADM are not statistical units.

2024-04-13 15:38 UTC, timtroendle commented on config/schema.yaml
> +                    resolutions (e.g., ehighways). FYI: E-highways were initially
The FYI also seems ill-placed here, I am sorry to say.  This is a description of the configuration parameters, but your comment is a comment to the parameter _value_.

2024-04-13 15:38 UTC, timtroendle commented on config/schema.yaml
> +                description: Version of the Nomenclature of territorial units for statistics to use in creating spatial units (see https://ec.europa.eu/eurostat/web/nuts/history for more info)
Nomenclature of Territorial Units for Statistics

2024-04-13 15:38 UTC, timtroendle commented on config/schema.yaml
> +                                - "Iceland" # added for ehighways
Please remove. Adding Iceland requires other changes, too.

2024-04-13 15:38 UTC, timtroendle commented on config/schema.yaml
> +        # TODO: replace zenodo link with Bryn's new one, which includes the potentials for ehighways
Please update link

2024-04-13 15:38 UTC, timtroendle commented on rules/shapes.smk
> +rule units: # for original resolutions of regional, national, continental
The comment is incorrect, right? This is for all resolutions.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    path_to_statistical_to_custom_units,
Last four parameters and output of the function miss type hints.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +        resolution_config=snakemake.params.resolution_configs[resolution],
I understand this construct existed before, but it's suboptimal. Please hand over only the configuration of the right resolution to the rule, not the configs of all resolutions.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
>          f"Layer {layer_name} is not correctly " "defined."
There is a superfluous pair of quotes.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    - resolution_config: a mapping of which statistical unit resolution each country should use as its base
The units are not necessarily statistically. NUTS is, GADM isn't.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    - source_layers: a dict with keys as each statistical unit type (nuts[0-3] or gadmn[0-3])
Same here.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    - source_layers: a dict with keys as each statistical unit type (nuts[0-3] or gadmn[0-3])
GADM isn't statistical.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +        # this code is only executed if there is a [statistical-to-custom-units file corresponding to the chosen resolution] in the config
What are the brackets for?

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    """Combine the lower-level statistical units (aspecified in resolution_config)
Typo in comment.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    """Combine the lower-level statistical units (aspecified in resolution_config)
The units are not necessarily statistical.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    """Combine the lower-level statistical units (aspecified in resolution_config)
Is it useful to mention `resolution_config` here? It's not part of the function anyway.

2024-04-13 15:38 UTC, timtroendle commented on config/default.yaml
> +    statistical-to-custom-units:
As mentioned in some other comments, the base units are not necessarily statistical. They are for eHighways, but if you want to be more flexible than eHighways (which you don't have to be, but which you are), then this does not make sense. Why not: `base-to-custom-units`?

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    - path_to_statistical_to_custom_units: csv file that specifies which NUTS and GADM
Here again, there should be no `statistical` in the name if you want to be more flexible than eHighways.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    -
Output is missing.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    - the base-level statistical units in layer and are either NUTS3 or whole countries (NUTS0 or GADM0)
GADM is not... you know what. :D

2024-04-13 15:38 UTC, timtroendle commented on config/schema.yaml
> +            nuts-year:
This parameter does not exist in the config. Please remove.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    nuts_year = 2013  # This was a variable in Bryn's SC EC, but hardcoded to 2013 in EC. Consider that the year needs to match for both the (downloaded nuts units) and (nuts to custom region mapping
Make this a constant at the top of the file.

2024-04-13 15:38 UTC, timtroendle commented on scripts/shapes/units.py
> +    nuts_year = 2013  # This was a variable in Bryn's SC EC, but hardcoded to 2013 in EC. Consider that the year needs to match for both the (downloaded nuts units) and (nuts to custom region mapping
I'd remove the first sentence. Alternatively, point to the line in the repo. "Bryn's SC EC" will not make sense to everyone and forever.

2024-04-25 12:59 UTC, brynpickering commented
> I don't think this should be handled within this PR or ticket. But I would like to keep this in mind and consider solving in the future. @brynpickering, do you agree?

I don't think it's necessarily a problem. You have standardised boundaries coming from various data sources (nuts, gadm, ...) and they are your building blocks in `shapes`. Then you have a mechanism to merge those shapes together with a custom mapping. It means we know that all shapes in the model are built from standard boundaries and there's no need for a mechanism to injest custom shapes.

2024-05-02 12:09 UTC, brynpickering reviewed
Not sure what the issue is with setting a nuts year at the config level and then downloading that nuts year when generating any units (as I did in SC-EC). Since we only use NUTS for `ehighways` at the moment it effectively allows you to choose the NUTS year that will be used to create those shapes.

We'll need the ability at a later point to download arbitrary NUTS years (for subnationalising using Eurostat datasets) so I guess we can leave it until then to introduce it as a feature.

2024-05-14 07:52 UTC, merged