Feature uncontrolled vs controlled charging
calliope-project/euro-calliope pull request #338
Opened 2024-04-10 10:00 UTC by adrienmellot

This PR does not fix any issue but is a step towards fixing #274 , #273 , #81 .

This separates fully electrified road transport demand into a controlled part (for now, as an annual demand to be met without any constraints), and an uncontrolled part (as a fixed timeseries profile). This share is a parameter to be decided by in the config file.

To note:
- There is an inconsistency with the override "keep-historic-electricity-demand-from-road-transport" because we've assumed historical electrified transport to be uncontrolled. If you activate the override, you are still counting this electricity demand as uncontrolled.

Co-authored by: Francesco Sanvito [sanvitofrancesco@gmail.com](mailto:sanvitofrancesco@gmail.com)
 

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-04-10 10:47 UTC, brynpickering reviewed
A few comments to address

2024-04-10 10:47 UTC, brynpickering commented on Snakefile
> +    message: "Create empty {wildcards.resolution} location-specific data file for the {wildcards.tech_group} tech `{wildcards.tech}`."  # Not used only if ruleorder is updated at top of file
Maybe update to: `Update ruleorder at the top of the file if you instead want the techs_and_locations_template rule to be used to generate a file`

2024-04-10 10:47 UTC, brynpickering commented on config/default.yaml
> +        uncontrolled-charging-share: 0.5
```suggestion
        uncontrolled-ev-charging-share: 0.5
```

2024-04-10 10:47 UTC, brynpickering commented on rules/transport.smk
> +rule download_transport_timeseries: # TODO have correct timeseries data once RAMP has generated the new charging profile and it's been put on Zenodo
Add the TODO on the line below. Makes it easier to read

2024-04-10 10:47 UTC, brynpickering commented on rules/transport.smk
> +use rule create_uncontrolled_road_transport_timeseries as create_unctronolled_road_transport_timeseries_historic_electrification with:
spelling

2024-04-10 10:47 UTC, brynpickering commented on rules/transport.smk
> +            "build/data/transport/timeseries/timeseries-uncontrolled-light-duty-vehicles.csv",
Turn this into a for loop that uses the keys from the config to decide what needs to be built.

2024-04-10 10:47 UTC, brynpickering commented on scripts/transport/annual_transport_demand.py
> +    road_distance_historically_electrified = (  # ASSUME historically electrified road consumption is all uncontrolled
put comment in its own line (above)

2024-04-10 10:47 UTC, brynpickering commented on scripts/transport/road_transport_controlled_charging.py
I haven't looked, but how close is this to a copy-paste of the `uncontrolled` python file? If it is very similar, we should consider using the two files with a controlled/uncontrolled flag that decides on the functions to use etc.

2024-04-10 12:38 UTC, adrienmellot commented on scripts/transport/road_transport_controlled_charging.py
It's fairly different, because the `uncontrolled` scripts generate timeseries per vehicle type which are then aggregated and rescaled per resolution. This last step is similar but still different because contains different data structures. The `controlled` script is actually closer to the `rescale.py` in the heat sector.

2024-04-10 14:41 UTC, brynpickering requested changes
Need to also update docs `customisation.md` note `"demand/electrified-transport.yaml"`

2024-04-10 14:41 UTC, brynpickering commented on templates/models/techs/demand/electrified-transport.yaml
> +    {{ id }}.techs.demand_road_transport_electrified_uncontrolled:
Needs controlled tech here too. I'd maybe update to:

```yaml
{{ id }}.techs:
  demand_road_transport_electrified_uncontrolled:
  demand_road_transport_historic_electrified_uncontrolled:
  demand_road_transport_electrified_controlled:

2024-04-10 14:41 UTC, brynpickering commented on templates/models/techs/demand/electrified-transport.yaml
>              resource_min_use: 1
should this be "force_resource"?

2024-04-10 21:04 UTC, adrienmellot commented on templates/models/techs/demand/electrified-transport.yaml
>              resource_min_use: 1
I've updated it, indeed I think it makes more sense

2024-04-11 07:34 UTC, brynpickering approved these changes

2024-04-11 07:35 UTC, merged