Add industry module
calliope-project/euro-calliope pull request #340
Opened 2024-04-10 10:15 UTC by irm-codebase

Fixes #308, #310.

This pull request includes the "skeleton" of the industry module, and includes the steel industry sub-workflow as an example.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [x] CHANGELOG updated
- [x] Minimal workflow tests pass
- [ ] Tests added to cover contribution (not relevant until module is complete)
- [ ] Documentation updated (not relevant until module is complete)
- [ ] Configuration schema updated (not relevant until module is complete)

2024-04-10 10:58 UTC, brynpickering reviewed
Some comments. Will need @timtroendle to comment on the utils files. We have `eurocalliopelib` at the moment to store utility functions. Should these go there? Or does the modularisation require a different approach?

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/config.yaml
> +        year-range: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
Just do start and end point and then use `slice(*year_range)` in your script. This should possibly be in the config under `pre-processing` as it also affects other eurostat/ch/jrc data.

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/industry.smk
> +TMP_PATH = "modules/industry/tmp"
`MODULE_PATH = "modules/industry"` and then all the others are  `MODULE_PATH + "..."`

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/industry.smk
> +        path_output = f"{TMP_PATH}/annual_demand_steel.csv"
I think Tim has now changed the naming convention from "demand" to "final_energy".

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/raw_data/jrc_idees_processed_energy.csv.gz
This should no longer be needed. We can now grab JRC data directly from a file server. See transport and heat demand modules.

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/src/steel_industry.py
> +H2_LHV_KTOE = 2.863  # 0.0333 TWh/kt LHV -> 2.863ktoe/kt
Move these to the config

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/src/steel_industry.py
> +    path_output: str = "",
`Optional[str] = None` and then use `if path_output is not None:`.

2024-04-10 10:58 UTC, brynpickering commented on modules/industry/src/utils/formatting.py
> +LEVEL_ORDER = ["subsector", "country_code", "unit", "carrier", "year"]
move to config

2024-04-10 14:09 UTC, irm-codebase commented on modules/industry/config.yaml
> +        year-range: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
Agreed. I had to use `range(*year_range)`, but it works well.
One issue here is that, by design, we've restricted access in the module to generic configuration.

For now I've kept it at the module level. Correcting this for all the configuration should be a separate issue.

2024-04-10 14:37 UTC, irm-codebase commented on modules/industry/src/steel_industry.py
> +H2_LHV_KTOE = 2.863  # 0.0333 TWh/kt LHV -> 2.863ktoe/kt
Config is meant to hold things that are exclusively user-relevant.

In this case, `CAT_NAME_STEEL` is predetermined by JRC and should not really be changed by the user because it can only lead to errors within `steel_industry.py`. Other sectors will use a similar structure.

Maybe this does apply for `H2_LHV_KTOE`. I'll move it to the config.

2024-04-10 14:38 UTC, irm-codebase commented on modules/industry/src/utils/formatting.py
> +LEVEL_ORDER = ["subsector", "country_code", "unit", "carrier", "year"]
See my comments above regarding non-user specific configuration. This is only relevant to formatting, any other configuration will result in broken functionality.

2024-04-10 14:54 UTC, brynpickering commented on modules/industry/config.yaml
> +        year-range: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
Careful here: range does not include the final value by default.

2024-04-10 14:59 UTC, brynpickering commented on modules/industry/src/steel_industry.py
> +H2_LHV_KTOE = 2.863  # 0.0333 TWh/kt LHV -> 2.863ktoe/kt
recycled steel percentage is also an assumption / based on some (now unknown) data source, as is HDRI consumption

2024-04-10 16:03 UTC, brynpickering commented on modules/industry/config.yaml
You should have a schema for this config.

2024-04-11 07:34 UTC, irm-codebase commented on modules/industry/raw_data/jrc_idees_processed_energy.csv.gz
We've created issue #345 to tackle this. Merging the basic structure of the industry module is a blocker for issues #311 and #309.

2024-04-11 07:39 UTC, irm-codebase commented on modules/industry/config.yaml
We've created issue #347 to tackle this.

A schema is a great idea, but the module's configuration might change too much while we port features. We'd prefer to do it once the chemical and "other" sectors are ported, to ensure the configuration file is mature enough.

2024-04-11 07:54 UTC, irm-codebase commented on modules/industry/config.yaml
> +        year-range: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
Fixed!

2024-04-11 08:08 UTC, irm-codebase commented on modules/industry/src/steel_industry.py
> +H2_LHV_KTOE = 2.863  # 0.0333 TWh/kt LHV -> 2.863ktoe/kt
We've moved only the recycled share of scrap steel to the cnf, for now. The others can also be moved later if we find it to be useful :)

2024-04-11 08:24 UTC, brynpickering commented on modules/industry/src/steel_industry.py
> +    """Get t_h2/t_steel, usually for H-DRI."""
```suggestion
    """Get t_h2/t_steel, usually for H-DRI. Conversion factor of 0.05 t_h2/t_steel is assumed"""
```

2024-04-11 08:26 UTC, brynpickering commented on modules/industry/src/steel_industry.py
> +    return (1 - recycled_steel_share) * 0.05
```suggestion
    # ASSUME: conversion factor of 0.05 t_h2/t_steel.
    return (1 - recycled_steel_share) * 0.05
```

2024-04-11 09:04 UTC, timtroendle requested changes
That's an excited pull request, thanks!

In my review, I mainly focussed on the structure assuming @brynpickering has checked the data processing logic. There are a few consistency related issues that need addressing. 

In addition, this change is not adding a feature and it's not show-casing the entire integration and no tests. Would it be possible to refactor the change so it's a feature? What I mean is: can we build this into the model? I understand you derive annual steal demand, so from there you could quite easily create flat steel demand profiles for all locations and put those into the model. Only then would we see the entire integration pipeline: model feature, documentation, and tests.

2024-04-11 09:08 UTC, irm-codebase commented
> @irm-codebase and @tud-mchen6 maybe we can discuss the design briefly after the group meeting today? @brynpickering may be useful to include in the discussion.

That would be good! No problem on my side :+1:

2024-04-11 09:13 UTC, irm-codebase commented on CHANGELOG.md
> +* **ADD** industry module and steel industry energy demand processing. NOT CONNECTED TO THE MAIN WORKFLOW. Industry sectors pending: chemical, "other".
The industry data pipeline has a lot of steps. Briefly:

1. Process industry sub-sectors (steel/chemicals/other...)
2. Merge subsector demands and test against dramatic increase/decrease in overall demand.
3. Scale demands based on a configuration .csv.
4. Create demand profiles (flat)

Adding everything in one go is too much, so we are working top down to keep things manageable. The "connection" to the main workflow will happen at around step 5, but first we need all the previous steps.

2024-04-11 09:37 UTC, irm-codebase commented on modules/industry/config.yaml
> +    outputs:
This are quite necessary, in our mind: the general goal of the modules is to de-couple them from the main workflow. If/when we convert the module to a wrapper (which lives in a separate repository), it'll be important to make sure that the main workflow/code is agnostic to locations in the Euro-Calliope workflow.

To ensure this, we decided to add inputs in the config file.

2024-04-11 09:39 UTC, irm-codebase commented on modules/industry/config.yaml
> +    inputs:
Hmmm... the purpose of the input section in `config.yaml` is to specify files that come from the main workflow.

How about `module-inputs`, to ensure clarity?

2024-04-11 09:43 UTC, irm-codebase commented on modules/industry/README.md
> +Placeholder text for the industry module documentation.
We've added a brief description in the `README.md` file.

This will be completed in conjunction with the `schema` file as we add more steps in the processing pipeline.

2024-04-11 09:46 UTC, irm-codebase commented on modules/industry/config.yaml
> +    inputs:
This is the setup we are following:

**Inputs**: files produced by rules outside of our module.
**Outputs**: files produced by the module that are relevant to the main workflow (intermediary steps go into the /tmp folder).
**Configuration**: a .yaml file that gives users the ability to modify module behaviour.
**Module**: code and steps for industry. Ideally, users shouldn't need to mess with it unless something needs to be added.

![module_setup](https://github.com/calliope-project/euro-calliope/assets/72193617/6ef4ba80-2750-4827-99dd-a28529292b7c)

2024-04-11 09:50 UTC, irm-codebase commented on modules/industry/env_industry.yaml
The end-goal is the opposite, actually: to let users specify their input files (some predetermined, others optional), and separate the module entirely.

We'd like to keep this env file to ensure containerization in case we decide to go a step further and use wrappers.

2024-04-11 13:56 UTC, irm-codebase commented on modules/industry/config.yaml
> +    inputs:
We'll keep the current approach (for now).
You can find explanations in the schema.yaml of the module :+1:

2024-04-11 15:19 UTC, irm-codebase commented on modules/industry/industry.smk
> +    conda: CONDA_PATH
The module has to be run from the base environment due to Snakemake quirks, so we only need one env file.
It does include snakemake (see `env_industry.yaml`). You should not need another one...

2024-04-11 15:20 UTC, irm-codebase commented on modules/industry/src/utils/formatting.py
There is both jrcidees parsing and regular formatting in this folder. We'll keep the name utils to avoid having 3 folder layers.

2024-04-11 15:24 UTC, irm-codebase commented on modules/industry/src/steel_industry.py
> +from utils import formatting
I think this is a strong argument to use wrappers instead...

Moving these utils to another location (outside the module) sort of defeats the purpose of modularisation in the first place...

2024-04-11 15:28 UTC, irm-codebase commented on modules/industry/industry.smk
> +DATA_PATH = f"{MODULE_PATH}/raw_data"
The JRC step that @brynpickering will effectively remove the raw_data folder. We have changed out to build, though!

2024-04-11 15:35 UTC, irm-codebase commented on modules/industry/config.yaml
> This config must go into the metadata that we create for model builds. See the `build_metadata` rule.

The general `config` already includes our module's configuration. Does this resolve your issue?

```
# Include modules
configfile: "modules/industry/config.yaml"
```

2024-04-22 14:12 UTC, irm-codebase commented
Relatively big update to this PR to fix #346. 

This was necessary because #354 made the pandas code go significantly slower. Moving to `xarray` made this module significantly faster. All results have been tested using checksums, and I can confirm the results are the same.

2024-05-02 11:54 UTC, brynpickering commented
@irm-codebase if you can rebase this onto current `develop` then I'll review

2024-05-08 14:11 UTC, irm-codebase commented
@brynpickering updated to the newest JRC version.

I had to modify a couple of lines at the JRC level because the production dataset did not have names for the variables. Hope that's ok.

2024-05-09 09:58 UTC, brynpickering requested changes
Great, we're close to having this ready to merge in!

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/industry.smk
> +# jrc_idees_processed* files in the raw_data folder should ideally be produced by a rule instead
fixed?

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +    jrc_prod = xr.open_dataset(path_jrc_industry_production)
`open_dataarray` and then you don't need production to have a data variable

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +    cnf_steel: dict,
minor point, but could you call this `config_steel`? `cnf` is not an abbreviation we use anywhere else

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +    recycled_share = cnf_steel["recycled-steel-share"]
this is the only thing extracted from the steel config. I would pass it thorugh as a direct parameter rather than wrapped in a dict. It is generally a good idea to split up config items in snakemake as it then tracks those specific config values for changes rather than the whole dictionary. I know you don't expect to need steel config params outside this script, but you never know!

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +        "Electric arc", "Low enthalpy heat", "Electric arc", jrc_energy, jrc_prod
Is it only electric arc that has low enthalpy heat?

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +        "Electric arc", "Low enthalpy heat", "Electric arc", jrc_energy, jrc_prod
Ah ok, it's because we're assuming future space heating will be based on the electric arc intensity. Might be worth mentioning that in a comment.

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +        "Electric arc", "Low enthalpy heat", "Electric arc", jrc_energy, jrc_prod
Ignore this, it's in the main docstring.

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +# TODO: fix me!
Should this still be here?

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +    new_steel_demand = formatting.fill_missing_countries_years(
Is this the approach I took? I thought I filled in the _intensities_ based on neighbours and ffill/bfill and _steel production_ based on annual energy production, then combined those into a new electricity demand. I wonder what the difference in result would be.

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    if fill_empty:
Aha, this is what I probably meant by filling empty data at the intensity level.

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +def get_subsection_useful_intensity(
Is there a useful assertion you can add here?

2024-05-09 09:58 UTC, brynpickering commented on scripts/jrc-idees/industry.py
> +    df_processed = df_processed.assign(variable="demand")
Now that I see your changes, I guess having a "variable" column that is transformed into the dataset variables is fine. I would not bother having as an input arg to `df_to_xr`, just take it as given that it is the col `"variable"`. I'd also call this one "production" rather than "demand".

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    if any(removed_dims):
```suggestion
    removed_coords = set(ds.coords).difference(STANDARD_COORDS)
    removed_dims = removed_coords.intersection(ds.dims)
    if removed_dims: 
```
an empty set will resolve to False, otherwise True.

Is this an expected problem, that there would be dimensions with coordinates? Otherwise I'd say that the first two lines could just be `set(ds.dims).difference(STANDARD_COORDS)`

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/formatting.py
> +    # Ensure countries follow our standard alpha3 convention.
They do in the output of the JRC processing, so no need to do that again here.

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/formatting.py
> +    return all_filled
Once you have done all the filling, you could check that there is no case of conumption in a year being outside a range of the average. E.g. you could catch cases of zero consumption in a year when the other years for that country have non-zero data. Maybe doesn't work because some countries really didn't have any steel production in e.g. 2000, but just a thought of how to confirm that gap-filling has succeeded.

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/steel_industry.py
> +def get_steel_demand_df(
you're now getting an `nc`/`dataset`, not `df`

2024-05-09 09:58 UTC, brynpickering commented on modules/industry/scripts/utils/formatting.py
> +def to_calliope_style(subsector_demand: xr.Dataset) -> pd.DataFrame:
Is this used any more?

2024-05-09 20:10 UTC, irm-codebase commented on scripts/jrc-idees/industry.py
> +    df_processed = df_processed.assign(variable="demand")
Fixed!
And yeah, I think that specifying the variable names is better in case anyone starts processing these things in a different way.

2024-05-09 20:14 UTC, irm-codebase commented on modules/industry/README.md
> +Some industries are specified as 'sub-module' in this module, such as iron and steel industry. This allows flexibly configure the decarbonisation level of each industry separately. All other industri
Noted, I fixed the spacing. I copy pasted your fix and added a small extra correction (industies -> industries).

2024-05-09 20:15 UTC, irm-codebase commented on modules/industry/README.md
> +For non-developer users, `config.yaml` is the main file to look into. Here, one can specify parameters such as the years to be included in the data processing, assumptions such as the share of recycl
Ditto. Added the spacing.

2024-05-09 20:23 UTC, irm-codebase commented on modules/industry/config.yaml
> +    outputs:
Unfortunately yes, for now. If removed, `outputs` becomes a None item, and breaks the schema. These will go away once the full module workflow is complete.

2024-05-09 20:31 UTC, irm-codebase commented on modules/industry/scripts/steel_industry.py
> +    recycled_share = cnf_steel["recycled-steel-share"]
This is to keep the configuration of sectors consistent: chemical, other and any extras are meant to have their own section in the configuration. Passing the whole dictionary keeps the snakemake leaner and is easier to work with on the python side too.

Besides, if another script needs a specific parameter from industry, they can just grab it directly instead of taking the whole dictionary.

2024-05-09 20:33 UTC, irm-codebase commented on modules/industry/scripts/steel_industry.py
> +    recycled_share = cnf_steel["recycled-steel-share"]
I'll keep this as-is, for now.

2024-05-09 20:47 UTC, irm-codebase commented on modules/industry/scripts/steel_industry.py
> +    new_steel_demand = formatting.fill_missing_countries_years(
Seems like it was! We checked the results against those in SCEC during development, and it's how it was done. Here's a brief excerpt:

```pthon
all_consumption = pd.concat([
        steel_energy_consumption.reorder_levels(all_other_industry_consumption.index.names),
        chem_energy_consumption.reorder_levels(all_other_industry_consumption.index.names),
        all_other_industry_consumption,
        all_other_industry_space_heat
    ])
    all_consumption.columns = all_consumption.columns.astype(int).rename('year')
    all_filled_consumption = fill_missing_data(energy_balances, cat_names, carrier_names, all_consumption)
    units = all_filled_consumption.index.get_level_values('unit')
    all_filled_consumption.loc[units == 'ktoe'] = (
        all_filled_consumption.loc[units == 'ktoe'].apply(util.ktoe_to_twh)
```

`all_filled_consumption` already has the steel stuff, and `fill_missing_data` is the `fill_missing_countries_years` bit here.

It would be good to introduce an issue with improvements for industry, to make things better once the whole pipeline is in. There are a couple of things in the "other" processing that could improve, too.

2024-05-09 20:54 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +def get_subsection_useful_intensity(
Do you mean the `assert` at line 70?

2024-05-09 20:56 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    if fill_empty:
No problems, then?

2024-05-09 21:00 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +# TODO: fix me!
The "other" industry merge corrects it, and I do not want to deal with the merge conflict... so yeah.

2024-05-09 21:17 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    if any(removed_dims):
Oh this is much more efficient! Thanks.

2024-05-09 21:28 UTC, irm-codebase commented on modules/industry/scripts/utils/formatting.py
> +def to_calliope_style(subsector_demand: xr.Dataset) -> pd.DataFrame:
removed

2024-05-10 07:55 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +def get_subsection_useful_intensity(
I mean one in `get_subsection_useful_intensity`

2024-05-13 08:35 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +def get_subsection_useful_intensity(
I added a check for divide-by-zero. It's the only generic test that made sense to me here.

2024-05-13 08:51 UTC, irm-codebase commented on modules/industry/scripts/utils/formatting.py
> +    return all_filled
I tried a couple of approaches, but I could not land on something generic enough that justifies the addition.
If I go for averages, countries that introduced production fail (as you mention).

I think a more robust approach would be to introduce a testing stage after these files are generated, but before calliope translation. Checking if the rate of increase/decrease of the carriers in each industry category are within certain ranges would be the most universal approach, since in theory it would sideline this problem.

Skipped this for now.

2024-05-13 09:09 UTC, irm-codebase commented
@brynpickering added most of your suggestions, with the exception of the gap filling test.

Let me know if you find anything else during review. Otherwise, I'll merge this in and update the "chemical" and "other" cases.

2024-05-14 07:59 UTC, brynpickering commented
One thing that is possibly missing is documentation in the main euro-calliope docs about these new modules. But for now I think we can ignore that as we may well move this to a different repo before the next release...

2024-05-14 08:07 UTC, timtroendle commented
I would add documentation now. It's _now_ in this repo and we may or may not move it somewhere else in the future. Like the model, the documentation is quite modular anyway, isn't it? So we could easily move the industry bit out of the documentation, too, should we decide to pull out this module into its own repo. We may as well decide to keep the documentation in the main repo and simply mention the optional module (one aspect we haven't discussed at all so far).

2024-05-14 09:27 UTC, irm-codebase commented
@timtroendle I'd say that adding full documentation now is only additional overhead: this is only part of the module (we are still missing other industry and chemical industry), plus disaggregation, testing and scaling steps. Also, we have already added pre-eliminary documentation explaining usage (see the README.md).

Besides, I agree with Bryn: moving module subworkflows into a separate repo makes a lot of sense. Still, I created issue [#381](https://github.com/calliope-project/euro-calliope/issues/381) to make sure we stay on point with this.

For now, let's finish this PR once and for all, please 🙏🙏🙏?

2024-05-14 09:44 UTC, timtroendle commented
Yeah fair point. Sorry, didn't want to be annoying, it's just easy to forget these things.

2024-05-14 11:03 UTC, brynpickering commented on envs/default.yaml
> +    - xarray=2022.9.0
@irm-codebase  This is causing a merge conflict. Do you actually need the default env to be update if you have modularised industry?

2024-05-14 12:44 UTC, irm-codebase commented on envs/default.yaml
> +    - xarray=2022.9.0
@brynpickering nope. Apologies, that's a leftover from were the module needed to update the country names. Since that's handled on the JRC part, we no longer have version conflicts there.

Fixed!

2024-05-14 15:34 UTC, merged