Add gridded heat demand timeseries
calliope-project/euro-calliope pull request #343
Opened 2024-04-10 16:17 UTC by sjpfenninger

Fixes #341.

Partially solves #299.

Implements gridded heat demand timeseries as an intermediate step towards completing #16. Based on a blend of sector-coupled-euro-calliope and balancing-act. So far, it is not connected to the main DAG, but you can build a gridded heat demand profile by running, for example:

```
snakemake --cores 1 --configfile config/minimal.yaml -f build/data/national/gridded_hourly_unscaled_heat_demand_2016.nc
```

Next step will be to wire this up with the existing heat code to generate scaled, per-zone heat demand profiles.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-04-11 15:18 UTC, timtroendle requested changes
I wouldn't say I understood every aspect of the profile creation script, but that's entirely because of my lack of knowledge of the conceptual model. I find the code to be very well written and understandable.

I have a few small comments regarding structure of the files and stuff like that.

2024-04-11 15:18 UTC, timtroendle commented on scripts/heat/gridded_unscaled_heat_profiles.py
> +def get_unscaled_heat_profiles(
Can you explain what "unscaled" means in this context?

2024-04-11 15:18 UTC, timtroendle commented on rules/heat.smk
> +        script = "scripts/heat/population_per_gridbox.py",
In new versions of Euro-Calliope (and Snakemake) this line is unecessary. It was always redundant and fortunately isn't neeeded anymore.

2024-04-11 15:18 UTC, timtroendle commented on rules/heat.smk
> +        script = "scripts/heat/gridded_unscaled_heat_profiles.py",
As above.

2024-04-11 15:18 UTC, timtroendle commented on scripts/heat/gridded_unscaled_heat_profiles.py
> +    wind_da = wind_ds["wind_speed"].mean("time")
Maybe call this average_wind_speed.

2024-04-11 15:18 UTC, timtroendle commented on scripts/heat/gridded_unscaled_heat_profiles.py
> +def get_hourly_heat_profiles(reference_temperature, daily_heat, hourly_params):
type hints

2024-04-11 15:18 UTC, timtroendle commented on scripts/heat/gridded_unscaled_heat_profiles.py
> +def get_hourly_heat_profiles(reference_temperature, daily_heat, hourly_params):
well actually for all functions in this file. I will stop commenting.

2024-04-12 12:44 UTC, sjpfenninger commented on config/default.yaml
> +    when2heat-params: https://raw.githubusercontent.com/oruhnau/when2heat/351bd1a2f9392ed50a7bdb732a103c9327c51846/input/bgw_bdew/{dataset}
Yes, we can package it up and put it on Zenodo. It's MIT-licensed.

2024-04-12 12:46 UTC, sjpfenninger commented on scripts/heat/population_per_gridbox.py
> +    path_to_wind_speed,  # FIXME: this is used to get the coordinates, but nothing else
You are right, it doesn't _need_ fixing. And it won't likely be fixed because we think the entire function will go away. For now I will rename it to `path_to_coordinates`. Temperature and heat having the same coordinates is an assumption/convention that I don't think we check anywhere, so it's a bit dangerous.

2024-04-12 14:22 UTC, sjpfenninger commented on scripts/heat/gridded_unscaled_heat_profiles.py
> +def get_unscaled_heat_profiles(
Adding docstring

2024-05-07 06:53 UTC, sjpfenninger commented
@timtroendle ping - this is ready for re-review and hopefully merging

2024-05-07 08:15 UTC, timtroendle approved these changes

2024-05-07 08:16 UTC, timtroendle commented
Thanks for the ping, it all looks good to me.

2024-05-07 08:17 UTC, merged