Add "other" industry demand
calliope-project/euro-calliope pull request #355
Opened 2024-04-11 13:50 UTC by tud-mchen6

Fixes #309 .

Adding "other" industry in the industry module.

#340 is a prerequisite for this PR.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [x] CHANGELOG updated
- [x] Minimal workflow tests pass
- [ ] Tests added to cover contribution (not relevant)
- [ ] Documentation updated (not relevant)
- [ ] Configuration schema updated (not relevant)

2024-04-12 12:40 UTC, brynpickering reviewed
@tud-mchen6 could you confirm that the only change in this PR compared to #340 is the `chemicals_industry.py` file?

2024-04-12 12:40 UTC, brynpickering commented on modules/industry/src/chemicals_industry.py
> +    }
This should probably all be in the configuration

2024-04-12 12:40 UTC, brynpickering commented on modules/industry/src/chemicals_industry.py
> +H2_LHV_KTOE = 2.863  # 0.0333 TWh/kt LHV -> 2.863ktoe/kt
Move to config

2024-04-12 12:40 UTC, brynpickering commented on modules/industry/src/chemicals_industry.py
> +METHANOL_LHV_KTOE = 0.476  # 19.915 MJ/kg LHV -> 19915000MJ/kt -> 0.476ktoe/kt
Move to config

2024-04-12 12:40 UTC, brynpickering commented on modules/industry/src/chemicals_industry.py
> +def get_chem_demand_df(
Would be worth fleshing out a docstring here describing each of the inputs and a brief overview of what the script is doing. This will show you (and me) that you have a good idea of what it is you've implemented.

2024-04-12 12:40 UTC, brynpickering commented on modules/industry/src/chemicals_industry.py
> +    path_output: str = "",
```suggestion
    path_output: Optional[str] = None,
```
Then `if path_output is not None:` later on

2024-04-16 07:44 UTC, tud-mchen6 commented
> @tud-mchen6 could you confirm that the only change in this PR compared to #340 is the `chemicals_industry.py` and `other_industry.py` files?

If compared to the commit of #340 at the same time point, the only change **is indeed** that `other_industry.py` is added and relevant rule is added in the `industry.smk` file. 

Now the branch of #340 has developed quite far (e.g. integrating the JRC data processing script), and these branches need to be merged with some effort. However, #340 has never developed the functionality of chemical industry or "other" industry, so functionality wise they are still separated.

2024-04-26 18:37 UTC, irm-codebase commented on modules/industry/src/other_industry.py
> +    breakpoint()
fixed

2024-04-27 10:28 UTC, irm-codebase commented
This PR now integrates the JRC module code and `xarray` processing.
Also, I've added some quality of life processing for "other industries":
- You can now "turn off" the processing of specific sectors via the configuration. All non specific sectors will be parsed through the "other" rule.
- You can now select which carriers to extract at a final energy level and at an end-use level.
- You can select the method of extraction. For now only "priority" is available, which reflects how SCEC does it.

2024-05-14 15:35 UTC, brynpickering commented
@irm-codebase ready to rebase onto develop now that #340 is merged in!

2024-05-15 15:35 UTC, irm-codebase commented on modules/industry/scripts/utils/filling.py
> +    # TODO: CHE has no values for "Wood and wood products" and "Transport Equipment".
CHE was triggering `assert` failures due to some missing data. For now I am just assuming those values are 0 (same as SCEC). 

This is mostly because the CHE processing above this module does not seem to provide data for these sectors, meaning they are filled with `nan` in all years, so none of our filling methods work.

Let me know what you think.

2024-05-15 15:37 UTC, irm-codebase reviewed
@brynpickering ready for review!

CHE pre-processing was leading to some funky issues, so I've added comments on how I dealt with it.

2024-05-15 15:37 UTC, irm-codebase commented on modules/industry/scripts/utils/filling.py
> +    # TODO: CHE has no values for "Wood and wood products" and "Transport Equipment".
CHE was triggering `assert` failures due to some missing data. For now I am just assuming those values are 0 (same as SCEC). 

This is mostly because the CHE processing above this module does not seem to provide data for these sectors, meaning they are filled with `nan` in all years, so none of our filling methods work.

Let me know what you think.

2024-05-30 07:19 UTC, brynpickering requested changes
Looks good, just some minor changes to make. I'll go through it again tomorrow by running the code and checking the results at different points. Would be good if a data consistency check existed somewhere, i.e. that no energy demand is lost / added.

2024-06-06 11:35 UTC, brynpickering commented on modules/industry/industry.smk
> +if "Iron and steel" in config["params"]["specific-industries"]:
If it is not a "specific" industry then it gets automatically lumped in as "other". So it's possible to overhaul the steel industry to decarbonise feedstocks or to just pipe all demands without converting any processes

2024-06-11 10:08 UTC, irm-codebase commented on modules/industry/config.yaml
> +        specific-industries: ["Iron and steel", "Chemicals Industry"]
I've gone for `enabled-subsector-processing`. This should make it clear that it can be activated/deactivated at will.

2024-06-11 10:13 UTC, irm-codebase commented on modules/industry/industry.smk
> +if "Iron and steel" in config["params"]["specific-industries"]:
> Is this the best way to add this conditionality? @timtroendle maybe you can comment.
> 
> The other approach would be to use a conditional list as inputs in a later rule, e.g.:
> 
> ```python
> rule merge_industry_demands:
>   input:
>     specific_industries = expand(f"{BUILD_PATH}/annual_demand_{subsector}.nc", subsector=subsector_translator(config["params"]["specific-industries"]))
> ```
> 
> where `subsector_translator` is a helper function to map e.g. `Steel and Iron` to `steel`.

This is a good idea for the merging step. But that one also involves adding scaling factors (which we currently lack). I'll keep the module this way for now since it is out of focus for this merge.

2024-06-11 10:17 UTC, irm-codebase commented on modules/industry/industry.smk
> +    message: "Calculate energy demand for all other industry sectors in JRC-IDEES."
Modified the use of `sector` in other parts of the module too.

2024-06-11 13:39 UTC, irm-codebase commented on modules/industry/config.yaml
> +        specific-industries: ["Iron and steel", "Chemicals Industry"]
I changed it to `non-generic-categories` and changed `other` to `generic-config`.
Hopefully this makes processing clearer.

2024-06-11 13:47 UTC, irm-codebase commented on modules/industry/industry.smk
> +        path_energy_balances = config["inputs"]["path-energy-balances"],
I'd like to keep `path` to avoid confusion between variables holding data and those holding strings.
A bit more explicit.

2024-06-11 14:25 UTC, irm-codebase commented on modules/industry/scripts/other_industry.py
> +    for carrier in JRC_TO_CALLIOPE:
I've actually removed the renaming step from this file. It makes more sense to do it once we merge all category files into one and re-scale it (if necessary).

2024-06-11 14:26 UTC, irm-codebase commented on modules/industry/scripts/other_industry.py
> +    """Transform final demand of all sectors by giving priority to certain carriers.
Changed to "category" (see prev. comment).

2024-06-11 14:50 UTC, irm-codebase commented
@brynpickering I've implemented your comments, and a couple of extras.

The biggest updates are:
- improved names of stuff to reduce ambiguity
- standardized naming from "sector" to "category" to match how JRC names things
- carrier names are no longer modified (better do it when aggregating/rescaling files)
- added an additional processing option for final energy demand

2024-06-26 07:07 UTC, brynpickering reviewed
I'm _almost_ happy for this one to go through! Just a couple of minor comments on naming and unit checking.

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/industry.smk
> +        path_energy_balances = config["inputs"]["path-energy-balances"],
but if all inputs hold strings...? How about `config["input-paths"]["energy-balances"]` etc?

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/industry.smk
> +    script: f"{SCRIPT_PATH}/generic_processing.py"
"merged_category_processing.py"? I would always have `category` added to whatever adjective we choose!

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/scripts/generic_processing.py
> +    # Extract useful dem. -> remove useful dem. from rest -> extract final dem.
dem -> demand

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/scripts/generic_processing.py
> +        case "keep everything":
I assume this doesn't lead to any double counting?

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/scripts/utils/filling.py
> +    # TODO: CHE has no values for "Wood and wood products" and "Transport Equipment".
Yeah, we don't have much choice on that. I assume they are in "other industry" in the CHE data so we can't extract them.

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    final_intensity = standardize(final_intensity, "twh/kt", name="final_intensity")
is it worth checking the unit of the incoming data before setting this to `twh/kt`. I.e., `useful_demand` should have the unit `twh`.

2024-06-26 07:07 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    useful_intensity = standardize(useful_intensity, "twh/kt", name="useful_intensity")
same as above RE checking unit

2024-06-26 10:01 UTC, timtroendle requested changes
Looks good to me overall. I have a few minor comments.

2024-06-30 19:38 UTC, brynpickering commented on modules/industry/config.yaml
> +        non-generic-categories: ["Iron and steel", "Chemicals Industry"]
I thought of "explicit" initially too. I then had a look in the dictionary and decided it wasn't quite right (it's more about leaving nothing implied). I'm not sure that "discrete" is right either. "separate"? "independent"?

2024-06-30 19:44 UTC, brynpickering commented on modules/industry/industry.smk
> +    script: f"{SCRIPT_PATH}/generic_processing.py"
@irm-codebase is using "category" as it aligns with the JRC-IDEES naming convention. I don't really mind if it's subsector or category, so long as it remains the same throughout the whole submodule.

2024-06-30 20:32 UTC, irm-codebase commented on modules/industry/industry.smk
> +    script: f"{SCRIPT_PATH}/generic_processing.py"
@timtroendle: Bryn is right on this one. Category is not a word we use often, but it makes sense int the context of JRC-IDEES data. I'd like to keep it that way.

2024-06-30 20:40 UTC, irm-codebase commented on modules/industry/config.yaml
> +        non-generic-categories: ["Iron and steel", "Chemicals Industry"]
Hmmm... I also struggled with names. A good name has to do two things:
- Specify that these are specific / individual to a given subcategory.
- Imply that all the rests will go to the "other" / generic / merged.

Here are words with the antonym, based on your comments.
- Specific / generic categories
- Separate / combined categories  < --- I like this one the best.
- Independent / dependent categories
- Explicit / implicit categories
- Discrete / joined categories

I suggest "separate-category-processing" and "combined-category-processing".

2024-07-01 09:57 UTC, timtroendle commented on modules/industry/config.yaml
> +        non-generic-categories: ["Iron and steel", "Chemicals Industry"]
I personally think "subsectors" is clearer, because "category" is generic. "category" is also an implementation detail: should we move to a different data source than JRC, that name would change. Anyways, "category" is fine by me.

I like the "separate" and "combined" distinction!

2024-07-01 11:16 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    final_intensity = standardize(final_intensity, "twh/kt", name="final_intensity")
I'm actually setting it because `xarray`, for some horrible reason, decided to actually delete attributes by default.
The library is limited to handling only `twh` as inputs.

I'll add a check at the start to ensure this is specified.

Another option would be to use pint (https://xarray.dev/blog/introducing-pint-xarray), but without standardising this on the JRC side there is not much benefit...

2024-07-01 11:25 UTC, irm-codebase commented on modules/industry/scripts/generic_processing.py
> +    cat_names_df = cat_names_df[~cat_names_df["jrc_idees"].isin(non_generic_categories)]
I'd rather avoid that, because it introduces the risk of _not_ processing an added category.
Besides, JRC-IDESS is unfortunately quite old (2015), and this processing is very tied to it. Do not see this is a future issue.

I have my sights on this other dataset: https://iopscience.iop.org/article/10.1088/2753-3751/ad4e39
but it is going to require a different module with its own steps.

2024-07-01 11:30 UTC, irm-codebase commented on modules/industry/config.yaml
> +        non-generic-categories: ["Iron and steel", "Chemicals Industry"]
@timtroendle : I also do not like category, but keeping the code close to the data helps in this case because JRC-IDEES is already hard to wrap your head around due to the amount of columns it has (sector/category/subcategory/process/energy type...)

A different data source is going to require a different approach. This (and the JRC module above it) are just very tied to how the data was constructed. I think this is unavoidable for things as heterogeneous as industry.

2024-07-01 14:27 UTC, brynpickering commented on modules/industry/config.yaml
> +        non-generic-categories: ["Iron and steel", "Chemicals Industry"]
Agreed, "Separate" / "combined" sounds good!

2024-07-01 14:29 UTC, brynpickering commented on modules/industry/industry.smk
> +    script: f"{SCRIPT_PATH}/generic_processing.py"
Will it become `subsector` at some point in the module, as it gets closer to being a Calliope model input?

2024-07-01 14:29 UTC, brynpickering commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    final_intensity = standardize(final_intensity, "twh/kt", name="final_intensity")
> I'm actually setting it because xarray, for some horrible reason, decided to actually delete attributes by default.

At what point in the process?

2024-07-02 15:11 UTC, irm-codebase commented on modules/industry/industry.smk
> +    script: f"{SCRIPT_PATH}/generic_processing.py"
that would make sense! the idea is:
jrc categories -> specific/combined scripts -> combine/scale/disaggregate scripts -> calliope subsector

2024-07-02 15:16 UTC, irm-codebase commented on modules/industry/scripts/generic_processing.py
> +        case "keep everything":
@brynpickering it shouldn't. It's basically "assume nothing, do nothing with the data and just give me the final demand.

If a useful demand is requested, the lines above should remove it. So no double counting is possible.

2024-07-03 14:11 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    final_intensity = standardize(final_intensity, "twh/kt", name="final_intensity")
Operations in general will delete xarray attributes: https://docs.xarray.dev/en/stable/getting-started-guide/faq.html#what-is-your-approach-to-metadata

So, basically everywhere?

2024-07-03 14:14 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    final_intensity = standardize(final_intensity, "twh/kt", name="final_intensity")
I can change this in the xarray options, but I do not think it's a good idea unless we implement an actual unit checker. Better to lose them and mindfully set them than risk leaving invalid attributes during our operations.

2024-07-03 14:30 UTC, irm-codebase commented on CHANGELOG.md
> +* **ADD** industry module and steel industry energy demand processing. NOT CONNECTED TO THE MAIN WORKFLOW. Industry sectors pending: chemical. (Fixes #308, #309, #310, #347, #345 and #346)
Updated it with a simpler message. I'll add chemical industry once that is done.

2024-07-03 14:47 UTC, irm-codebase commented on modules/industry/industry.smk
> +        input:
Is there a way to tell snakemake to "monitor" a full folder? hard coding every-single utility file seems very brittle.

2024-07-03 15:42 UTC, timtroendle commented on modules/industry/scripts/generic_processing.py
> +    if path_output:
I needed for testing purposes, I'd recommend to let the function return a dataset which is stored somewhere else, as discussed in the last dev call. Otherwise you increase complexity of the function signature.

2024-07-03 15:51 UTC, irm-codebase commented on modules/industry/industry.smk
> +        input:
I think moving things to `/lib` actually makes things worse: it becomes a common dependency across all the environments that use it, diminishing their benefit. You can end up in a situation were one environment requires a lib/ update that breaks others.

On the other hand, making self-contained scripts bloats code and leads to repeated functionality.

2024-07-03 15:59 UTC, irm-codebase commented on modules/industry/industry.smk
> +        input:
I will add them for now, but this approach worries me.
An alternative is to move stuff out, and import them with a set tag.
If something is broken, then the focus should be in doing another release of that workflow.

```
module industry_workflow:
    snakefile:
        github("calliope/industry-smk", path="workflow/Snakefile", tag="v1.0.0")
    config: "config/industry.yaml"

use rule * from other_workflow as industry_*
```

But that's for the future, maybe.

2024-07-03 16:10 UTC, irm-codebase commented on modules/industry/scripts/generic_processing.py
> +    if path_output:
I'm a bit puzzled. That is already what this is doing: the `return other_demand` is an xarray. You could choose to save it or evaluate it directly in a test.

I'll just remove it.

2024-07-04 12:42 UTC, irm-codebase reviewed
Let me know if more fixes are needed

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/config.yaml
> +    input-paths:
Name change requested  by Bryn. This change is also reflected in rule scripts.

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/industry.smk
>      input:
This was added to the "combine" rule.

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/industry.smk
> +rule combine_and_scale:
This new rule makes sure that both "combined" and "specific" JRC categories are processed.
In the future they will be combined and scaled (chemicals industry must be finished first).

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/schema.yaml
All the requested name changes show here, too.

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/scripts/generic_processing.py
> +    assert other_demand.sum() < jrc_energy["final"].sum(), "Potential double counting!"
Simple assert to avoid double counting.

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +def check_units(jrc_energy: xr.Dataset, jrc_prod: xr.DataArray) -> None:
New method to ensure JRC data has the right format.

2024-07-04 12:42 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    # First by country avg. (all years), then by year avg. (all countries).
Done. I've also added it to other parts.

2024-07-05 13:24 UTC, timtroendle approved these changes

2024-07-05 13:24 UTC, timtroendle commented on modules/industry/industry.smk
>      input:
For the sake of being explicit rather than implicit, I would add them here, too.

2024-07-05 13:24 UTC, timtroendle commented on modules/industry/industry.smk
>      input:
Also, the "combine" rule is downstream of this, so this won't work, right? I would definitely make the dependencies explicit, then you do not even have to think about this at all.

2024-07-05 13:24 UTC, timtroendle commented on modules/industry/scripts/generic_processing.py
> +    assert other_demand.sum() < jrc_energy["final"].sum(), "Potential double counting!"
Shouldn't this be `<=`?

2024-07-05 17:25 UTC, irm-codebase commented on modules/industry/scripts/generic_processing.py
> +    assert other_demand.sum() < jrc_energy["final"].sum(), "Potential double counting!"
You are right! I'll make a quick update.

2024-07-05 17:32 UTC, irm-codebase commented
@timtroendle quick fix for the `assert` case you mentioned. I also updated the name of the files, to make them match the category (did not do it before to avoid breaking the review relations).

The aggregated rule runs with no problems!

2024-07-05 17:32 UTC, irm-codebase commented
No idea why the docs are not working. It's not related to my changes, for what I can see.

2024-07-09 07:30 UTC, brynpickering approved these changes

2024-07-09 07:33 UTC, merged

2024-07-25 17:20 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    carrier_final_demand = useful_dem_tot / carrier_eff
I must admit that I found this function very confusing when converting it from SCEC's code. @brynpickering please correct if I say something wrong here.

> This basically means [all carriers demand added together] divided by [specific carrier efficiency]? But this formula only works for the entries that relate to the defined carrier and any other entries with different carriers will become null.

This is intended. Basically, if a carrier was never used to meet a specific useful demand, it's efficiency (`carrier_eff`) should be full of `nan` values.

> This then becomes an issue for line 165. useful_dem_tot.sum() will likely be larger than carrier_final_demand.sum() because the previous one contains demand of all carriers, while the latter only 'transformed' demand of one carrier. At least that is what I get from processing chemicals industry.

I see your point. How about this?

```
assert jrc_energy["useful].sel(carrier_name=carrier) < carrier_final_demand.sum(), "Creating energy!"
```

2024-07-25 17:22 UTC, irm-codebase commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    carrier_final_demand = useful_dem_tot / carrier_eff
@tud-mchen6 that being said, I think this function is only used in the "other"/combined industries processing, even in the old SCEC code. Just please make sure that this is the actual function you wish to use.

2024-08-27 09:01 UTC, tud-mchen6 commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    carrier_final_demand = useful_dem_tot / carrier_eff
> @tud-mchen6 that being said, I think this function is only used in the "other"/combined industries processing, even in the old SCEC code. Just please make sure that this is the actual function you wish to use.

As I understand, that is not true. The old SCEC code uses `electrical_consumption` in the function `get_chem_energy_consumption`, and `electrical_consumption` is generated by the function `get_carrier_demand`, which is a similar version to `get_carrier_demand` in `jrc_idees_parser.py` in the old industry module.

2024-08-27 09:01 UTC, tud-mchen6 commented on modules/industry/scripts/utils/jrc_idees_parser.py
> +    carrier_final_demand = useful_dem_tot / carrier_eff
> I must admit that I found this function very confusing when converting it from SCEC's code. @brynpickering please correct if I say something wrong here.
> 
> > This basically means [all carriers demand added together] divided by [specific carrier efficiency]? But this formula only works for the entries that relate to the defined carrier and any other entries with different carriers will become null.
> 
> This is intended. Basically, if a carrier was never used to meet a specific useful demand, it's efficiency (`carrier_eff`) should be full of `nan` values.
> 
> > This then becomes an issue for line 165. useful_dem_tot.sum() will likely be larger than carrier_final_demand.sum() because the previous one contains demand of all carriers, while the latter only 'transformed' demand of one carrier. At least that is what I get from processing chemicals industry.
> 
> I see your point. How about this?
> 
> ```
> assert jrc_energy["useful].sel(carrier_name=carrier) < carrier_final_demand.sum(), "Creating energy!"
> ```

Your suggestion at the end looks good, except that you may need to add a `.sum()` to the left hand side?