Feature EV controlled charging custom constraints
calliope-project/euro-calliope pull request #356
Opened 2024-04-12 10:48 UTC by adrienmellot

Fixes #350 .

Within the realm of full electrification of road transport, this PR allows the controlled charging share of this electricity demand to be constrained.

Possibly, we want to have the run.py file to be integrated in a better way, and also in workflow tests.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-05-03 13:58 UTC, brynpickering requested changes
Thanks for this @adrienmellot, shows how complex our EV modelling is. Too complex...?

Anyway, some reasonably major comments about reorganising file structures:

1. `run.py` could be restructured into a snakemake rule script that calls constraint adding scripts on-the-fly
2. the controlled EV annual demand and installed capacities rule should probably be split in two since they have some mutually exclusive inputs/params. They can use the same script (since they share the regionalisation step) but some parameter / wildcard is used in the script to decide whether `df_demand` or `df_charging_potentials` is generated.

2024-05-03 13:58 UTC, brynpickering commented on rules/transport.smk
> +rule create_controlled_road_transport_annual_demand_and_installed_capacities:
Could this be split into two rules or not? I.e. annual demand and installed capacities are two rules

2024-05-03 13:58 UTC, brynpickering commented on rules/transport.smk
> +rule create_controlled_ev_charging_parameters:
set a wildcard constraint on the allowed `dataset_name` values? It would help understand later all the files that can be generated by this rule

2024-05-03 13:58 UTC, brynpickering commented on scripts/transport/road_transport_controlled_charging.py
> +    df_ev_chargeable_distance = df_ev_chargeable_distance.assign(**{
Add an ASSUME comment that >2015 uses 2015 data. Also use `final_year` to set the upper bound? `range(2016, final_year + 1)` (and don't even do this extrapolation if `final_year` <=2015)

2024-05-03 13:58 UTC, brynpickering commented on scripts/transport/road_transport_controlled_charging.py
> +    # df_ev_chargeable_distance.index.name = None
delete

2024-05-03 13:58 UTC, brynpickering commented on scripts/transport/road_transport_controlled_constraints.py
> +):
Missing return type

2024-05-03 13:58 UTC, brynpickering commented on config/run.py
I'd suggest having a `run.py` in `scripts` and then a `add_constraints.py` in the `scripts/transport/` directory. The `run.py` has most of the content of this file _except_ the constraints. It then lods constraints as modules and loads them into the model:

```python
import importlib.util


model = calliope.read_netcdf(path_to_temp_model)
model.run(build_only=True)

for file in constraint_files:
    spec=importlib.util.spec_from_file_location("constraints", file)

    # creates a new module based on spec
    constraint_adder = importlib.util.module_from_spec(spec)

    # executes the module in its own namespace
    # when a module is imported or reloaded.
    spec.loader.exec_module(constraint_adder)

    constraint_adder.add_eurocalliope_constraints(model)

new_model = model.backend.rerun()
new_model.to_netcdf(path_to_output)
```

Then you can have the run step be a snakemake rule with the reference to the constraint scripts in the inputs.

2024-05-03 13:58 UTC, brynpickering commented on config/run.py
This is untested by me, loading files as modules might need some trial and error work

2024-05-14 14:47 UTC, adrienmellot commented
@brynpickering I've addressed the first part of the comments regarding style, not yet the part concerning the `run.py` and the file structure for the custom constraints.

Regarding your comment about splitting the controlled EV annual demand and installed capacities rule into two rules, I've discussed it with Tim and it makes life harder to split it. The reason for that is that the rule outputs one `.csv` file only which is later read to generate the `.yaml` for the model. 

Splitting the rule into two would either require generating two `.csv` files, which makes it harder for the `.yaml` file to be generated afterwards (or two `.yaml` files, which we don't really want), or to have a rule order where one rule first generates a `.csv` and the second rule appends to this. All in all, a little more complex than having just one rule?

2024-05-14 15:33 UTC, brynpickering commented
OK, it's because the template filler can only handle one location-specific CSV. This probably needs fixing as it leads to quite messy implementations like this. Not something to solve in this PR!

2024-05-30 14:34 UTC, adrienmellot commented
For now custom constraints are not implemented (#385). I've thus removed the `run.py` file that there was to avoid any confusion. We discussed that the data processing could still be let through even though for now it is not immediately useful. I haven't updated the changelog and documentation for this PR as I don't think that it would not make much sense for now, it should probably be done once #385 is solved!

2024-05-31 13:57 UTC, brynpickering approved these changes
Final set of suggestions, otherwise OK to go ahead!

2024-05-31 13:57 UTC, brynpickering commented on scripts/transport/road_transport_controlled_constraints.py
> +        ]),
```suggestion
        country_codes=utils.convert_valid_countries(snakemake.params.countries).values()
```

2024-05-31 13:57 UTC, brynpickering commented on scripts/transport/road_transport_controlled_constraints.py
> +import pycountry
```suggestion
from eurocalliopelib import utils
```

2024-05-31 13:57 UTC, brynpickering commented on config/schema.yaml
> +                        description: EV battery size per vehicle type.
Give unit here rather than as a comment in the config

2024-05-31 13:58 UTC, brynpickering requested changes
Actually, can't approve - it needs a changelog entry ;)

2024-06-06 11:31 UTC, brynpickering approved these changes

2024-06-06 11:33 UTC, merged