Update default profile to be a workflow-profile
calliope-project/euro-calliope pull request #361
Opened 2024-04-15 13:39 UTC by timtroendle

Default profile (in `profiles/default`) is now the default workflow profile. Snakemake activates it automatically using the name. This allows the user to inject other profile parameters using the `--profile` cli option. This also allows us to provide the conda configuration as an addition to, rather than a replacement of, the default profile.

Fixes #268

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-04-16 06:16 UTC, sjpfenninger requested changes
The docs actually don't mention that there is a default workflow profile. This should probably be added, e.g. under the "Build" heading in `build.md`. Particularly mentioning that it sets `cores` to `2`.

2024-04-16 06:16 UTC, sjpfenninger commented on profiles/conda/config.yaml
As of v23.10.0, conda uses libmamba as its solver by default. So the two should be equally fast. Do we still need two separate profiles? Furthermore, I think as long as conda is installed as well as mamba, conda is used anyway, irrespective of whether you used mamba to install the `euro-calliope` environment -- unless you run snakemake with `--conda-frontend mamba`.

2024-04-16 07:55 UTC, brynpickering commented
Am I right in saying that it would now not be necessary to include `--profile profiles/conda` when calling snakemake?

2024-04-16 08:23 UTC, sjpfenninger commented on docs/workflow/build-remote.md
> +While you can build Euro-Calliope on [any cluster that is supported by Snakemake](https://snakemake.readthedocs.io/en/v8.10.7/tutorial/additional_features.html#cluster-or-cloud-execution), our defaul
Oh, we're using mkdocs, right. That makes it easier and we should definitely do it...

2024-04-16 10:24 UTC, timtroendle commented on profiles/conda/config.yaml
Can we make the question whether we want to drop `mamba` a separate question? Right now, `mamba` is the default and whenever you want to run the workflow without, you have to use `--profile="profiles/conda"` or `--conda-frontend conda` which is essentially the same.

2024-04-16 10:26 UTC, timtroendle commented
No, it isn't. This pull request isn't changing any behaviour, but it adds the possibility to inject your own profile through `--profile="your-profile"`.

We could get rid of this by dropping mamba support and running conda by default.

2024-04-16 14:41 UTC, sjpfenninger commented on profiles/conda/config.yaml
Yes, agreed, that question is beyond the scope of this PR

2024-04-17 13:17 UTC, brynpickering reviewed
Should `euler/config.yaml` also be updated? It has `conda-prefix` and `software-deployment-method` which are now duplicated in the default profile.

2024-05-02 12:49 UTC, timtroendle commented
Yes, that makes sense. Done.

2024-05-02 12:56 UTC, merged