Fix macOS ARM compatibility by upgrading to libnetcdf 4.8.0
calliope-project/euro-calliope pull request #369
Opened 2024-05-01 14:33 UTC by timtroendle

Recent changes in #357 broke ARM compatibility as libnetcdf 4.7 is not available for macOS ARM. The first available version if 4.8.0 and this is also the only version that is compatible with the other dependencies.

@sjpfenninger could you please check whether this still works on linux?

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-05-06 08:34 UTC, timtroendle commented
@irm-codebase, could you test this on Linux? If not, can you suggest someone on Linux that could review and test?

2024-05-07 06:56 UTC, timtroendle commented
@sjpfenninger I am currently working on this again. I am introducing a CI test that does these checks so we don't have to do them manually.

2024-05-07 07:00 UTC, sjpfenninger commented
Great. Also running this on linux right now, it seems to be fine so far. All the envs built.

2024-05-07 07:13 UTC, sjpfenninger approved these changes
Works in local testing

2024-05-07 08:28 UTC, brynpickering requested changes

2024-05-07 08:28 UTC, brynpickering commented on .github/workflows/environments.yaml
> +        shell: bash -el {0}
Set this is a top-level default:

```
defaults:
  run:
    shell: bash -l {0}
```

2024-05-07 08:28 UTC, brynpickering commented on .github/workflows/environments.yaml
> +    runs-on: ["ubuntu-latest", "macos-latest"]
These need to be in a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) not in a list on `runs-on` (see [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on) for why not a list):

```
jobs:
  environments-are-installable:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
```

2024-05-07 08:48 UTC, brynpickering commented on .github/workflows/environments.yaml
> +  environments-are-installable:
You need to checkout the project to have access to the files: `- uses: actions/checkout@v3`

2024-05-07 08:48 UTC, brynpickering commented on .github/workflows/environments.yaml
> +        run: conda env create -f ../envs/geo.yaml --dry-run
These should be `conda create`?

2024-05-07 08:52 UTC, timtroendle commented on .github/workflows/environments.yaml
> +        run: conda env create -f ./envs/geo.yaml --dry-run
I think "env create" is just fine. This is similar to how we define it in the docs.

2024-05-07 08:59 UTC, timtroendle commented
In the process, I've decided to drop support for Intel macOS. Maintaining compat of ARM macOS and Linux is hard enough and Intel macOS will only become less important in the future.

2024-05-07 09:00 UTC, timtroendle commented
@brynpickering, the new tests took 4 minutes to run. Do we really want that?

Possibly, I could split the job into several jobs so they run in parallel.

2024-05-07 09:55 UTC, sjpfenninger requested changes
Wait... I spoke too soon..., this fails again in the same old way on linux:

```
Job 101: Extract national potentials and cost from raw biofuel data.

[...]

from ._netCDF4 import *
ImportError: f6f640ac8f16d5d71ef1d7e200f26108_/lib/python3.9/site-packages/netCDF4/../../../libnetcdf.so.19: undefined symbol: H5Pset_fapl_ros3
```

2024-05-07 09:58 UTC, sjpfenninger commented
I think it's good to test that the environments are installable, but this example shows that it's not enough - the failure here is some arcane library import issue that only occurs when the library is actually imported. I wonder if at least for cases like this, an additional test that simply imports all libraries, would be useful.

2024-05-07 10:22 UTC, timtroendle commented
Maybe. I wonder whether what we are seeing here is a bug. This _should_ not happen, right? So I wonder if it's worth to run complex tests for such a case.

Much worse is the fact that this is breaking linux compat. That means we either break linux or mac. A real fix would require updating many more dependencies.

2024-05-07 14:28 UTC, timtroendle commented
Well they are all kinda slow and because they run in sequence in just adds up. Interestingly, the ARM build was a lot faster.

2024-05-07 14:34 UTC, brynpickering commented
You could add another matrix level which is the environment file name, then they would run in parallel jobs. It would just be a longer list to look through in the checks.

2024-05-07 14:35 UTC, timtroendle commented
That's exactly what I am currently preparing :D

2024-05-07 14:39 UTC, timtroendle commented
Ok this is much faster. It clutters the list of checks slightly, but it's in fact cleaner too.

I will now try to find a solution to the dependency problem.

2024-05-07 16:28 UTC, timtroendle commented
This is a mess.

What I found out so far:
* Pinning h5py was a mistake. It was never a dependency and has been  introduced as a dependency.
* libnetcdf 4.8 seems the main problem. Previous versions of Euro-Calliope always used <4.8 because of some third packages (maybe numpy, scipy, or gdal) that required 4.7 instead of 4.8.
* libnetcdf <4.8 isn't available for ARM macOS
* libnetcdf 4.8.1 doesn't fix the problem.
* libnetcdf 4.9.2 fixes the problem. It requires many updates in other dependencies.
* calliope 0.6.10 requires libnetcdf < 4.9

Seems like a deadlock to me.

2024-05-07 16:33 UTC, timtroendle commented
We could provide different versions of libnetcdf for different platforms: 4.8 for Mac, 4.7 for Linux. Snakemake is able to do that, but it would be in a hacky way.
https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#freezing-environments-to-exactly-pinned-packages

2024-05-07 16:46 UTC, timtroendle commented
@brynpickering, @sjpfenninger, doesn't this mean that current Calliope is broken on Linux? Or am I missing something here?

2024-05-07 18:03 UTC, irm-codebase commented
> @brynpickering, @sjpfenninger, doesn't this mean that current Calliope is broken on Linux? Or am I missing something here?

If by that you mean v0.7, no, it works quite well (I've tested the latest dev version on my machine).

2024-05-08 06:52 UTC, timtroendle commented
Thanks, good to know. In fact, I thought of 0.6.10. Even here, I am pretty sure it's not broken, but then some of my bullet points above must be wrong:

> * libnetcdf <4.8 isn't available for ARM macOS
> * libnetcdf 4.8.1 doesn't fix the problem of Linux compat.
> * libnetcdf 4.9.2 fixes the problem of Linux compat. It requires many updates in other dependencies.
> * calliope 0.6.10 requires libnetcdf < 4.9

2024-05-08 15:47 UTC, timtroendle commented
For reference, the above bullet points were incomplete. Obviously, the problem is not in a single library but in the wrong combination of libraries. The following list works on both linux and ARM mac and should solve this issue here:

```
    - netCDF4=1.6.2
    - hdf5=1.12.2
    - libnetcdf=4.8.1
```

2024-05-08 16:12 UTC, timtroendle commented
This (^) seems to fix the Linux compat issue but it requires massive updates in all envs that include GDAL. This is because libgdal depends on hdf5, too, and requires updates. That then requires updates in GDAL, which requires updates in fiona, rasterio, rasterstats, which then require updates in numpy, scipy, and even Python.

It would make sense to fiddle out the minimal change that works, but I won't have time before next week to work on that.

2024-05-09 07:10 UTC, brynpickering commented
A nightmare... In the non-calliope envs, you could do libnetcdf>4.8 to avoid the need to update the GDAL-related things?

2024-05-10 16:34 UTC, brynpickering commented
Necessary updates don't seem to have been quite so drastic as you suggested @timtroendle. I think this is now ready for review!

2024-05-13 08:55 UTC, timtroendle commented on CHANGELOG.md
> +* **UPDATE** environments to fix issues on Linux and Macos-arm64:
Should include reference to this pull request #369 and #357

2024-05-13 08:55 UTC, timtroendle commented on CHANGELOG.md
> +* **FIX** pin `hdf5` and `libnetcdf` in all environments which rely on `xarray`, to prevent issues on linux-x86 (#357, #369).
Seems duplicate of the UPDATE statement above. Considering that this was never broken in releases, this sounds like an update and not a fix to me.

2024-05-13 08:57 UTC, timtroendle commented
> Necessary updates don't seem to have been quite so drastic as you suggested @timtroendle. I think this is now ready for review!

Awesome, thanks for the work! I just love my drama. I'll run the minimal workflow on both systems to verify nothing obvious is broken.

2024-05-14 08:14 UTC, brynpickering commented on .github/workflows/environments.yaml
> +
Would be worth limiting this to only run when there have been changes in the relevant files.
Even better would be to skip matrix items that don't have file changes, but that's more complex (and relies on another third-party plugin).

```suggestion
on:
    push:
        branches:
            - main
            - develop
        paths:
           - envs/*.yaml
           - templates/environment.yaml
           - requirements-*.yaml
    pull_request:
        paths:
           - envs/*.yaml
           - templates/environment.yaml
           - requirements-*.yaml
```

2024-05-14 08:16 UTC, brynpickering approved these changes
One suggestion for an update to the workflow file, otherwise good to go.

2024-05-14 08:29 UTC, timtroendle commented on .github/workflows/environments.yaml
> +
Looks nice, great suggestion! The doc says the checks will stay in 'pending' in case path filters kick in, which is maybe not so nice. Anyways, let's give this a try and we can always remove it if we don't like it.

2024-05-14 08:36 UTC, merged