Update ehighways resolution shape generation
calliope-project/euro-calliope pull request #370
Opened 2024-05-03 19:21 UTC by brynpickering

Supercedes #336
Fixes #318 

This is in response to a question you had @timtroendle around defining the shape source in `shapes` in the config. I went to clean up the unresolved comments from #336 and realised that it is a lot cleaner to take that approach. This PR leads to a less flexible solution - E-Highways is baked in more than in #336 - but it is cleaner.

As with #336, it only works with NUTS2013, but I will open an issue about that and have a fix ready to go that I'll add via another PR.
 
## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-05-06 08:54 UTC, timtroendle approved these changes
I am liking this a lot. Just a few minor comments.

2024-05-06 08:54 UTC, timtroendle commented on scripts/shapes/units.py
> +    #
Remove

2024-05-06 08:54 UTC, timtroendle commented on scripts/shapes/units.py
> +def _continental_layer(units: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
Consider renaming to `merge_to_continental_layer` or similar.

2024-05-06 08:55 UTC, timtroendle requested changes
CHANGELOG and documentation updates are missing.

2024-05-06 12:35 UTC, brynpickering commented on config/schema.yaml
> +                                - "Iceland" # added for ehighways
sorry, slipped through the net

2024-05-06 12:35 UTC, brynpickering commented on envs/default.yaml
> +    - libnetcdf=4.8.0
I don't have a linux device to try it on, so we'll have to wait for one of the others

2024-05-06 16:45 UTC, brynpickering commented
@timtroendle I've addressed your issues but...

On running the minimal workflow with updated zenodo pointer (to new potentials data that includes `ehighways`), a previous issue rears its head (#99). This would be solved by merging in #239.

2024-05-06 16:50 UTC, timtroendle commented
Will have a look at #239 soon.

2024-05-10 08:43 UTC, brynpickering commented
Minimal workflow now runs successfully, including `all_tests` (which covers the `ehighways` resolution as well as the `regional` one).

2024-05-14 07:50 UTC, timtroendle approved these changes

2024-05-14 07:50 UTC, timtroendle commented on config/schema.yaml
> +                enum: [2013]  # FIXME: enable other years
Doesn't sound like a fixme to me.

2024-05-14 07:52 UTC, merged