Feature: heat pump cop profiles
calliope-project/euro-calliope pull request #393
Opened 2024-06-07 16:42 UTC by brynpickering

Fixes #80 by adding COP profiles.

Builds onchanges made to input weather data in #390.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-06-07 18:48 UTC, irm-codebase reviewed
Minor comments.
Things look generally good!

2024-06-07 18:48 UTC, irm-codebase commented on CHANGELOG.md
> +* **ADD** fully-electrified heat demand (#284, #343, #390, #391) and heat pumps with variable COP to meet that demand (#393).
Swap for #393 for #80. The approach here generally tends to focus on issues, not PRs (although I might be wrong here).

2024-06-07 18:48 UTC, irm-codebase commented on config/default.yaml
> +        correction-factor: 0.85  # [@Ruhnau:2019]
Change for `[@Ruhnau:2019:10.1038/s41597-019-0199-y]`?

2024-06-07 18:48 UTC, irm-codebase commented on rules/heat.smk
> +rule heat_pump_cop_subset:
Consider renaming to `heat_pump_cop`. I think the pypsa people usually name rules and scripts the same, and it's a good rule to follow. Makes searching a bit less ambiguous.

2024-06-07 18:48 UTC, irm-codebase commented on scripts/heat/heat_pump_cop.py
> +        .mean("product")  # ASSUME: take the average of all heat pump products
Is `ASSUME` a general style we follow for assumptions?
It might be good to specify this in the docstring of the function.

2024-06-07 18:48 UTC, irm-codebase commented on scripts/heat/heat_pump_cop.py
> +    assert (
Small recommendation: if you are validating inputs, it's generally better to put these at the very start of the function. It's more explicit to other developers, and generally safer (the function will break before anything else is run if an input is set up improperly).

Nice to have.

2024-06-07 18:48 UTC, irm-codebase commented on envs/default.yaml
> +    - scipy=1.9.1
Is this needed? This is not used in this PR.

2024-06-07 18:58 UTC, timtroendle commented
I am confused. Why are you intending to merge into the `feature-hot-water` branch? Which PR to check first? I will now have  a look at the feature-hot-water PR.

2024-06-09 13:34 UTC, brynpickering commented on CHANGELOG.md
> +* **ADD** fully-electrified heat demand (#284, #343, #390, #391) and heat pumps with variable COP to meet that demand (#393).
We've been doing a bit of both so far... More PRs than issues in recent changelog entries actually. I agree that issues should be prioritised, but we'll need to go in and clean up the changelog to align everything 😄

2024-06-09 13:35 UTC, brynpickering commented on config/default.yaml
> +        correction-factor: 0.85  # [@Ruhnau:2019]
No, we have these short refs that one can look up in the reference list according to that ref name.

2024-06-09 13:36 UTC, brynpickering commented on rules/heat.smk
> +rule heat_pump_cop_subset:
Yeah, I'm not sure why `subset` creeped in there (it's a rule moved over from another repo). I would usually follow the same approach, even without knowing the PyPSA people do it ;)

2024-06-09 13:37 UTC, brynpickering commented on scripts/heat/heat_pump_cop.py
> +        .mean("product")  # ASSUME: take the average of all heat pump products
Yeah, we've been doing it this way for a while. It's a bit like "TODO" and "FIXME". I prefer to keep assumptions close to where the action is, especially since docstrings don't get used in the standard way in snakemake scripts (rendered in docs, referred to in interactive sessions).

2024-06-09 13:38 UTC, brynpickering commented on envs/default.yaml
> +    - scipy=1.9.1
Yes, it's a dependency of xarray when doing linear interpolation. Xarray has a relatively slim set of core dependencies. You only realise you need something for one of their modules when your code breaks 😄

2024-06-09 13:39 UTC, brynpickering commented
> I am confused. Why are you intending to merge into the feature-hot-water branch? Which PR to check first? I will now have a look at the feature-hot-water PR.

To reduce the diff that you would be reviewing. Sorry for pushing this before the hot water one was ready! I thought it would be nice to have it online so that you _could_ review it while I was fixing up review comments on the hot water PR.

2024-06-10 19:37 UTC, irm-codebase approved these changes
Looks good!

2024-06-10 19:37 UTC, irm-codebase commented on envs/default.yaml
> +    - scipy=1.9.1
Should've known. I've seen this on in my own code...

2024-06-10 19:37 UTC, irm-codebase commented on CHANGELOG.md
> +* **ADD** fully-electrified heat demand (#284, #343, #390, #391) and heat pumps with variable COP to meet that demand (#393).
I think including PRs is fine. I mostly commented because I thought it was enforced, so no biggie.

2024-06-19 16:11 UTC, timtroendle requested changes
Looks great.

In the sake of implementing features that can be tested right away, would it possibly to extend this PR to actually building in the heat pump? It seems to me that only a few minor things are missing so that we'd actually have heat pumps, right?

2024-06-19 16:11 UTC, timtroendle commented on scripts/heat/heat_pump_cop.py
> +    # `ds_cop` has dims [site, time], `weight` has dims [site, id], we want a final array with dims [id, time]
ds_cop = cop

2024-06-19 16:11 UTC, timtroendle commented on scripts/heat/heat_pump_cop.py
> +    assert (cop >= 1).all(), "Found improbably low heat pump COP values (< 1)."
These would make great unit tests. I would move them there.

2024-06-20 17:44 UTC, brynpickering commented on scripts/heat/heat_pump_cop.py
> +        path_to_temperature (str): Gridded temperature timeseries data.
We access them from zenodo individually and, because they are large files, I'd keep them separate. Not sure it's worth the intermediate snakemake step to merge them

2024-06-20 18:01 UTC, brynpickering commented on scripts/heat/heat_pump_cop.py
> +    assert (cop >= 1).all(), "Found improbably low heat pump COP values (< 1)."
pros of moving to unit tests: 

* more clear grouping of our tests 
* availability of pytest infrastructure
cons:  
* you don't find out something is a problem until the entire workflow has been completed (should we instead be aiming for fast failure...?)
* the test is far removed from the code that would cause test failure
* (in this example) the test would come after the data aggregation. I'd fix this by moving the aggregation of gridcells to IDs into the next rule in the process, so this rule's outputs can be fed into a test, but then the output files are quite large.

2024-06-20 18:08 UTC, brynpickering commented on scripts/heat/heat_pump_cop.py
> +    assert (cop >= 1).all(), "Found improbably low heat pump COP values (< 1)."
I guess this is a more high level question of when to test in a snakemake workflow. I'm have implemented the change locally but do wonder whether the cons outweigh the pros...

2024-06-21 07:27 UTC, timtroendle commented on config/default.yaml
> +        sink-temperature:
I think that's fine but it should be mentioned.

2024-06-21 07:30 UTC, timtroendle commented on scripts/heat/heat_pump_cop.py
> +    assert (cop >= 1).all(), "Found improbably low heat pump COP values (< 1)."
I see your point and I agree this may require a high-level discussion. I just want to add another important pro: you can test many more things and, because it's pytest, quite easily. For example, you can execute each test by country.

2024-06-21 07:33 UTC, timtroendle commented on scripts/heat/heat_pump_cop.py
> +    assert (cop >= 1).all(), "Found improbably low heat pump COP values (< 1)."
In terms of code modularity, it would be good to have tests (especially unit tests) closer to the actual scripts. In theory we could have a test runner per "module" (== ".smk" file), but it would add overhead.

2024-06-26 06:44 UTC, brynpickering commented
> would it possibly to extend this PR to actually building in the heat pump? It seems to me that only a few minor things are missing so that we'd actually have heat pumps, right?

Do you mean extending to having the electricity demand from heating be based on the when2heat profile & heat pump COP? Or do you mean having heat pumps as a templated technology option?

2024-06-28 08:52 UTC, brynpickering commented
@timtroendle I have:

1. added a heat pump supply template.
2. processed the heat pump outputs into a COP timeseries file.
3. moved data checks to tests.

It was a bit more work than expected ;)

I also found it a pain to debug tests as you can't drop into the debugger with `breakpoint()` in the same way as with the other scripts. It requires adding `--pdb` to the pytest call. I've added functionality to allow that in the `test` rule/runner.

2024-06-28 08:53 UTC, brynpickering commented
Failing tests are due to too many requests to access either the miniconda `.sh` file or a cached version of it. Not sure how we resolve that.

2024-06-28 08:54 UTC, brynpickering commented on scripts/heat/heat_pump_cop.py
> +    assert (cop >= 1).all(), "Found improbably low heat pump COP values (< 1)."
Moved although I maintain that for intermediate datasets it is better to do the checks as part of the script. For final model files, we can then have tests. This stops us having an overcomplicated DAG where loads of intermediate data files need to be kept around until the penultimate step.

2024-06-28 13:08 UTC, timtroendle requested changes
Awesome!

A few more minor changes. More importantly: updates to the docs are changing. There should be updates here:
https://euro-calliope.readthedocs.io/en/latest/model/customisation/#importing-modules

In the sake of modularity, shouldn't we split the heat yaml template into several files? I tend to think yes. Also, I would add additional techs in additional PRs, together with the respective carriers they require.

2024-06-28 13:08 UTC, timtroendle commented on templates/models/techs/supply/heat.yaml
In terms of modularity, should this file include _only_ heat pumps? I tend to think yes. Also, I'd prefer to include other supply technologies in other PRs, together with their carrier supplies which seem missing in this PR.

2024-06-28 13:09 UTC, timtroendle commented
I wouldn't worry too much about the failing tests. @setup-miniconda's tests are failing, too, so I am assuming they will have this high up on their agenda.

2024-06-28 13:17 UTC, timtroendle commented on tests/model/test_heat.py
> +def test_unscaled_heat(unscaled_space_heat_timeseries):
No, here it doesn't make sense because there are no locations.

2024-06-28 13:19 UTC, timtroendle commented
👆Oops, I wanted to suggest edits and now I've committed them. Must have missed the "suggest" option, sorry.

2024-06-28 13:25 UTC, brynpickering commented on tests/model/test_heat.py
> +def test_cop_monthly(cop_timeseries):
It's effectively being done per location anyway, right? If the test fials, you'd be able to pinpoint the offending location pretty quickly when debugging...

2024-06-28 13:26 UTC, brynpickering commented on templates/models/techs/supply/heat.yaml
oops, sorry. A staging error. I'll revert the non-electricity ones. I'd maybe do it per type of carrier in?

2024-06-28 13:28 UTC, brynpickering commented on templates/models/techs/supply/heat.yaml
> +                energy_cap: {{ mean([5.9 / 10, 5.9 / 8, 76 / 400, 45 / 160]) * 1e6 * scaling_factors.specific_costs }}  # {{ (1 / scaling_factors.specific_costs) | unit("EUR2015/MW_heat") }} | averag
They're all from the DEA. It's definitely better to have them explicitly stated in here as they're easier to compare to the DEA tables. Still, I should probably state it over multiple lines (is that possible with the jinja2 template?) with a comment for each

2024-06-28 13:30 UTC, brynpickering commented on scripts/heat/group_gridded_timeseries.py
> +    """Multi-processing helper function to get the weighted average of all gridcells for a given spatial unit (id)."""
More that it only exists because it is needs to be its own function so that it can be called by the multiprocessor.

2024-06-28 13:32 UTC, brynpickering commented on scripts/heat/group_gridded_timeseries.py
> +        annual_demand (xr.DataArray): Per-unit annual space heating and hot water demands.
It's doing two sets of weighted averages: weighted averaging "sites" into "IDs" (using population) and weighted averaging "space heat" and "hot water" demand into a general profile for "heat" (using annual demands).

2024-06-28 15:20 UTC, brynpickering commented
@timtroendle I think that's all done now. I've opened various issues for things that need to be resolved off the back of this PR.

2024-06-28 19:38 UTC, timtroendle approved these changes
Nice!

Just one, I think important, comment: there is a dependency between the "storage/heat" and "supply/heat" files now which should not be the case. By moving the overrides to the "storage/heat" you should be able to get rid of the dependency. The only remaining dependency are the carrier definitions and we will not and don't have to get rid of those.

2024-06-28 19:38 UTC, timtroendle commented on templates/models/techs/supply/heat-from-electricity.yaml
> +overrides:
These overrides should be in the `templates/models/techs/storage/heat.yaml`, right? Otherwise we are creating a dependency between these two files.

I mean, this will break if users don't import the file with the storage techs.

2024-06-28 19:38 UTC, timtroendle commented on templates/models/techs/supply/heat-from-electricity.yaml
> +overrides:
Also: consider adding these overrides to `tests/resources/test.yaml`.

2024-06-28 19:41 UTC, timtroendle commented on templates/models/techs/supply/heat-from-electricity.yaml
> +{# TODO: weight single-/multi-family technology costs based on regional dwelling ratio #}
Would be useful to link to the Github issue here: #406.

2024-06-30 19:14 UTC, brynpickering commented on templates/models/techs/supply/heat-from-electricity.yaml
> +overrides:
We're creating a dependency either way as they also influence the output carrier of the supply technology. I think they are better off in `supply/heat-from-electricity.yaml` as the storage techs are actually abstract tech groups so there's nothing wrong with including that YAML file as an input by default.

As an aside: this won't be an issue in v0.7 as we can trigger a storage buffer for these kinds of techs when defining them, so I wouldn't put too much weight on whether we've got it perfect right now.

2024-07-01 09:45 UTC, timtroendle commented on templates/models/techs/supply/heat-from-electricity.yaml
> +overrides:
Ok up to you. I guess you have the better overview.

I just think we should try to minimise dependencies between files as much as possible. As far as I can tell, this would be the first dependency between two files. It's also slightly surprising that storage gets added through a file in "supply" instead of "storage".

2024-07-01 10:06 UTC, brynpickering commented on templates/models/techs/supply/heat-from-electricity.yaml
> +overrides:
OK, I've decoupled them now, although this does add a bit of unnecessary model complexity when _not_ using the storage buffers. Since this will all be swept away with v0.7 that complexity is probably fine for now.

2024-07-01 14:30 UTC, merged