Update IRENA hydro generation data
calliope-project/euro-calliope pull request #40
Opened 2020-11-03 15:02 UTC by timtroendle

This adds most recent hydro generation data of IRENA.

2021-04-06 10:22 UTC, brynpickering commented
I'm sorry to have missed this PR @timtroendle. Are the changes still valid?

2021-04-06 10:41 UTC, timtroendle commented
No problem. Yes, they are still valid.

2021-04-06 11:26 UTC, brynpickering requested changes
The code snippet in the notebook is so short that I would remove the notebook and process the excel directly in the workflow. The excel is in 'data' either way. The code can be simplified by keeping the data as a MultiIndex series the whole time and using `xs(...)` when accessing single index level items (even across several index levels) and `.loc[pd.IndexSlice[...]]` when accessing multiple index level items.

2021-04-06 11:26 UTC, brynpickering commented on notebooks/preprocess-irena-data.ipynb
> +{
Why can this not be done inside the workflow? It accesses an Excel and processes it, which seems like something that doesn't need to be separate. It just requires the Excel to be pre-downloaded by the user into `data`

2021-04-06 11:26 UTC, brynpickering commented on notebooks/preprocess-irena-data.ipynb
> +    "COUNTRY_IDS = [\n",
Should it actively access the config and get the scope of countries and work from that? Then you know expplicitly if you have data gaps where certain countries are missing

2021-04-06 11:26 UTC, brynpickering commented on notebooks/preprocess-irena-data.ipynb
> +    "    .dropna(\"index\", subset=[\"country_code\"])\n",
You really just want to drop any NaNs, so you could avoid resetting the index and dropping and just do `dropna()` on the df?

2021-04-06 11:26 UTC, brynpickering commented on src/hydro/inflow_mwh.py
> +        .to_xarray()
do you really need to convert to xarray to get this information (same question for the notebook)? Use `.xs(year, level='year')` to get the relevant year from the MultiIndex.

It would also seem worthwhile to keep the data units in the name moving forward (now  'generation_mwh' )

2021-04-06 15:25 UTC, timtroendle commented on notebooks/preprocess-irena-data.ipynb
> +{
Yes, but there are two reasons against doing that. First, I don't want another manual download here. We should get rid of manual downloads instead of introducing more. Second, this data is not downloadable from their website. It has been sent to me. This notebook is for us to ease updating the data in the future.

2021-04-06 15:27 UTC, timtroendle commented on notebooks/preprocess-irena-data.ipynb
> +    "COUNTRY_IDS = [\n",
Actually no, because this is not in-the-loop for reasons I explained above.

2021-04-06 15:33 UTC, timtroendle commented on src/hydro/inflow_mwh.py
> +        .to_xarray()
Yes, but it actually is: the unit is the variable name, see line 10. This dataframe is only internal anyways.

2021-04-06 15:33 UTC, timtroendle commented on src/hydro/inflow_mwh.py
> +        .to_xarray()
Can do entirely within pandas, ok.

2021-04-06 15:34 UTC, timtroendle commented on notebooks/preprocess-irena-data.ipynb
> +    "    .dropna(\"index\", subset=[\"country_code\"])\n",
Actually, I don't remember why I did this back then. Will have a look again if it can be shortened.

2021-04-06 15:36 UTC, brynpickering commented on src/hydro/inflow_mwh.py
> +        .to_xarray()
Fair enough, then don't bother renaming it?

2021-04-06 15:56 UTC, timtroendle commented on src/hydro/inflow_mwh.py
> +        .to_xarray()
I rename it to avoid a line like this: `annual_national_generation_mwh.loc["generation_gwh"]`

2021-04-07 12:52 UTC, timtroendle commented on notebooks/preprocess-irena-data.ipynb
> +    "    .dropna(\"index\", subset=[\"country_code\"])\n",
Hmm yeah, dropna only works on data, not on the index. I could iterrupt here and reset the index based on a na-cleaned index, but don't think that's much cleaner.

2021-04-07 12:54 UTC, timtroendle commented on notebooks/preprocess-irena-data.ipynb
> +    "COUNTRY_IDS = [\n",
I removed the country ids and keep all countries.

2021-04-07 15:37 UTC, brynpickering approved these changes

2021-04-07 16:00 UTC, merged