Feature heat electricity demand
calliope-project/euro-calliope pull request #408
Opened 2024-07-02 09:35 UTC by brynpickering

Fixes #275 

I have removed fully electrified heat in favour of a heat demand profile and a heat pump technology (via #393) that can meet that demand. This will add model complexity. Anyone wanting a simpler approach would need a rule to combine the heat demand profile with the heat pump COP profile to get an electricity demand profile, then add that to their model instead. @timtroendle do you think it's worth adding that in as an option or not? E.g. a rule to produce `build/models/{resolution}/timeseries/demand/electrified-heat.csv` and then an `electrified-heat` override in `techs/demand/heat.yaml` which can be triggered to point `heat-demand` to the electrified profile and to have `electricity` as its input carrier.
 
## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-07-05 14:26 UTC, timtroendle requested changes
A few comments on code clarity.

I personally would not remove the electrified-heat. I would probably also not include it into the "heat.yaml" but keep the separate "electrified-heat.yaml". That way, we can build models that aren't even aware of the heat carrier. The only change the existing files would need is that instead of a `1` scaling factor, you'd take the cop time series as a scaling factor from heat to electricity.

2024-07-05 14:26 UTC, timtroendle commented on rules/heat.smk
> +        input_dataset = "heat-pump-cop"
Removing it could help somewhat to make the purpose of this rule clearer. Honestly, I am struggling to understand what this rule does and why.

2024-07-05 14:26 UTC, timtroendle commented on rules/heat.smk
> +    message: "Generate {wildcards.resolution} {wildcards.input_dataset} timeseries data from gridded data "
This message is wrong, no? It surely is a copy of "group_gridded_timeseries" which is suboptimal.

2024-07-05 14:26 UTC, timtroendle commented on rules/heat.smk
> +    message: "Generate {wildcards.resolution} {wildcards.input_dataset} timeseries data from gridded data "
As above, this message is wrong.

2024-07-05 14:26 UTC, timtroendle commented on rules/heat.smk
> +    script: "../scripts/heat/heat_pump_final_timeseries.py"
A better name would be "cop_final_timeseries.py". I was struggeling for a while because I thought this would create generation time series which does not make sense.

2024-07-05 14:26 UTC, timtroendle commented on rules/heat.smk
> +rule heat_pump_final_timeseries:
As below, a clearer name to me would be "cop_final_timeseries".

2024-07-05 14:26 UTC, timtroendle commented on scripts/heat/heat_demand_final_timeseries.py
> +        sum(sfh_mfh_shares.values()) == 1
Given floats, this can produce false positives. I'd go for a safer `math.isclose()`.

2024-07-05 14:37 UTC, brynpickering commented on config/default.yaml
> +            SFH: 0.6
Yeah ok, this was a placeholder until we could use per-region census data directly. SFH/MFH is 0.55:0.45 in EFTA countries according to the [2011 census](https://ec.europa.eu/eurostat/databrowser/view/cens_11dwob_r3__custom_12068189/default/table?lang=en).

2024-07-05 14:45 UTC, brynpickering commented on rules/heat.smk
> +        input_dataset = "heat-pump-cop"
I'll leave it there for now as I want to add heat pump capacity as another timeseries and it would bloat this PR to add it in now

2024-07-05 14:47 UTC, brynpickering commented on scripts/heat/heat_demand_final_timeseries.py
> +    It therefore ignores heat pump COP profiles and the possibility of a storage buffer.
We could. I had an estimate or heat pump vs direct electrification shares in SC-EC. I'll need to dig up what I did there.

2024-07-05 14:48 UTC, brynpickering commented on scripts/heat/heat_pump_final_timeseries.py
> +    """Take a weighted average of hot water and space heat end uses (using per-unit annual demands) to return a single "heat" end use timeseries.
No, that's correct. It is taking hot water and space heating end use COP profiles and creating a weighted average "heat" energy carrier.

2024-07-05 14:49 UTC, brynpickering commented on rules/heat.smk
> +    script: "../scripts/heat/heat_pump_final_timeseries.py"
This will change to also include heat pump capacity timeseries too. Will be a PR coming your way soon. I know it isn't ideal but I'm not going to revert this now to reintroduce it very shortly

2024-07-08 17:23 UTC, brynpickering commented on scripts/heat/heat_demand_final_timeseries.py
> +    It therefore ignores heat pump COP profiles and the possibility of a storage buffer.
Looks like I didn't have this share in SC-EC. Looking at the data, we have `ambient_heat` end use consumption which _should_ give us an indication of the proportion of electricity use being used for heat pumps, but it has some key missing values (e.g. household demand in sweden, which I expect to heavily be reliant on heat pumps!).

2024-07-09 07:45 UTC, brynpickering commented on scripts/heat/heat_demand_final_timeseries.py
> +    It therefore ignores heat pump COP profiles and the possibility of a storage buffer.
Actually, this is only useful for calculating electrified heat demand. The ASSUME is referring to distributing historic electricity demand for heating across the hours of the year. What I am assuming is that the profile is not weighted by the relative COP in each hour and just scales the heat demand profile directly.

2024-07-09 15:10 UTC, brynpickering commented
@timtroendle I've added electrified heat back in. One question is how to make it clear that one should choose between heat and electrified heat demands? It can't be done by overrides as you would need to link model files together. You could do it by having neither in there by default (like national transmission) and then forcing a decision to be made on loading the model. The user just _then_ needs to remember to include heat supply techs at the same time as adding heat demand...

2024-07-10 15:14 UTC, timtroendle approved these changes
Awesome! I think this is going to be very useful.

Re mutual exclusivity: Personally, I wouldn't bother on the model-layer. Modellers need to know what they are doing and should figure that they should not add both heat and electrified-heat. Certainly, we should support them in figuring out, and a quick mention in the docs doesn't hurt. I don't think we need to do more.

2024-07-10 15:14 UTC, timtroendle commented on templates/models/techs/supply/historic-electrified-heat.yaml.jinja
> +overrides:
Now that this is a separate module, this override seems unnecessary. If modellers don't want this, they can simply not import the module.

2024-07-10 15:17 UTC, timtroendle commented on Snakefile
> +            "build/models/{resolution}/timeseries/demand/electrified-heat.csv",
Adding both would require a change in `example-model.yaml.jinja`: it would need an explicit list of imports instead of the current import-everything-strategy. Moving forward, that'll make more and more sense as we are adding modules that we do not necessarily want to import.


We may even have two or more example models in the future, each with consistent imports and configurations.

2024-07-22 15:43 UTC, merged