Add `.jinja` suffix; reorganise template rules
calliope-project/euro-calliope pull request #409
Opened 2024-07-02 10:24 UTC by brynpickering

Fixes #404 
Also fixes `ruleorder` issue highlighted in #394. I achieved this by merging `{tech_group}/{tech}` into `{tech_and_group}` which allows us to add wildcard constraints that are combinations of tech group and tech (currently, only `supply/biofuel`).

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-07-03 14:49 UTC, timtroendle requested changes
The jinja part of this PR makes a lot of sense.

The part related to the "tech_locations_template" rules is nice in the sense that it removes all these rule dependencies. It comes at the price that "tech_group" and "tech" are merged into a single wildcard. That's less clear I find, but I didn't find a better solution either.

I definitely think the rules and wildcards should have different naming. I always takes my a while to understand what they are doing.

* "tech_and_group" -> "group_and_tech", because that's the order.
* I suggest to rename all "template" rules to "module" rules, because rules are typically named by their outputs (a model module in these cases) instead of their inputs (a template).
* "locations_template" -> "locations", or "locations_module"
* "techs_and_locations_template" -> "tech_module" (potentially plus "with(out)_location_data", see my comment)
* "bio_techs_and_locations_template" -> "biofuel_tech_module"

2024-07-03 14:49 UTC, timtroendle commented on Snakefile
> +use rule techs_and_locations_template as dummy_tech_locations_template with:
consistent naming would be "dummy_techs_and_locations_template".

2024-07-03 14:49 UTC, timtroendle commented on Snakefile
> +use rule techs_and_locations_template as dummy_tech_locations_template with:
Anyways, maybe different names would be more helpful in communicating the difference. I don't really understand why this is called a "dummy". Is it maybe: "tech_and_locations_template_with(out)_location_specific_data"? That seems the be the differentiating factor to me.

Or even more radical and better in my opinion: "model_component_with(out)_location_specific_data". We don't have a clear rule, but typically rules are named by (1) what they do or (2) what they produce, not by their inputs (here: template).

Or:  "module_with(out)_location_specific_data". That's how we call these files in the documentation. My favourite right now.

2024-07-05 14:05 UTC, brynpickering commented on Snakefile
> +        locations = rules.locations_template.output.csv
`locations_from_template`? I still like the link to templates in the rule name

2024-07-05 14:06 UTC, brynpickering commented on Snakefile
> +        locations = rules.locations_template.output.csv
or `locations_calliope_input`?

2024-07-05 14:30 UTC, timtroendle commented on Snakefile
> +        locations = rules.locations_template.output.csv
Personally, I like `locations_module` best. We already call these files modules and this would be most consistent. I am fine with renaming these files to something else, but I'd be consistent -- including in the docs.

2024-07-05 14:44 UTC, timtroendle approved these changes
I like this. There are a few more things we could change, so that we have a consistent name for this type of files.

2024-07-05 14:44 UTC, timtroendle commented on Snakefile
> +rule model_file_without_specific_data:
`module_without_specific_data`?

2024-07-05 14:44 UTC, timtroendle commented on Snakefile
> +rule non_model_file_without_specific_data:
`auxiliary_file(_without_specific_data)` maybe?

2024-07-05 14:44 UTC, timtroendle commented on Snakefile
>          ),
`input_files` -> `modules`

2024-07-05 14:44 UTC, timtroendle commented on rules/shapes.smk
> +rule locations:
`locations_module`?

2024-07-05 14:44 UTC, timtroendle commented on Snakefile
>          non_model_files = expand(
`auxiliary_files`?

2024-07-09 15:11 UTC, merged