Entsoe data priority
calliope-project/euro-calliope pull request #42
Opened 2021-02-01 15:00 UTC by brynpickering

Change order of priority of OPSD load data sources and explicitly define the order. See #41 for more information.

2021-02-01 17:46 UTC, timtroendle approved these changes
Looks good to me! However, as mentioned over in #41: as entso-e is dropping PS, should we rely on transparency data for future compatibility?

2021-02-01 17:46 UTC, timtroendle commented on src/national_load.py
> +        ["data"]
``.loc[:, "data"]`` would be slightly nicer here, as it's more explicit.

2021-04-06 10:34 UTC, brynpickering commented
@timtroendle in light of the discussion in #41, maybe this would be better dealt with by having the order preference in the config, so a user can decide if they want to drop PS (I would include it preferentially still, based on its seemingly higher accuracy).

2021-04-06 15:21 UTC, timtroendle commented
Fine with me.

2021-04-06 15:22 UTC, timtroendle requested changes
Changes are fine but need to be added in the changelog.

2021-04-06 15:49 UTC, brynpickering commented
Once #45 is in, I'll also update this PR to include a schema entry for the priority list.

2021-04-14 18:08 UTC, brynpickering commented
@timtroendle bump

2021-04-15 06:46 UTC, timtroendle requested changes
I am not convinced by the approach of mixing data sources. I don't think we should do that.

2021-04-15 06:46 UTC, timtroendle commented on scripts/national_load.py
> +    Choosing `entsoe_power_statistics` as main source since OPSD states:
This comment here is weird. You are not selecting here, but in the config.

2021-04-15 06:46 UTC, timtroendle commented on scripts/national_load.py
> +            load_top_priority = load_top_priority.fillna(load_by_attribute[source])
I am not so sure about this. Should we really mix data sources? I'd rather not. When there are only a few hours to fill, I think an interpolation is the best you can do.

Mixing data sources between countries could be fine I'd say. So if "Albania" is not within your top priority data source, go look Albania up in the next on the list.

2021-04-15 07:32 UTC, brynpickering commented on scripts/national_load.py
> +    Choosing `entsoe_power_statistics` as main source since OPSD states:
well, the comment was from before it moved to config ;)

2021-04-15 10:27 UTC, brynpickering commented on scripts/national_load.py
> +            load_top_priority = load_top_priority.fillna(load_by_attribute[source])
Hmm, over one or two hours I agree that interpolation might be better. The majority of missing source data for a particular country is for the entire year. But what about those few cases over several days? In #3 There is gap filling for more than a few days using previous years' data. I would say that this gap filling should preferentially come from alternative data sources for the same year, then from different years, then by interpolation.

Maybe I merge in #3 and then incorporate this into the gap filling process? Go with filling data for more than a few hours from alternative data sources, then from other years, then leave the last few hours to be filled in by interpolation?

2021-04-15 15:55 UTC, timtroendle commented on scripts/national_load.py
> +            load_top_priority = load_top_priority.fillna(load_by_attribute[source])
I find other data sources problematic because they may literally represent a different measure. Using other years can be problematic as well: what if 15 April was not a workday in that other year, but a weekend? Or a holiday?

I'm fine having all these mechanism in, but the default config should be very conservative. Then, one could do all sorts of gap filling things, but one would need to do that explicitly.

2021-04-15 16:32 UTC, brynpickering commented on scripts/national_load.py
> +            load_top_priority = load_top_priority.fillna(load_by_attribute[source])
I agree that it isn't ideal, but that is kind of where we get to when using incomplete datasets. The different sources don't necessarily represent a different measure. More often they are just a different method of quantification of the same measure. Those sources that would be different are low down in the priority list (net consumption vs gross generation). Nevertheless, their profiles would be accurate, just their magnitudes would be slightly different (and by slightly, we're talking on the order of <10% since they just represent the differences caused by transmission losses).

If April 15th were a holiday one year and not the next, the profile and the magnitude would be slightly different, but the error would be *much* less than linearly interpolating from the demand at 23:00 on the 14th and 00:00 on the 16th. 

If we were being conservative, the current workflow should possibly not run: using 2017 Albanian data puts it out of sync with its neighbours who are all using 2016 data. For me the most conservative is to fail and then ask the user to allow gap filling mechanisms. In order of preference for least deviation from what 'actual' demand might be, I would go with: 

1. go down the priority list of data sources, replacing the whole year of data if that is necessary, provided the next options down the list has more data than the one it is replacing,
2. fill from other years where large gaps still exist, and
3. fill by interpolation.

2021-04-16 07:04 UTC, timtroendle commented on scripts/national_load.py
> +            load_top_priority = load_top_priority.fillna(load_by_attribute[source])
Yes, that sounds good to me. Fail, and then let the user decide. And be verbose with manipulations in the log messages, so that the user can afterwards analyse the gap filling.

2021-04-16 07:55 UTC, brynpickering commented
@timtroendle I think I would merge this and #3 in (they both run on the minimal workflow) and then start another PR that merges the two sets of functionalities into one that makes the gap filling more user-driven.

2021-04-16 09:17 UTC, timtroendle commented
Good for me. I opened #66 to keep track of these changes. You can also use #66 for the changelog.

2021-04-16 09:19 UTC, timtroendle approved these changes
Fine with merging this in. Still, I'd prefer to switch this mechanism off by default before merging.

2021-04-16 10:08 UTC, brynpickering commented
Since such a switch hasn't ever really existed, I'll introduce it in the next PR.

2021-04-16 10:51 UTC, timtroendle commented
You could simply remove the other data sources from the config. ;-) I'm just a little concerned because I am working from `develop` at the moment and I'd like to keep it clean because of that (and I think we should always keep it clean). But here as well, if you promise to add the _real_ switch soon, just merge and go on.

2021-04-16 11:20 UTC, brynpickering commented
> You could simply remove the other data sources from the config.

OK, that's done!

2021-04-16 11:24 UTC, timtroendle commented
Thanks!

2021-04-16 11:26 UTC, merged