Add `-o` option to unzip calls
calliope-project/euro-calliope pull request #423
Opened 2024-08-02 13:12 UTC by brynpickering

Fixes #327 

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. All others should be checked by the reviewer. You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Minimal workflow tests pass
- [ ] Tests added to cover contribution
- [ ] Documentation updated
- [ ] Configuration schema updated

2024-08-05 13:45 UTC, timtroendle requested changes
I see how this is solving the issue #327. I would still be reluctant to merge this, because #327 _should_ never happen. Snakemake _should_ take care that the file to be generated is deleted before executing the rule.

I recommend to first better understand #327. Can we reproduce it? Maybe it's a bug in Snakemake? Maybe that bug is solved already in some newer version? Maybe we can solve the bug ourselves?

2024-08-06 19:07 UTC, brynpickering commented
It happens for me too. It's because the `output` is just one of the files that is unzipped, not all of them. I can fix it properly in this instance, but there are other instances in which `-o` is used. 

EDIT: I have now cleaned these up to all be able to unzip without needing `-o` by only extracting the files that are actually needed.

2024-08-07 08:01 UTC, timtroendle approved these changes

2024-08-07 08:01 UTC, timtroendle commented on CHANGELOG.md
> +* **UPDATE** unzip command to always overwrite existing data if it is called (#327).
This comment seems incorrect now. Maybe something like `FIX ensure only relevant data is unzipped (#)`?

2024-08-07 12:21 UTC, brynpickering commented on rules/wind-and-solar.smk
> +    shell: "for file in {output}; do unzip {input} ${{file#'build/data/'}} -d build/data; done"
oh nice, hadn't even clocked the `shadow` on this rule.

2024-08-07 12:37 UTC, merged