Update gap filling method
calliope-project/euro-calliope pull request #91
Opened 2021-04-27 16:56 UTC by brynpickering

Fixes #66 by adding in many gap filling methods for national load data. The methods are:
1. Interpolate across hours with a fixed limit of hours up to which that is allowed.
2. Fill from other years, within a threshold of years one can look to
3. Fill 29th of february with 28th whenever working with a leap year and filling from other years / interpolation proved incapable of filling the day.
3. Clean outliers.
4. Choose data from most trusted data source first. This happens on a per-country level after all other gap filling, and selects the first data source it can find with all hours filled in.

Ideally there would be a myriad of tests for this, but I want to get the process reviewed before going all in on tests.

2021-05-06 18:06 UTC, brynpickering commented
@timtroendle I'd appreciate your thoughts on this, since it could prove to be a bottleneck once considering different model years. Is it going too far or is it too complex? Maybe you have some ideas on how to make it cleaner...?

2021-05-11 06:48 UTC, timtroendle requested changes
Looks good. As this is a complex routine now, it requires some more work to make sure it does what we think it does and to keep it maintainable.

2021-05-11 07:06 UTC, brynpickering commented on scripts/national_load.py
> +    return _interpolate_gaps(cleaned_load, data_quality_config["interpolate-hours"])
So I do think this is still worthwhile, since it is basically saying 'do everything you can to make my favourite data source usable for this year but if after all your hard work you can't, then just take the next available data source in my priority list which has all data points'.

2021-05-11 08:29 UTC, brynpickering commented on scripts/national_load.py
> +    preferred_order_of_years_with_data = list(allowed_years_with_data.sort_values(key=__give_older_years_lower_priority, ascending=False))
No, you're correct. Will fix.

2021-05-12 08:06 UTC, timtroendle commented on config/schema.yaml
> +                        description: Whether or not to gap-fill empty 29th of February data for leap years with data from the day before.
All good. Somehow the description must make this obvious.

2021-05-12 08:13 UTC, timtroendle commented on scripts/national_load.py
> +- remove outlier data and interpolate across any newly formed small gaps
It cannot, can it? If you remove outlier in the entire dataset, you cannot introduce them with any of the gap-filling methods.

2021-05-12 08:19 UTC, timtroendle commented on scripts/national_load.py
> +    return _interpolate_gaps(cleaned_load, data_quality_config["interpolate-hours"])
Sorry, but I'm not sure to understand. This was not supposed to say anything about the data-source-gap-filling-method. This comment links back to my earlier comment that outlier handling should come first and it should not come with its own gap-filling method. The two should be separate things.

2021-05-12 08:36 UTC, brynpickering commented on scripts/national_load.py
> +- remove outlier data and interpolate across any newly formed small gaps
Depends on what you are calculating an outlier against. Averages between data sources might be different and thus lead to different pointers to outliers. I don't really mind, though. I can just do the outlier handling first.

2021-05-12 08:37 UTC, brynpickering commented on scripts/national_load.py
> +    return _interpolate_gaps(cleaned_load, data_quality_config["interpolate-hours"])
OK, sure, sorry for the confusion.

2021-05-12 08:42 UTC, timtroendle commented on scripts/national_load.py
> +- remove outlier data and interpolate across any newly formed small gaps
Fair point. But wouldn't it make the outlier detection even stronger, if we were basing it not on a single year, but more data? Either way, I think we should and could think about better methods for detecting outliers anyway.

2021-05-12 08:57 UTC, brynpickering commented on scripts/national_load.py
> +- remove outlier data and interpolate across any newly formed small gaps
Agreed. We could do e.g. a Z-score outlier detection with scipy. I would be worried that our current bounds (0.25 - 2) would erroneously pick up outliers in countries where electricity demand has increased markedly over the last 20 years, hence why I'd only concern ourselves with outliers present in the gap-filled 1-year datasets...

2021-05-12 10:54 UTC, brynpickering commented
I would like to have unit tests on a bunch of these functions, so plan to move several of them to a `data-quality` specific lib directory. Does this make sense @timtroendle ?

2021-05-12 10:57 UTC, timtroendle commented on scripts/national_load.py
> +- remove outlier data and interpolate across any newly formed small gaps
Sounds good. But if you move up outlier detection, you'd need to remove outliers in all years. So I'm fine doing it per year, but you'd need to do it for all years.

2021-05-12 10:59 UTC, timtroendle commented
I am slightly hesitant to moving functions into the lib that have a single purpose. It will only make the script _and_ the lib more difficult to understand and maintain.

If testing is the only purpose, can we find a way to test functions within scripts?

2021-05-13 16:01 UTC, brynpickering commented
This is now waiting on the new testing infrastructure #120 to move forward.

2021-07-21 06:15 UTC, timtroendle commented
With #120 implemented, can we bring this in, too? it's almost finished as far as I remember.

2021-07-22 06:56 UTC, brynpickering commented
@timtroendle tests have now been added which all pass on in the GH workflow.

2021-07-22 14:45 UTC, brynpickering commented
This has now been tested with the minimal workflow with no issues.

2021-07-23 16:49 UTC, timtroendle requested changes
Looks good!

A few more comments about the tests and then this is good to go.

2021-07-23 16:49 UTC, timtroendle commented on tests/scripts/test_national_load.py
> +        load = self.runner(self.data_quality_config())
I like this test. But there are two things I'd change. First, you are replicating the _main_ function of the script in the `runner` function. So in a way, you are testing the runner function, not the script. I'd rather create a function in the script that covers almost everything (likely everything but the writing-to-file) and that you can call and test here.

If you've done that, then `data_quality_config` can become a fixture, and `runner` can disappear (or become another fixture if necessary). That's the second thing I'd do, as it would then stick to the default pytest structure.

2021-07-23 16:49 UTC, timtroendle commented on tests/scripts/test_national_load.py
> +    def data_quality_config(
Should rather be a fixture factory.

https://docs.pytest.org/en/6.2.x/fixture.html?highlight=fixture%20factory#factories-as-fixtures

2021-07-23 16:49 UTC, timtroendle commented on tests/scripts/test_national_load.py
> +        ("config_update", "ALB_in_err", "DEU_in_err", "err_date"),
Can you make it `ALB_in_err_msg`? I only understood this after reading the code.

2021-07-23 16:49 UTC, timtroendle commented on tests/scripts/test_national_load.py
> +            self.runner(config)
As above, I really think you should test a script function here, not the `runner` function. They can easily get out of sync.

2021-07-23 16:49 UTC, timtroendle commented on scripts/national_load.py
> +        (normed_load <= data_quality_config["outlier-data-thresholds"]["relative-to-mean-max"])
Pretty sure we can do better than that. But that's not part of this PR of course. I opened #148.

2021-07-25 09:53 UTC, timtroendle commented on tests/scripts/test_national_load.py
> +                assert country in str(excinfo.value)
```suggestion
                assert excinfo.match(country)
```

2021-07-26 15:02 UTC, brynpickering commented on tests/scripts/test_national_load.py
> +         [2, [[0, 0], [0, 1], [1, 2] , [2, 3], [2, 4]]])
This is an issue of the available interpolate function. It isn't actually the ideal behaviour imo, but it's all that pandas has available...

2021-07-26 15:08 UTC, brynpickering commented on tests/scripts/test_national_load.py
> +        assert np.allclose(expected, interpolated, equal_nan=True)
I would keep it as hours, since the input from the national load data is hourly. Renaming to "steps" suggests that there is the possibility for it to be something else, which there isn't...

2021-07-26 15:26 UTC, timtroendle commented on tests/scripts/test_national_load.py
> +        assert np.allclose(expected, interpolated, equal_nan=True)
Well there is a way. Simply inject a `input_load` that is not resolved hourly. Maybe add a simple 

`assert input_load.index.freq == "H"`?

2021-07-26 15:33 UTC, brynpickering commented on tests/scripts/test_national_load.py
> +        ([[0, 1, 2, np.nan], [0]],
Zero values are included in 'missing' and only those values in the year of interest (2016 here) are included in the list, hence not `[0, 3]`, but `[0]`. I've now updated this to be more explicit and to include the example of using the 2017 year.

2021-07-26 15:49 UTC, brynpickering commented on scripts/national_load.py
> +        (normed_load <= data_quality_config["outlier-data-thresholds"]["relative-to-mean-max"])
Agreed, this came up in conversation some time ago, but I haven't changed the functionality from v1.0 for now.

2021-07-26 15:57 UTC, brynpickering commented on tests/scripts/test_national_load.py
> +        assert np.allclose(expected, interpolated, equal_nan=True)
They would then also need to restructure it to be identical to the raw load data from OPSD, to not fail on loading in. I do this in the tests to have a small dummy load data file whilst having multiple days. Anyway, I will revert to 'steps' because the alternative it lots of work to update the tests!

2021-07-27 13:25 UTC, timtroendle approved these changes
Beautiful!

2021-07-27 14:17 UTC, brynpickering commented
For info: I have tested the full workflow with the default config and years [2015, 2016]. `build/data/electricity-demand-national.csv` builds successfully in both cases.

2021-07-27 14:17 UTC, merged

2021-07-27 14:39 UTC, timtroendle commented
Very cool. This is going to be a very useful addition -- not only but including for #152.